## Análise Exploratória de Dados - State of Data 2024-2025

#### Objetivo: Explorar possíveis indícios de etarismo no mercado de dados, com foco em impactos e tomadas de decisão para negócios.

##### 1. Importações e Configurações

In [19]:
import pandas as pd
import plotly.express as px

##### 2. Carregamento e Leitura Inicial dos Dados

In [2]:
# Dataset original da pesquisa State of Data, foi renomeado para simplificar.
df = pd.read_csv("../data/raw/Dataset_Original.csv")

#### 3. Informações Gerais do DataFrame

In [3]:
# Visializando as primeiras linhas do Dataframe
df.head()

,0.a_token,0.d_data/hora_envio,1.a_idade,1.a.1_faixa_idade,1.b_genero,1.c_cor/raca/etnia,1.d_pcd,1.e_experiencia_profissional_prejudicada,1.e.1_Não acredito que minha experiência profissional seja afetada,"1.e.2_Sim, devido a minha Cor/Raça/Etnia",...,"8.d.3_Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.",8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).,"8.d.5_Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.","8.d.6_Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.","8.d.7_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.","8.d.8_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.","8.d.9_Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.",8.d.10_Criando e gerenciando soluções de Feature Store e cultura de MLOps.,"8.d.11_Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)",8.d.12_Treinando e aplicando LLM's para solucionar problemas de negócio.
0,reb94rv0msth7q4nreb94riaq80iz3yi,16/10/2024 11:19:17,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1zc66g69jjt49y32l1zc66g8wqj79m4e,16/10/2024 20:45:31,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,uu99wmam4n5kc2uu99wmydf0rk7l58f7,17/10/2024 18:10:59,18,17-21,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3ynsw7z0hl5hhpbfvaeqk73ynsw7z04l,22/10/2024 18:03:00,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,v6bji2ct5xckpl1uouv6bjiotkrf3b4f,23/10/2024 01:33:23,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Verificando o número de linhas e colunas.
print(f"Linhas: {df.shape[0]}")
print(f"Colunas: {df.shape[1]}")

Linhas: 5217
Colunas: 403

In [9]:
# Exibindo informações sobre o DataFrame, incluindo tipos de dados e valores não nulos.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5217 entries, 0 to 5216
Columns: 403 entries, 0.a_token to 8.d.12_Treinando e aplicando LLM's para solucionar problemas de negócio.
dtypes: bool(1), float64(323), int64(1), object(78)
memory usage: 16.0+ MB

In [58]:
# Substituí df.columns por este comando para melhor visualizar o DataFrame, que tem muitas colunas.
df.columns.to_list()

['0.a_token',
 '0.d_data/hora_envio',
 '1.a_idade',
 '1.a.1_faixa_idade',
 '1.b_genero',
 '1.c_cor/raca/etnia',
 '1.d_pcd',
 '1.e_experiencia_profissional_prejudicada',
 '1.e.1_Não acredito que minha experiência profissional seja afetada',
 '1.e.2_Sim, devido a minha Cor/Raça/Etnia',
 '1.e.3_Sim, devido a minha identidade de gênero',
 '1.e.4_Sim, devido ao fato de ser PCD',
 '1.i.1_uf_onde_mora',
 '1.f.1_Quantidade de oportunidades de emprego/vagas recebidas',
 '1.f.2_Senioridade das vagas recebidas em relação à sua experiência',
 '1.f.3_Aprovação em processos seletivos/entrevistas',
 '1.f.4_Oportunidades de progressão de carreira',
 '1.f.5_Velocidade de progressão de carreira',
 '1.f.6_Nível de cobrança no trabalho/Stress no trabalho',
 '1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias',
 '1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho',
 '1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho',
 '1.i.2_regiao_onde_mora',
 '1.f_aspectos_prejudicados',
 '1.k.1_uf_de_origem',
 '1.k.2_regiao_de_origem',
 '1.g_vive_no_brasil',
 '1.h_pais_onde_mora',
 '1.i_estado_onde_mora',
 '1.j_vive_no_estado_de_formacao',
 '1.k_estado_de_origem',
 '1.l_nivel_de_ensino',
 '1.m_área_de_formação',
 '2.a_situação_de_trabalho',
 '2.b_setor',
 '2.c_numero_de_funcionarios',
 '2.d_atua_como_gestor',
 '2.e_cargo_como_gestor',
 '2.f_cargo_atual',
 '2.g_nivel',
 '2.h_faixa_salarial',
 '2.i_tempo_de_experiencia_em_dados',
 '2.j_tempo_de_experiencia_em_ti',
 '2.k_satisfeito_atualmente',
 '2.l.1_Remuneração/Salário',
 '2.l.2_Benefícios',
 '2.l.3_Propósito do trabalho e da empresa',
 '2.l.4_Flexibilidade de trabalho remoto',
 '2.l.5_Ambiente e clima de trabalho',
 '2.l.6_Oportunidade de aprendizado e trabalhar com referências',
 '2.l.7_Oportunidades de crescimento',
 '2.l.8_Maturidade da empresa em termos de tecnologia e dados',
 '2.l.9_Relação com os gestores e líderes',
 '2.l.10_Reputação que a empresa tem no mercado',
 '2.l.11_Gostaria de trabalhar em outra área',
 '2.l_motivo_insatisfacao',
 '2.m_participou_de_entrevistas_ultimos_6m',
 '2.n_planos_de_mudar_de_emprego_6m',
 '2.o_criterios_para_escolha_de_emprego',
 '2.o.1_Remuneração/Salário',
 '2.o.2_Benefícios',
 '2.o.3_Propósito do trabalho e da empresa',
 '2.o.4_Flexibilidade de trabalho remoto',
 '2.o.5_Ambiente e clima de trabalho',
 '2.o.6_Oportunidade de aprendizado e trabalhar com referências',
 '2.o.7_Plano de carreira e oportunidades de crescimento',
 '2.o.8_Maturidade da empresa em termos de tecnologia e dados',
 '2.o.9_Qualidade dos gestores e líderes',
 '2.o.10_Reputação que a empresa tem no mercado',
 '2.q_empresa_passou_por_layoff_em_2024',
 '2.r_modelo_de_trabalho_atual',
 '2.s_modelo_de_trabalho_ideal',
 '2.t_atitude_em_caso_de_retorno_presencial',
 '3.a_numero_de_pessoas_em_dados',
 '3.b_cargos_no_time_de_dados_da_empresa',
 '3.b.1_Analytics Engineer',
 '3.b.2_Engenharia de Dados/Data Engineer',
 '3.b.3_Analista de Dados/Data Analyst',
 '3.b.4_Cientista de Dados/Data Scientist',
 '3.b.5_Database Administrator/DBA',
 '3.b.6_Analista de Business Intelligence/BI',
 '3.b.7_Arquiteto de Dados/Data Architect',
 '3.b.8_Data Product Manager/DPM',
 '3.b.9_Business Analyst',
 '3.b.10_ML Engineer/AI Engineer',
 '3.c_responsabilidades_como_gestor',
 '3.c.1_Pensar na visão de longo prazo de dados',
 '3.c.2_Organização de treinamentos e iniciativas',
 '3.c.3_Atração, seleção e contratação',
 '3.c.4_Decisão sobre contratação de ferramentas',
 '3.c.5_gestor da equipe de engenharia de dados',
 '3.c.6_gestor da equipe de estudos, relatórios',
 '3.c.7_gestor da equipe de Inteligência Artificial e Machine Learning',
 '3.c.8_Apesar de ser gestor ainda atuo na parte técnica',
 '3.c.9_Gestão de projetos de dados',
 '3.c.10_Gestão de produtos de dados',
 '3.c.11_Gestão de pessoas',
 '3.d_desafios_como_gestor',
 '3.d.1_Contratar talentos',
 '3.d.2_Reter talentos',
 '3.d.3_Convencer a empresa a aumentar investimentos',
 '3.d.4_Gestão de equipes no ambiente remoto',
 '3.d.5_Gestão de projetos envolvendo áreas multidisciplinares',
 '3.d.6_Organizar as informações com qualidade e confiabilidade',
 '3.d.7_Processar e armazenar um alto volume de dados',
 '3.d.8_Gerar valor para as áreas de negócios',
 '3.d.9_Desenvolver e manter modelos Machine Learning em produção',
 '3.d.10_Gerenciar a expectativa das áreas',
 '3.d.11_Garantir a manutenção dos projetos e modelos em produção',
 '3.d.12_Conseguir levar inovação para a empresa',
 '3.d.13_Garantir (ROI) em projetos de dados',
 '3.d.14_Dividir o tempo entre entregas técnicas e gestão',
 '3.e_ai_generativa_e_llm_é_uma_prioridade?',
 '3.f_tipo_de_uso_de_ai_generativa_e_llm_na_empresa',
 '3.f.1 Colaboradores usando AI generativa de forma independente e descentralizada',
 '3.f.2 Direcionamento centralizado do uso de AI generativa',
 '3.f.3 Desenvolvedores utilizando Copilots',
 '3.f.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais',
 '3.f.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores',
 '3.f.6 IA Generativa e LLMs como principal frente do negócio',
 '3.f.7 IA Generativa e LLMs não é prioridade',
 '3.f.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa',
 '3.g_motivos_para_não_usar_ai_generativa_e_llm',
 '3.g.1 Falta de compreensão dos casos de uso',
 '3.g.2 Falta de confiabilidade das saídas (alucinação dos modelos)',
 '3.g.3 Incerteza em relação a regulamentação',
 '3.g.4 Preocupações com segurança e privacidade de dados',
 '3.g.5 Retorno sobre investimento (ROI) não comprovado de IA Generativa',
 '3.g.6 Dados da empresa não estão prontos para uso de IA Generativa',
 '3.g.7 Falta de expertise ou falta de recursos',
 '3.g.8 Alta direção da empresa não vê valor ou não vê como prioridade',
 '3.g.9 Preocupações com propriedade intelectual',
 '4.a_funcao_de_atuacao',
 '4.a.1_atuacao_em_dados',
 '4.b_fontes_de_dados_(dia_a_dia)',
 '4.b.1_Dados relacionais (estruturados em bancos SQL)',
 '4.b.2_Dados armazenados em bancos NoSQL',
 '4.b.3_Imagens',
 '4.b.4_Textos/Documentos',
 '4.b.5_Vídeos',
 '4.b.6_Áudios',
 '4.b.7_Planilhas',
 '4.b.8_Dados georeferenciados',
 '4.c_fonte_de_dado_mais_usada',
 '4.c.1_Dados relacionais (estruturados em bancos SQL)',
 '4.c.2_Dados armazenados em bancos NoSQL',
 '4.c.3_Imagens',
 '4.c.4_Textos/Documentos',
 '4.c.5_Vídeos',
 '4.c.6_Áudios',
 '4.c.7_Planilhas',
 '4.c.8_Dados georeferenciados',
 '4.d_linguagem_de_programacao_(dia_a_dia)',
 '4.d.1_SQL',
 '4.d.2_R',
 '4.d.3_Python',
 '4.d.4_C/C++/C#',
 '4.d.5_.NET',
 '4.d.6_Java',
 '4.d.7_Julia',
 '4.d.8_SAS/Stata',
 '4.d.9_Visual Basic/VBA',
 '4.d.10_Scala',
 '4.d.11_Matlab',
 '4.d.12_Rust',
 '4.d.13_PHP',
 '4.d.14_JavaScript',
 '4.d.15_Não utilizo nenhuma das linguagens listadas',
 '4.e_linguagem_mais_usada',
 '4.f_linguagem_preferida',
 '4.g_banco_de_dados_(dia_a_dia)',
 '4.g.1_MySQL',
 '4.g.2_Oracle',
 '4.g.3_SQL SERVER',
 '4.g.4_Amazon Aurora ou RDS',
 '4.g.5_DynamoDB',
 '4.g.6_CoachDB',
 '4.g.7_Cassandra',
 '4.g.8_MongoDB',
 '4.g.9_MariaDB',
 '4.g.10_Datomic',
 '4.g.11_S3',
 '4.g.12_PostgreSQL',
 '4.g.13_ElasticSearch',
 '4.g.14_DB2',
 '4.g.15_Microsoft Access',
 '4.g.16_SQLite',
 '4.g.17_Sybase',
 '4.g.18_Firebase',
 '4.g.19_Vertica',
 '4.g.20_Redis',
 '4.g.21_Neo4J',
 '4.g.22_Google BigQuery',
 '4.g.23_Google Firestore',
 '4.g.24_Amazon Redshift',
 '4.g.25_Amazon Athena',
 '4.g.26_Snowflake',
 '4.g.27_Databricks',
 '4.g.28_HBase',
 '4.g.29_Presto',
 '4.g.30_Splunk',
 '4.g.31_SAP HANA',
 '4.g.32_Hive',
 '4.g.33_Firebird',
 '4.h_cloud_(dia_a_dia)',
 '4.h.1_Amazon Web Services (AWS)',
 '4.h.2_Google Cloud (GCP)',
 '4.h.3_Azure (Microsoft)',
 '4.h.4_Oracle Cloud',
 '4.h.5_IBM',
 '4.h.6_Servidores On Premise/Não utilizamos Cloud',
 '4.h.7_Cloud Própria',
 '4.i_cloud_preferida',
 '4.j_ferramenta_de_bi_(dia_a_dia)',
 '4.j.1_Microsoft PowerBI',
 '4.j.2_Qlik View/Qlik Sense',
 '4.j.3_Tableau',
 '4.j.4_Metabase',
 '4.j.5_Superset',
 '4.j.6_Redash',
 '4.j.7_Looker',
 '4.j.8_Looker Studio(Google Data Studio)',
 '4.j.9_Amazon Quicksight',
 '4.j.10_Alteryx',
 '4.j.11_SAP Business Objects/SAP Analytics',
 '4.j.12_Oracle Business Intelligence',
 '4.j.13_Salesforce/Einstein Analytics',
 '4.j.14_SAS Visual Analytics',
 '4.j.15_Grafana',
 '4.j.16_Pentaho',
 '4.j.17_Fazemos todas as análises utilizando apenas Excel ou planilhas do google',
 '4.j.18_Não utilizo nenhuma ferramenta de BI no trabalho',
 '4.k_ferramenta_de_bi_preferida',
 '4.l_tipo_de_uso_de_ai_generativa_e_llm_na_empresa',
 '4.l.1 Colaboradores usando AI generativa de forma independente e descentralizada',
 '4.l.2 Direcionamento centralizado do uso de AI generativa',
 '4.l.3 Desenvolvedores utilizando Copilots',
 '4.l.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais',
 '4.l.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores',
 '4.l.6 IA Generativa e LLMs como principal frente do negócio',
 '4.l.7 IA Generativa e LLMs não é prioridade',
 '4.l.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa',
 '4.m_usa_chatgpt_ou_copilot_no_trabalho?',
 '4.m.1 Não uso soluções de AI Generativa com foco em produtividade',
 '4.m.2 Uso soluções gratuitas de AI Generativa com foco em produtividade',
 '4.m.3 Uso e pago pelas soluções de AI Generativa com foco em produtividade',
 '4.m.4 A empresa que trabalho paga pelas soluções de AI Generativa com foco em produtividade',
 '4.m.5 Uso soluções do tipo Copilot',
 '5.a_objetivo_na_area_de_dados',
 '5.b_oportunidade_buscada',
 '5.c_tempo_em_busca_de_oportunidade',
 '5.d_experiencia_em_processos_seletivos',
 '6.a_rotina_como_de',
 '6.a.1_Desenvolvo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.',
 "6.a.2_Realizo construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.",
 '6.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 '6.a.4_Atuo na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.',
 '6.a.5_Modelo soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.',
 '6.a.6_Desenvolvo/cuido da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.',
 '6.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
 '6.a.8_Cuido da qualidade dos dados, metadados e dicionário de dados.',
 '6.a.9_Nenhuma das opções listadas refletem meu dia a dia.',
 '6.b_ferramentas_etl_de',
 '6.b.1_Scripts Python',
 '6.b.2_SQL & Stored Procedures',
 '6.b.3_Apache Airflow',
 '6.b.4_Apache NiFi',
 '6.b.5_Luigi',
 '6.b.6_AWS Glue',
 '6.b.7_Talend',
 '6.b.8_Pentaho',
 '6.b.9_Alteryx',
 '6.b.10_Stitch',
 '6.b.11_Fivetran',
 '6.b.12_Google Dataflow',
 '6.b.13_Oracle Data Integrator',
 '6.b.14_IBM DataStage',
 '6.b.15_SAP BW ETL',
 '6.b.16_SQL Server Integration Services (SSIS)',
 '6.b.17_SAS Data Integration',
 '6.b.18_Qlik Sense',
 '6.b.19_Knime',
 '6.b.20_Databricks',
 '6.b.21_Não utilizo ferramentas de ETL',
 '6.c_possui_data_lake',
 '6.d_tecnologia_data_lake',
 '6.e_possui_data_warehouse',
 '6.f_tecnologia_data_warehouse',
 '6.g_ferramentas_de_qualidade_de_dados_(dia_a_dia)',
 '6.h_maior_tempo_gasto_como_de',
 '6.h.1_Desenvolvendo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.',
 '6.h.2_Realizando construções de ETL\\s em ferramentas como Pentaho, Talend, Dataflow etc.',
 '6.h.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 '6.h.4_Atuando na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.',
 '6.h.5_Modelando soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.',
 '6.h.6_Desenvolvendo/cuidando da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.',
 '6.h.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
 '6.h.8_Cuidando da qualidade dos dados, metadados e dicionário de dados.',
 '6.h.9_Nenhuma das opções listadas refletem meu dia a dia.',
 '7.a_rotina_como_da',
 '7.a.1_Processo e analiso dados utilizando linguagens de programação como Python, R etc.',
 '7.a.2_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.',
 '7.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 '7.a.4_Utilizo API\\s para extrair dados e complementar minhas análises.',
 '7.a.5_Realizo experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.',
 '7.a.6_Desenvolvo/cuido da manutenção de ETL\\s utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.',
 '7.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.',
 '7.a.8_Desenvolvo/cuido da manutenção de planilhas para atender as áreas de negócio.',
 '7.a.9_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.',
 '7.a.10_Nenhuma das opções listadas refletem meu dia a dia.',
 '7.b_ferramentas_etl_da',
 '7.b.1_Scripts Python',
 '7.b.2_SQL & Stored Procedures',
 '7.b.3_Apache Airflow',
 '7.b.4_Apache NiFi',
 '7.b.5_Luigi',
 '7.b.6_AWS Glue',
 '7.b.7_Talend',
 '7.b.8_Pentaho',
 '7.b.9_Alteryx',
 '7.b.10_Stitch',
 '7.b.11_Fivetran',
 '7.b.12_Google Dataflow',
 '7.b.13_Oracle Data Integrator',
 '7.b.14_IBM DataStage',
 '7.b.15_SAP BW ETL',
 '7.b.16_SQL Server Integration Services (SSIS)',
 '7.b.17_SAS Data Integration',
 '7.b.18_Qlik Sense',
 '7.b.19_Knime',
 '7.b.20_Databricks',
 '7.b.21_Não utilizo ferramentas de ETL',
 '7.c_ferramentas_autonomia_area_de_negocios',
 '7.c.1_Ferramentas de AutoML como H2O.ai, Data Robot, BigML etc.',
 '7.c.2_"Point and Click" Analytics como Alteryx, Knime, Rapidminer etc.',
 '7.c.3_Product metricts & Insights como Mixpanel, Amplitude, Adobe Analytics.',
 '7.c.4_Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.',
 '7.c.5_Minha empresa não utiliza essas ferramentas.',
 '7.c.6_Não sei informar.',
 '7.d_maior_tempo_gasto_como_da',
 '7.d.1_Processando e analisando dados utilizando linguagens de programação como Python, R etc.',
 '7.d.2_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.',
 '7.d.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 "7.d.4_Utilizando API's para extrair dados e complementar minhas análises.",
 '7.d.5_Realizando experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.',
 "7.d.6_Desenvolvendo/cuidando da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.",
 '7.d.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
 '7.d.8_Desenvolvendo/cuidando da manutenção de planilhas para atender as áreas de negócio.',
 '7.d.9_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.',
 '7.d.10_Nenhuma das opções listadas refletem meu dia a dia.',
 '8.a_rotina_como_ds',
 '8.a.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.',
 '8.a.2_Sou responsável pela coleta e limpeza dos dados que uso para análise e modelagem.',
 '8.a.3_Sou responsável por entrar em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.',
 '8.a.4_Desenvolvo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).',
 '8.a.5_Sou responsável por colocar modelos em produção, criar os pipelines de dados, APIs de consumo e monitoramento.',
 '8.a.6_Cuido da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.',
 '8.a.7_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc',
 '8.a.8_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.',
 '8.a.9_Crio e dou manutenção em ETLs, DAGs e automações de pipelines de dados.',
 '8.a.10_Crio e gerencio soluções de Feature Store e cultura de MLOps.',
 '8.a.11_Sou responsável por criar e manter a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)',
 "8.a.12_Treino e aplico LLM's para solucionar problemas de negócio.",
 '8.b_tecnicas_e_metodos_ds',
 '8.b.1_Utilizo modelos de regressão (linear, logística, GLM).',
 '8.b.2_Utilizo redes neurais ou modelos baseados em árvore para criar modelos de classificação.',
 '8.b.3_Desenvolvo sistemas de recomendação (RecSys).',
 '8.b.4_Utilizo métodos estatísticos Bayesianos para analisar dados.',
 '8.b.5_Utilizo técnicas de NLP (Natural Language Processing) para análisar dados não-estruturados.',
 '8.b.6_Utilizo métodos estatísticos clássicos (Testes de hipótese, análise multivariada, sobrevivência, dados longitudinais, inferência estatistica) para analisar dados.',
 '8.b.7_Utilizo cadeias de Markov ou HMM\\s para realizar análises de dados.',
 '8.b.8_Desenvolvo técnicas de Clusterização (K-means, Spectral, DBScan etc).',
 '8.b.9_Realizo previsões através de modelos de Séries Temporais (Time Series).',
 '8.b.10_Utilizo modelos de Reinforcement Learning (aprendizado por reforço).',
 '8.b.11_Utilizo modelos de Machine Learning para detecção de fraude.',
 '8.b.12_Utilizo métodos de Visão Computacional.',
 '8.b.13_Utilizo modelos de Detecção de Churn.',
 "8.b.14_Utilizo LLM's para solucionar problemas de negócio.",
 '8.c_tecnologias_ds',
 '8.c.1_Ferramentas de BI (PowerBI, Looker, Tableau, Qlik etc).',
 '8.c.2_Planilhas (Excel, Google Sheets etc).',
 '8.c.3_Ambientes de desenvolvimento local (R-studio, JupyterLab, Anaconda).',
 '8.c.4_Ambientes de desenvolvimento na nuvem (Google Colab, AWS Sagemaker, Kaggle Notebooks etc).',
 '8.c.5_Ferramentas de AutoML (Datarobot, H2O, Auto-Keras etc).',
 '8.c.6_Ferramentas de ETL (Apache Airflow, NiFi, Stitch, Fivetran, Pentaho etc).',
 '8.c.7_Plataformas de Machine Learning (TensorFlow, Azure Machine Learning, Kubeflow etc).',
 '8.c.8_Feature Store (Feast, Hopsworks, AWS Feature Store, Databricks Feature Store etc).',
 '8.c.9_Sistemas de controle de versão (Github, DVC, Neptune, Gitlab etc).',
 '8.c.10_Plataformas de Data Apps (Streamlit, Shiny, Plotly Dash etc).',
 '8.c.11_Ferramentas de estatística avançada como SPSS, SAS, etc.',
 '8.d_maior_tempo_gasto_como_ds',
 '8.d.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.',
 '8.d.2_Coletando e limpando dos dados que uso para análise e modelagem.',
 '8.d.3_Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.',
 '8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).',
 '8.d.5_Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.',
 '8.d.6_Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.',
 '8.d.7_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.',

In [59]:
colunas_secoes = {k: [] for k in range(1, 9)}
colunas_secoes

{1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: []}

In [60]:
# Para cada seção, separar as colunas
for secao in range(1, 9):
    colunas_secoes[secao] = [col for col in df.columns if col.startswith(f"{secao}")]

colunas_secoes

{1: ['1.a_idade',
  '1.a.1_faixa_idade',
  '1.b_genero',
  '1.c_cor/raca/etnia',
  '1.d_pcd',
  '1.e_experiencia_profissional_prejudicada',
  '1.e.1_Não acredito que minha experiência profissional seja afetada',
  '1.e.2_Sim, devido a minha Cor/Raça/Etnia',
  '1.e.3_Sim, devido a minha identidade de gênero',
  '1.e.4_Sim, devido ao fato de ser PCD',
  '1.i.1_uf_onde_mora',
  '1.f.1_Quantidade de oportunidades de emprego/vagas recebidas',
  '1.f.2_Senioridade das vagas recebidas em relação à sua experiência',
  '1.f.3_Aprovação em processos seletivos/entrevistas',
  '1.f.4_Oportunidades de progressão de carreira',
  '1.f.5_Velocidade de progressão de carreira',
  '1.f.6_Nível de cobrança no trabalho/Stress no trabalho',
  '1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias',
  '1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho',
  '1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho',
  '1.i.2_regiao_onde_mora',
  '1.f_aspectos_prejudicados',
  '1.k.1_uf_de_origem',
  '1.k.2_regiao_de_origem',
  '1.g_vive_no_brasil',
  '1.h_pais_onde_mora',
  '1.i_estado_onde_mora',
  '1.j_vive_no_estado_de_formacao',
  '1.k_estado_de_origem',
  '1.l_nivel_de_ensino',
  '1.m_área_de_formação'],
 2: ['2.a_situação_de_trabalho',
  '2.b_setor',
  '2.c_numero_de_funcionarios',
  '2.d_atua_como_gestor',
  '2.e_cargo_como_gestor',
  '2.f_cargo_atual',
  '2.g_nivel',
  '2.h_faixa_salarial',
  '2.i_tempo_de_experiencia_em_dados',
  '2.j_tempo_de_experiencia_em_ti',
  '2.k_satisfeito_atualmente',
  '2.l.1_Remuneração/Salário',
  '2.l.2_Benefícios',
  '2.l.3_Propósito do trabalho e da empresa',
  '2.l.4_Flexibilidade de trabalho remoto',
  '2.l.5_Ambiente e clima de trabalho',
  '2.l.6_Oportunidade de aprendizado e trabalhar com referências',
  '2.l.7_Oportunidades de crescimento',
  '2.l.8_Maturidade da empresa em termos de tecnologia e dados',
  '2.l.9_Relação com os gestores e líderes',
  '2.l.10_Reputação que a empresa tem no mercado',
  '2.l.11_Gostaria de trabalhar em outra área',
  '2.l_motivo_insatisfacao',
  '2.m_participou_de_entrevistas_ultimos_6m',
  '2.n_planos_de_mudar_de_emprego_6m',
  '2.o_criterios_para_escolha_de_emprego',
  '2.o.1_Remuneração/Salário',
  '2.o.2_Benefícios',
  '2.o.3_Propósito do trabalho e da empresa',
  '2.o.4_Flexibilidade de trabalho remoto',
  '2.o.5_Ambiente e clima de trabalho',
  '2.o.6_Oportunidade de aprendizado e trabalhar com referências',
  '2.o.7_Plano de carreira e oportunidades de crescimento',
  '2.o.8_Maturidade da empresa em termos de tecnologia e dados',
  '2.o.9_Qualidade dos gestores e líderes',
  '2.o.10_Reputação que a empresa tem no mercado',
  '2.q_empresa_passou_por_layoff_em_2024',
  '2.r_modelo_de_trabalho_atual',
  '2.s_modelo_de_trabalho_ideal',
  '2.t_atitude_em_caso_de_retorno_presencial'],
 3: ['3.a_numero_de_pessoas_em_dados',
  '3.b_cargos_no_time_de_dados_da_empresa',
  '3.b.1_Analytics Engineer',
  '3.b.2_Engenharia de Dados/Data Engineer',
  '3.b.3_Analista de Dados/Data Analyst',
  '3.b.4_Cientista de Dados/Data Scientist',
  '3.b.5_Database Administrator/DBA',
  '3.b.6_Analista de Business Intelligence/BI',
  '3.b.7_Arquiteto de Dados/Data Architect',
  '3.b.8_Data Product Manager/DPM',
  '3.b.9_Business Analyst',
  '3.b.10_ML Engineer/AI Engineer',
  '3.c_responsabilidades_como_gestor',
  '3.c.1_Pensar na visão de longo prazo de dados',
  '3.c.2_Organização de treinamentos e iniciativas',
  '3.c.3_Atração, seleção e contratação',
  '3.c.4_Decisão sobre contratação de ferramentas',
  '3.c.5_gestor da equipe de engenharia de dados',
  '3.c.6_gestor da equipe de estudos, relatórios',
  '3.c.7_gestor da equipe de Inteligência Artificial e Machine Learning',
  '3.c.8_Apesar de ser gestor ainda atuo na parte técnica',
  '3.c.9_Gestão de projetos de dados',
  '3.c.10_Gestão de produtos de dados',
  '3.c.11_Gestão de pessoas',
  '3.d_desafios_como_gestor',
  '3.d.1_Contratar talentos',
  '3.d.2_Reter talentos',
  '3.d.3_Convencer a empresa a aumentar investimentos',
  '3.d.4_Gestão de equipes no ambiente remoto',
  '3.d.5_Gestão de projetos envolvendo áreas multidisciplinares',
  '3.d.6_Organizar as informações com qualidade e confiabilidade',
  '3.d.7_Processar e armazenar um alto volume de dados',
  '3.d.8_Gerar valor para as áreas de negócios',
  '3.d.9_Desenvolver e manter modelos Machine Learning em produção',
  '3.d.10_Gerenciar a expectativa das áreas',
  '3.d.11_Garantir a manutenção dos projetos e modelos em produção',
  '3.d.12_Conseguir levar inovação para a empresa',
  '3.d.13_Garantir (ROI) em projetos de dados',
  '3.d.14_Dividir o tempo entre entregas técnicas e gestão',
  '3.e_ai_generativa_e_llm_é_uma_prioridade?',
  '3.f_tipo_de_uso_de_ai_generativa_e_llm_na_empresa',
  '3.f.1 Colaboradores usando AI generativa de forma independente e descentralizada',
  '3.f.2 Direcionamento centralizado do uso de AI generativa',
  '3.f.3 Desenvolvedores utilizando Copilots',
  '3.f.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais',
  '3.f.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores',
  '3.f.6 IA Generativa e LLMs como principal frente do negócio',
  '3.f.7 IA Generativa e LLMs não é prioridade',
  '3.f.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa',
  '3.g_motivos_para_não_usar_ai_generativa_e_llm',
  '3.g.1 Falta de compreensão dos casos de uso',
  '3.g.2 Falta de confiabilidade das saídas (alucinação dos modelos)',
  '3.g.3 Incerteza em relação a regulamentação',
  '3.g.4 Preocupações com segurança e privacidade de dados',
  '3.g.5 Retorno sobre investimento (ROI) não comprovado de IA Generativa',
  '3.g.6 Dados da empresa não estão prontos para uso de IA Generativa',
  '3.g.7 Falta de expertise ou falta de recursos',
  '3.g.8 Alta direção da empresa não vê valor ou não vê como prioridade',
  '3.g.9 Preocupações com propriedade intelectual'],
 4: ['4.a_funcao_de_atuacao',
  '4.a.1_atuacao_em_dados',
  '4.b_fontes_de_dados_(dia_a_dia)',
  '4.b.1_Dados relacionais (estruturados em bancos SQL)',
  '4.b.2_Dados armazenados em bancos NoSQL',
  '4.b.3_Imagens',
  '4.b.4_Textos/Documentos',
  '4.b.5_Vídeos',
  '4.b.6_Áudios',
  '4.b.7_Planilhas',
  '4.b.8_Dados georeferenciados',
  '4.c_fonte_de_dado_mais_usada',
  '4.c.1_Dados relacionais (estruturados em bancos SQL)',
  '4.c.2_Dados armazenados em bancos NoSQL',
  '4.c.3_Imagens',
  '4.c.4_Textos/Documentos',
  '4.c.5_Vídeos',
  '4.c.6_Áudios',
  '4.c.7_Planilhas',
  '4.c.8_Dados georeferenciados',
  '4.d_linguagem_de_programacao_(dia_a_dia)',
  '4.d.1_SQL',
  '4.d.2_R',
  '4.d.3_Python',
  '4.d.4_C/C++/C#',
  '4.d.5_.NET',
  '4.d.6_Java',
  '4.d.7_Julia',
  '4.d.8_SAS/Stata',
  '4.d.9_Visual Basic/VBA',
  '4.d.10_Scala',
  '4.d.11_Matlab',
  '4.d.12_Rust',
  '4.d.13_PHP',
  '4.d.14_JavaScript',
  '4.d.15_Não utilizo nenhuma das linguagens listadas',
  '4.e_linguagem_mais_usada',
  '4.f_linguagem_preferida',
  '4.g_banco_de_dados_(dia_a_dia)',
  '4.g.1_MySQL',
  '4.g.2_Oracle',
  '4.g.3_SQL SERVER',
  '4.g.4_Amazon Aurora ou RDS',
  '4.g.5_DynamoDB',
  '4.g.6_CoachDB',
  '4.g.7_Cassandra',
  '4.g.8_MongoDB',
  '4.g.9_MariaDB',
  '4.g.10_Datomic',
  '4.g.11_S3',
  '4.g.12_PostgreSQL',
  '4.g.13_ElasticSearch',
  '4.g.14_DB2',
  '4.g.15_Microsoft Access',
  '4.g.16_SQLite',
  '4.g.17_Sybase',
  '4.g.18_Firebase',
  '4.g.19_Vertica',
  '4.g.20_Redis',
  '4.g.21_Neo4J',
  '4.g.22_Google BigQuery',
  '4.g.23_Google Firestore',
  '4.g.24_Amazon Redshift',
  '4.g.25_Amazon Athena',
  '4.g.26_Snowflake',
  '4.g.27_Databricks',
  '4.g.28_HBase',
  '4.g.29_Presto',
  '4.g.30_Splunk',
  '4.g.31_SAP HANA',
  '4.g.32_Hive',
  '4.g.33_Firebird',
  '4.h_cloud_(dia_a_dia)',
  '4.h.1_Amazon Web Services (AWS)',
  '4.h.2_Google Cloud (GCP)',
  '4.h.3_Azure (Microsoft)',
  '4.h.4_Oracle Cloud',
  '4.h.5_IBM',
  '4.h.6_Servidores On Premise/Não utilizamos Cloud',
  '4.h.7_Cloud Própria',
  '4.i_cloud_preferida',
  '4.j_ferramenta_de_bi_(dia_a_dia)',
  '4.j.1_Microsoft PowerBI',
  '4.j.2_Qlik View/Qlik Sense',
  '4.j.3_Tableau',
  '4.j.4_Metabase',
  '4.j.5_Superset',
  '4.j.6_Redash',
  '4.j.7_Looker',
  '4.j.8_Looker Studio(Google Data Studio)',
  '4.j.9_Amazon Quicksight',
  '4.j.10_Alteryx',
  '4.j.11_SAP Business Objects/SAP Analytics',
  '4.j.12_Oracle Business Intelligence',
  '4.j.13_Salesforce/Einstein Analytics',
  '4.j.14_SAS Visual Analytics',
  '4.j.15_Grafana',
  '4.j.16_Pentaho',
  '4.j.17_Fazemos todas as análises utilizando apenas Excel ou planilhas do google',
  '4.j.18_Não utilizo nenhuma ferramenta de BI no trabalho',
  '4.k_ferramenta_de_bi_preferida',
  '4.l_tipo_de_uso_de_ai_generativa_e_llm_na_empresa',
  '4.l.1 Colaboradores usando AI generativa de forma independente e descentralizada',
  '4.l.2 Direcionamento centralizado do uso de AI generativa',
  '4.l.3 Desenvolvedores utilizando Copilots',
  '4.l.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais',
  '4.l.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores',
  '4.l.6 IA Generativa e LLMs como principal frente do negócio',
  '4.l.7 IA Generativa e LLMs não é prioridade',
  '4.l.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa',
  '4.m_usa_chatgpt_ou_copilot_no_trabalho?',
  '4.m.1 Não uso soluções de AI Generativa com foco em produtividade',
  '4.m.2 Uso soluções gratuitas de AI Generativa com foco em produtividade',
  '4.m.3 Uso e pago pelas soluções de AI Generativa com foco em produtividade',
  '4.m.4 A empresa que trabalho paga pelas soluções de AI Generativa com foco em produtividade',
  '4.m.5 Uso soluções do tipo Copilot'],
 5: ['5.a_objetivo_na_area_de_dados',
  '5.b_oportunidade_buscada',
  '5.c_tempo_em_busca_de_oportunidade',
  '5.d_experiencia_em_processos_seletivos'],
 6: ['6.a_rotina_como_de',
  '6.a.1_Desenvolvo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.',
  "6.a.2_Realizo construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.",
  '6.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
  '6.a.4_Atuo na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.',
  '6.a.5_Modelo soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.',
  '6.a.6_Desenvolvo/cuido da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.',
  '6.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
  '6.a.8_Cuido da qualidade dos dados, metadados e dicionário de dados.',
  '6.a.9_Nenhuma das opções listadas refletem meu dia a dia.',
  '6.b_ferramentas_etl_de',
  '6.b.1_Scripts Python',
  '6.b.2_SQL & Stored Procedures',
  '6.b.3_Apache Airflow',
  '6.b.4_Apache NiFi',
  '6.b.5_Luigi',
  '6.b.6_AWS Glue',
  '6.b.7_Talend',
  '6.b.8_Pentaho',
  '6.b.9_Alteryx',
  '6.b.10_Stitch',
  '6.b.11_Fivetran',
  '6.b.12_Google Dataflow',
  '6.b.13_Oracle Data Integrator',
  '6.b.14_IBM DataStage',
  '6.b.15_SAP BW ETL',
  '6.b.16_SQL Server Integration Services (SSIS)',
  '6.b.17_SAS Data Integration',
  '6.b.18_Qlik Sense',
  '6.b.19_Knime',
  '6.b.20_Databricks',
  '6.b.21_Não utilizo ferramentas de ETL',
  '6.c_possui_data_lake',
  '6.d_tecnologia_data_lake',
  '6.e_possui_data_warehouse',
  '6.f_tecnologia_data_warehouse',
  '6.g_ferramentas_de_qualidade_de_dados_(dia_a_dia)',
  '6.h_maior_tempo_gasto_como_de',
  '6.h.1_Desenvolvendo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.',
  '6.h.2_Realizando construções de ETL\\s em ferramentas como Pentaho, Talend, Dataflow etc.',
  '6.h.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
  '6.h.4_Atuando na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.',
  '6.h.5_Modelando soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.',
  '6.h.6_Desenvolvendo/cuidando da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.',
  '6.h.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
  '6.h.8_Cuidando da qualidade dos dados, metadados e dicionário de dados.',
  '6.h.9_Nenhuma das opções listadas refletem meu dia a dia.'],
 7: ['7.a_rotina_como_da',
  '7.a.1_Processo e analiso dados utilizando linguagens de programação como Python, R etc.',
  '7.a.2_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.',
  '7.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
  '7.a.4_Utilizo API\\s para extrair dados e complementar minhas análises.',
  '7.a.5_Realizo experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.',
  '7.a.6_Desenvolvo/cuido da manutenção de ETL\\s utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.',
  '7.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.',
  '7.a.8_Desenvolvo/cuido da manutenção de planilhas para atender as áreas de negócio.',
  '7.a.9_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.',
  '7.a.10_Nenhuma das opções listadas refletem meu dia a dia.',
  '7.b_ferramentas_etl_da',
  '7.b.1_Scripts Python',
  '7.b.2_SQL & Stored Procedures',
  '7.b.3_Apache Airflow',
  '7.b.4_Apache NiFi',
  '7.b.5_Luigi',
  '7.b.6_AWS Glue',
  '7.b.7_Talend',
  '7.b.8_Pentaho',
  '7.b.9_Alteryx',
  '7.b.10_Stitch',
  '7.b.11_Fivetran',
  '7.b.12_Google Dataflow',
  '7.b.13_Oracle Data Integrator',
  '7.b.14_IBM DataStage',
  '7.b.15_SAP BW ETL',
  '7.b.16_SQL Server Integration Services (SSIS)',
  '7.b.17_SAS Data Integration',
  '7.b.18_Qlik Sense',
  '7.b.19_Knime',
  '7.b.20_Databricks',
  '7.b.21_Não utilizo ferramentas de ETL',
  '7.c_ferramentas_autonomia_area_de_negocios',
  '7.c.1_Ferramentas de AutoML como H2O.ai, Data Robot, BigML etc.',
  '7.c.2_"Point and Click" Analytics como Alteryx, Knime, Rapidminer etc.',
  '7.c.3_Product metricts & Insights como Mixpanel, Amplitude, Adobe Analytics.',
  '7.c.4_Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.',
  '7.c.5_Minha empresa não utiliza essas ferramentas.',
  '7.c.6_Não sei informar.',
  '7.d_maior_tempo_gasto_como_da',
  '7.d.1_Processando e analisando dados utilizando linguagens de programação como Python, R etc.',
  '7.d.2_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.',
  '7.d.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
  "7.d.4_Utilizando API's para extrair dados e complementar minhas análises.",
  '7.d.5_Realizando experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.',
  "7.d.6_Desenvolvendo/cuidando da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.",
  '7.d.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
  '7.d.8_Desenvolvendo/cuidando da manutenção de planilhas para atender as áreas de negócio.',
  '7.d.9_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.',
  '7.d.10_Nenhuma das opções listadas refletem meu dia a dia.'],
 8: ['8.a_rotina_como_ds',
  '8.a.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.',
  '8.a.2_Sou responsável pela coleta e limpeza dos dados que uso para análise e modelagem.',
  '8.a.3_Sou responsável por entrar em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.',
  '8.a.4_Desenvolvo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).',
  '8.a.5_Sou responsável por colocar modelos em produção, criar os pipelines de dados, APIs de consumo e monitoramento.',
  '8.a.6_Cuido da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.',
  '8.a.7_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc',
  '8.a.8_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.',
  '8.a.9_Crio e dou manutenção em ETLs, DAGs e automações de pipelines de dados.',
  '8.a.10_Crio e gerencio soluções de Feature Store e cultura de MLOps.',
  '8.a.11_Sou responsável por criar e manter a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)',
  "8.a.12_Treino e aplico LLM's para solucionar problemas de negócio.",
  '8.b_tecnicas_e_metodos_ds',
  '8.b.1_Utilizo modelos de regressão (linear, logística, GLM).',
  '8.b.2_Utilizo redes neurais ou modelos baseados em árvore para criar modelos de classificação.',
  '8.b.3_Desenvolvo sistemas de recomendação (RecSys).',
  '8.b.4_Utilizo métodos estatísticos Bayesianos para analisar dados.',
  '8.b.5_Utilizo técnicas de NLP (Natural Language Processing) para análisar dados não-estruturados.',
  '8.b.6_Utilizo métodos estatísticos clássicos (Testes de hipótese, análise multivariada, sobrevivência, dados longitudinais, inferência estatistica) para analisar dados.',
  '8.b.7_Utilizo cadeias de Markov ou HMM\\s para realizar análises de dados.',
  '8.b.8_Desenvolvo técnicas de Clusterização (K-means, Spectral, DBScan etc).',
  '8.b.9_Realizo previsões através de modelos de Séries Temporais (Time Series).',
  '8.b.10_Utilizo modelos de Reinforcement Learning (aprendizado por reforço).',
  '8.b.11_Utilizo modelos de Machine Learning para detecção de fraude.',
  '8.b.12_Utilizo métodos de Visão Computacional.',
  '8.b.13_Utilizo modelos de Detecção de Churn.',
  "8.b.14_Utilizo LLM's para solucionar problemas de negócio.",
  '8.c_tecnologias_ds',
  '8.c.1_Ferramentas de BI (PowerBI, Looker, Tableau, Qlik etc).',
  '8.c.2_Planilhas (Excel, Google Sheets etc).',
  '8.c.3_Ambientes de desenvolvimento local (R-studio, JupyterLab, Anaconda).',
  '8.c.4_Ambientes de desenvolvimento na nuvem (Google Colab, AWS Sagemaker, Kaggle Notebooks etc).',
  '8.c.5_Ferramentas de AutoML (Datarobot, H2O, Auto-Keras etc).',
  '8.c.6_Ferramentas de ETL (Apache Airflow, NiFi, Stitch, Fivetran, Pentaho etc).',
  '8.c.7_Plataformas de Machine Learning (TensorFlow, Azure Machine Learning, Kubeflow etc).',
  '8.c.8_Feature Store (Feast, Hopsworks, AWS Feature Store, Databricks Feature Store etc).',
  '8.c.9_Sistemas de controle de versão (Github, DVC, Neptune, Gitlab etc).',
  '8.c.10_Plataformas de Data Apps (Streamlit, Shiny, Plotly Dash etc).',
  '8.c.11_Ferramentas de estatística avançada como SPSS, SAS, etc.',
  '8.d_maior_tempo_gasto_como_ds',
  '8.d.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.',
  '8.d.2_Coletando e limpando dos dados que uso para análise e modelagem.',
  '8.d.3_Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.',
  '8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).',

In [61]:
# Verificando se ficou alguma coluna de fora
todas_colunas_secoes = [item for sublist in colunas_secoes.values() for item in sublist]
todas_colunas_secoes

['1.a_idade',
 '1.a.1_faixa_idade',
 '1.b_genero',
 '1.c_cor/raca/etnia',
 '1.d_pcd',
 '1.e_experiencia_profissional_prejudicada',
 '1.e.1_Não acredito que minha experiência profissional seja afetada',
 '1.e.2_Sim, devido a minha Cor/Raça/Etnia',
 '1.e.3_Sim, devido a minha identidade de gênero',
 '1.e.4_Sim, devido ao fato de ser PCD',
 '1.i.1_uf_onde_mora',
 '1.f.1_Quantidade de oportunidades de emprego/vagas recebidas',
 '1.f.2_Senioridade das vagas recebidas em relação à sua experiência',
 '1.f.3_Aprovação em processos seletivos/entrevistas',
 '1.f.4_Oportunidades de progressão de carreira',
 '1.f.5_Velocidade de progressão de carreira',
 '1.f.6_Nível de cobrança no trabalho/Stress no trabalho',
 '1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias',
 '1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho',
 '1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho',
 '1.i.2_regiao_onde_mora',
 '1.f_aspectos_prejudicados',
 '1.k.1_uf_de_origem',
 '1.k.2_regiao_de_origem',
 '1.g_vive_no_brasil',
 '1.h_pais_onde_mora',
 '1.i_estado_onde_mora',
 '1.j_vive_no_estado_de_formacao',
 '1.k_estado_de_origem',
 '1.l_nivel_de_ensino',
 '1.m_área_de_formação',
 '2.a_situação_de_trabalho',
 '2.b_setor',
 '2.c_numero_de_funcionarios',
 '2.d_atua_como_gestor',
 '2.e_cargo_como_gestor',
 '2.f_cargo_atual',
 '2.g_nivel',
 '2.h_faixa_salarial',
 '2.i_tempo_de_experiencia_em_dados',
 '2.j_tempo_de_experiencia_em_ti',
 '2.k_satisfeito_atualmente',
 '2.l.1_Remuneração/Salário',
 '2.l.2_Benefícios',
 '2.l.3_Propósito do trabalho e da empresa',
 '2.l.4_Flexibilidade de trabalho remoto',
 '2.l.5_Ambiente e clima de trabalho',
 '2.l.6_Oportunidade de aprendizado e trabalhar com referências',
 '2.l.7_Oportunidades de crescimento',
 '2.l.8_Maturidade da empresa em termos de tecnologia e dados',
 '2.l.9_Relação com os gestores e líderes',
 '2.l.10_Reputação que a empresa tem no mercado',
 '2.l.11_Gostaria de trabalhar em outra área',
 '2.l_motivo_insatisfacao',
 '2.m_participou_de_entrevistas_ultimos_6m',
 '2.n_planos_de_mudar_de_emprego_6m',
 '2.o_criterios_para_escolha_de_emprego',
 '2.o.1_Remuneração/Salário',
 '2.o.2_Benefícios',
 '2.o.3_Propósito do trabalho e da empresa',
 '2.o.4_Flexibilidade de trabalho remoto',
 '2.o.5_Ambiente e clima de trabalho',
 '2.o.6_Oportunidade de aprendizado e trabalhar com referências',
 '2.o.7_Plano de carreira e oportunidades de crescimento',
 '2.o.8_Maturidade da empresa em termos de tecnologia e dados',
 '2.o.9_Qualidade dos gestores e líderes',
 '2.o.10_Reputação que a empresa tem no mercado',
 '2.q_empresa_passou_por_layoff_em_2024',
 '2.r_modelo_de_trabalho_atual',
 '2.s_modelo_de_trabalho_ideal',
 '2.t_atitude_em_caso_de_retorno_presencial',
 '3.a_numero_de_pessoas_em_dados',
 '3.b_cargos_no_time_de_dados_da_empresa',
 '3.b.1_Analytics Engineer',
 '3.b.2_Engenharia de Dados/Data Engineer',
 '3.b.3_Analista de Dados/Data Analyst',
 '3.b.4_Cientista de Dados/Data Scientist',
 '3.b.5_Database Administrator/DBA',
 '3.b.6_Analista de Business Intelligence/BI',
 '3.b.7_Arquiteto de Dados/Data Architect',
 '3.b.8_Data Product Manager/DPM',
 '3.b.9_Business Analyst',
 '3.b.10_ML Engineer/AI Engineer',
 '3.c_responsabilidades_como_gestor',
 '3.c.1_Pensar na visão de longo prazo de dados',
 '3.c.2_Organização de treinamentos e iniciativas',
 '3.c.3_Atração, seleção e contratação',
 '3.c.4_Decisão sobre contratação de ferramentas',
 '3.c.5_gestor da equipe de engenharia de dados',
 '3.c.6_gestor da equipe de estudos, relatórios',
 '3.c.7_gestor da equipe de Inteligência Artificial e Machine Learning',
 '3.c.8_Apesar de ser gestor ainda atuo na parte técnica',
 '3.c.9_Gestão de projetos de dados',
 '3.c.10_Gestão de produtos de dados',
 '3.c.11_Gestão de pessoas',
 '3.d_desafios_como_gestor',
 '3.d.1_Contratar talentos',
 '3.d.2_Reter talentos',
 '3.d.3_Convencer a empresa a aumentar investimentos',
 '3.d.4_Gestão de equipes no ambiente remoto',
 '3.d.5_Gestão de projetos envolvendo áreas multidisciplinares',
 '3.d.6_Organizar as informações com qualidade e confiabilidade',
 '3.d.7_Processar e armazenar um alto volume de dados',
 '3.d.8_Gerar valor para as áreas de negócios',
 '3.d.9_Desenvolver e manter modelos Machine Learning em produção',
 '3.d.10_Gerenciar a expectativa das áreas',
 '3.d.11_Garantir a manutenção dos projetos e modelos em produção',
 '3.d.12_Conseguir levar inovação para a empresa',
 '3.d.13_Garantir (ROI) em projetos de dados',
 '3.d.14_Dividir o tempo entre entregas técnicas e gestão',
 '3.e_ai_generativa_e_llm_é_uma_prioridade?',
 '3.f_tipo_de_uso_de_ai_generativa_e_llm_na_empresa',
 '3.f.1 Colaboradores usando AI generativa de forma independente e descentralizada',
 '3.f.2 Direcionamento centralizado do uso de AI generativa',
 '3.f.3 Desenvolvedores utilizando Copilots',
 '3.f.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais',
 '3.f.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores',
 '3.f.6 IA Generativa e LLMs como principal frente do negócio',
 '3.f.7 IA Generativa e LLMs não é prioridade',
 '3.f.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa',
 '3.g_motivos_para_não_usar_ai_generativa_e_llm',
 '3.g.1 Falta de compreensão dos casos de uso',
 '3.g.2 Falta de confiabilidade das saídas (alucinação dos modelos)',
 '3.g.3 Incerteza em relação a regulamentação',
 '3.g.4 Preocupações com segurança e privacidade de dados',
 '3.g.5 Retorno sobre investimento (ROI) não comprovado de IA Generativa',
 '3.g.6 Dados da empresa não estão prontos para uso de IA Generativa',
 '3.g.7 Falta de expertise ou falta de recursos',
 '3.g.8 Alta direção da empresa não vê valor ou não vê como prioridade',
 '3.g.9 Preocupações com propriedade intelectual',
 '4.a_funcao_de_atuacao',
 '4.a.1_atuacao_em_dados',
 '4.b_fontes_de_dados_(dia_a_dia)',
 '4.b.1_Dados relacionais (estruturados em bancos SQL)',
 '4.b.2_Dados armazenados em bancos NoSQL',
 '4.b.3_Imagens',
 '4.b.4_Textos/Documentos',
 '4.b.5_Vídeos',
 '4.b.6_Áudios',
 '4.b.7_Planilhas',
 '4.b.8_Dados georeferenciados',
 '4.c_fonte_de_dado_mais_usada',
 '4.c.1_Dados relacionais (estruturados em bancos SQL)',
 '4.c.2_Dados armazenados em bancos NoSQL',
 '4.c.3_Imagens',
 '4.c.4_Textos/Documentos',
 '4.c.5_Vídeos',
 '4.c.6_Áudios',
 '4.c.7_Planilhas',
 '4.c.8_Dados georeferenciados',
 '4.d_linguagem_de_programacao_(dia_a_dia)',
 '4.d.1_SQL',
 '4.d.2_R',
 '4.d.3_Python',
 '4.d.4_C/C++/C#',
 '4.d.5_.NET',
 '4.d.6_Java',
 '4.d.7_Julia',
 '4.d.8_SAS/Stata',
 '4.d.9_Visual Basic/VBA',
 '4.d.10_Scala',
 '4.d.11_Matlab',
 '4.d.12_Rust',
 '4.d.13_PHP',
 '4.d.14_JavaScript',
 '4.d.15_Não utilizo nenhuma das linguagens listadas',
 '4.e_linguagem_mais_usada',
 '4.f_linguagem_preferida',
 '4.g_banco_de_dados_(dia_a_dia)',
 '4.g.1_MySQL',
 '4.g.2_Oracle',
 '4.g.3_SQL SERVER',
 '4.g.4_Amazon Aurora ou RDS',
 '4.g.5_DynamoDB',
 '4.g.6_CoachDB',
 '4.g.7_Cassandra',
 '4.g.8_MongoDB',
 '4.g.9_MariaDB',
 '4.g.10_Datomic',
 '4.g.11_S3',
 '4.g.12_PostgreSQL',
 '4.g.13_ElasticSearch',
 '4.g.14_DB2',
 '4.g.15_Microsoft Access',
 '4.g.16_SQLite',
 '4.g.17_Sybase',
 '4.g.18_Firebase',
 '4.g.19_Vertica',
 '4.g.20_Redis',
 '4.g.21_Neo4J',
 '4.g.22_Google BigQuery',
 '4.g.23_Google Firestore',
 '4.g.24_Amazon Redshift',
 '4.g.25_Amazon Athena',
 '4.g.26_Snowflake',
 '4.g.27_Databricks',
 '4.g.28_HBase',
 '4.g.29_Presto',
 '4.g.30_Splunk',
 '4.g.31_SAP HANA',
 '4.g.32_Hive',
 '4.g.33_Firebird',
 '4.h_cloud_(dia_a_dia)',
 '4.h.1_Amazon Web Services (AWS)',
 '4.h.2_Google Cloud (GCP)',
 '4.h.3_Azure (Microsoft)',
 '4.h.4_Oracle Cloud',
 '4.h.5_IBM',
 '4.h.6_Servidores On Premise/Não utilizamos Cloud',
 '4.h.7_Cloud Própria',
 '4.i_cloud_preferida',
 '4.j_ferramenta_de_bi_(dia_a_dia)',
 '4.j.1_Microsoft PowerBI',
 '4.j.2_Qlik View/Qlik Sense',
 '4.j.3_Tableau',
 '4.j.4_Metabase',
 '4.j.5_Superset',
 '4.j.6_Redash',
 '4.j.7_Looker',
 '4.j.8_Looker Studio(Google Data Studio)',
 '4.j.9_Amazon Quicksight',
 '4.j.10_Alteryx',
 '4.j.11_SAP Business Objects/SAP Analytics',
 '4.j.12_Oracle Business Intelligence',
 '4.j.13_Salesforce/Einstein Analytics',
 '4.j.14_SAS Visual Analytics',
 '4.j.15_Grafana',
 '4.j.16_Pentaho',
 '4.j.17_Fazemos todas as análises utilizando apenas Excel ou planilhas do google',
 '4.j.18_Não utilizo nenhuma ferramenta de BI no trabalho',
 '4.k_ferramenta_de_bi_preferida',
 '4.l_tipo_de_uso_de_ai_generativa_e_llm_na_empresa',
 '4.l.1 Colaboradores usando AI generativa de forma independente e descentralizada',
 '4.l.2 Direcionamento centralizado do uso de AI generativa',
 '4.l.3 Desenvolvedores utilizando Copilots',
 '4.l.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais',
 '4.l.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores',
 '4.l.6 IA Generativa e LLMs como principal frente do negócio',
 '4.l.7 IA Generativa e LLMs não é prioridade',
 '4.l.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa',
 '4.m_usa_chatgpt_ou_copilot_no_trabalho?',
 '4.m.1 Não uso soluções de AI Generativa com foco em produtividade',
 '4.m.2 Uso soluções gratuitas de AI Generativa com foco em produtividade',
 '4.m.3 Uso e pago pelas soluções de AI Generativa com foco em produtividade',
 '4.m.4 A empresa que trabalho paga pelas soluções de AI Generativa com foco em produtividade',
 '4.m.5 Uso soluções do tipo Copilot',
 '5.a_objetivo_na_area_de_dados',
 '5.b_oportunidade_buscada',
 '5.c_tempo_em_busca_de_oportunidade',
 '5.d_experiencia_em_processos_seletivos',
 '6.a_rotina_como_de',
 '6.a.1_Desenvolvo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.',
 "6.a.2_Realizo construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.",
 '6.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 '6.a.4_Atuo na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.',
 '6.a.5_Modelo soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.',
 '6.a.6_Desenvolvo/cuido da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.',
 '6.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
 '6.a.8_Cuido da qualidade dos dados, metadados e dicionário de dados.',
 '6.a.9_Nenhuma das opções listadas refletem meu dia a dia.',
 '6.b_ferramentas_etl_de',
 '6.b.1_Scripts Python',
 '6.b.2_SQL & Stored Procedures',
 '6.b.3_Apache Airflow',
 '6.b.4_Apache NiFi',
 '6.b.5_Luigi',
 '6.b.6_AWS Glue',
 '6.b.7_Talend',
 '6.b.8_Pentaho',
 '6.b.9_Alteryx',
 '6.b.10_Stitch',
 '6.b.11_Fivetran',
 '6.b.12_Google Dataflow',
 '6.b.13_Oracle Data Integrator',
 '6.b.14_IBM DataStage',
 '6.b.15_SAP BW ETL',
 '6.b.16_SQL Server Integration Services (SSIS)',
 '6.b.17_SAS Data Integration',
 '6.b.18_Qlik Sense',
 '6.b.19_Knime',
 '6.b.20_Databricks',
 '6.b.21_Não utilizo ferramentas de ETL',
 '6.c_possui_data_lake',
 '6.d_tecnologia_data_lake',
 '6.e_possui_data_warehouse',
 '6.f_tecnologia_data_warehouse',
 '6.g_ferramentas_de_qualidade_de_dados_(dia_a_dia)',
 '6.h_maior_tempo_gasto_como_de',
 '6.h.1_Desenvolvendo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.',
 '6.h.2_Realizando construções de ETL\\s em ferramentas como Pentaho, Talend, Dataflow etc.',
 '6.h.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 '6.h.4_Atuando na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.',
 '6.h.5_Modelando soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.',
 '6.h.6_Desenvolvendo/cuidando da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.',
 '6.h.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
 '6.h.8_Cuidando da qualidade dos dados, metadados e dicionário de dados.',
 '6.h.9_Nenhuma das opções listadas refletem meu dia a dia.',
 '7.a_rotina_como_da',
 '7.a.1_Processo e analiso dados utilizando linguagens de programação como Python, R etc.',
 '7.a.2_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.',
 '7.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 '7.a.4_Utilizo API\\s para extrair dados e complementar minhas análises.',
 '7.a.5_Realizo experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.',
 '7.a.6_Desenvolvo/cuido da manutenção de ETL\\s utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.',
 '7.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.',
 '7.a.8_Desenvolvo/cuido da manutenção de planilhas para atender as áreas de negócio.',
 '7.a.9_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.',
 '7.a.10_Nenhuma das opções listadas refletem meu dia a dia.',
 '7.b_ferramentas_etl_da',
 '7.b.1_Scripts Python',
 '7.b.2_SQL & Stored Procedures',
 '7.b.3_Apache Airflow',
 '7.b.4_Apache NiFi',
 '7.b.5_Luigi',
 '7.b.6_AWS Glue',
 '7.b.7_Talend',
 '7.b.8_Pentaho',
 '7.b.9_Alteryx',
 '7.b.10_Stitch',
 '7.b.11_Fivetran',
 '7.b.12_Google Dataflow',
 '7.b.13_Oracle Data Integrator',
 '7.b.14_IBM DataStage',
 '7.b.15_SAP BW ETL',
 '7.b.16_SQL Server Integration Services (SSIS)',
 '7.b.17_SAS Data Integration',
 '7.b.18_Qlik Sense',
 '7.b.19_Knime',
 '7.b.20_Databricks',
 '7.b.21_Não utilizo ferramentas de ETL',
 '7.c_ferramentas_autonomia_area_de_negocios',
 '7.c.1_Ferramentas de AutoML como H2O.ai, Data Robot, BigML etc.',
 '7.c.2_"Point and Click" Analytics como Alteryx, Knime, Rapidminer etc.',
 '7.c.3_Product metricts & Insights como Mixpanel, Amplitude, Adobe Analytics.',
 '7.c.4_Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.',
 '7.c.5_Minha empresa não utiliza essas ferramentas.',
 '7.c.6_Não sei informar.',
 '7.d_maior_tempo_gasto_como_da',
 '7.d.1_Processando e analisando dados utilizando linguagens de programação como Python, R etc.',
 '7.d.2_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.',
 '7.d.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 "7.d.4_Utilizando API's para extrair dados e complementar minhas análises.",
 '7.d.5_Realizando experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.',
 "7.d.6_Desenvolvendo/cuidando da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.",
 '7.d.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
 '7.d.8_Desenvolvendo/cuidando da manutenção de planilhas para atender as áreas de negócio.',
 '7.d.9_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.',
 '7.d.10_Nenhuma das opções listadas refletem meu dia a dia.',
 '8.a_rotina_como_ds',
 '8.a.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.',
 '8.a.2_Sou responsável pela coleta e limpeza dos dados que uso para análise e modelagem.',
 '8.a.3_Sou responsável por entrar em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.',
 '8.a.4_Desenvolvo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).',
 '8.a.5_Sou responsável por colocar modelos em produção, criar os pipelines de dados, APIs de consumo e monitoramento.',
 '8.a.6_Cuido da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.',
 '8.a.7_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc',
 '8.a.8_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.',
 '8.a.9_Crio e dou manutenção em ETLs, DAGs e automações de pipelines de dados.',
 '8.a.10_Crio e gerencio soluções de Feature Store e cultura de MLOps.',
 '8.a.11_Sou responsável por criar e manter a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)',
 "8.a.12_Treino e aplico LLM's para solucionar problemas de negócio.",
 '8.b_tecnicas_e_metodos_ds',
 '8.b.1_Utilizo modelos de regressão (linear, logística, GLM).',
 '8.b.2_Utilizo redes neurais ou modelos baseados em árvore para criar modelos de classificação.',
 '8.b.3_Desenvolvo sistemas de recomendação (RecSys).',
 '8.b.4_Utilizo métodos estatísticos Bayesianos para analisar dados.',
 '8.b.5_Utilizo técnicas de NLP (Natural Language Processing) para análisar dados não-estruturados.',
 '8.b.6_Utilizo métodos estatísticos clássicos (Testes de hipótese, análise multivariada, sobrevivência, dados longitudinais, inferência estatistica) para analisar dados.',
 '8.b.7_Utilizo cadeias de Markov ou HMM\\s para realizar análises de dados.',
 '8.b.8_Desenvolvo técnicas de Clusterização (K-means, Spectral, DBScan etc).',
 '8.b.9_Realizo previsões através de modelos de Séries Temporais (Time Series).',
 '8.b.10_Utilizo modelos de Reinforcement Learning (aprendizado por reforço).',
 '8.b.11_Utilizo modelos de Machine Learning para detecção de fraude.',
 '8.b.12_Utilizo métodos de Visão Computacional.',
 '8.b.13_Utilizo modelos de Detecção de Churn.',
 "8.b.14_Utilizo LLM's para solucionar problemas de negócio.",
 '8.c_tecnologias_ds',
 '8.c.1_Ferramentas de BI (PowerBI, Looker, Tableau, Qlik etc).',
 '8.c.2_Planilhas (Excel, Google Sheets etc).',
 '8.c.3_Ambientes de desenvolvimento local (R-studio, JupyterLab, Anaconda).',
 '8.c.4_Ambientes de desenvolvimento na nuvem (Google Colab, AWS Sagemaker, Kaggle Notebooks etc).',
 '8.c.5_Ferramentas de AutoML (Datarobot, H2O, Auto-Keras etc).',
 '8.c.6_Ferramentas de ETL (Apache Airflow, NiFi, Stitch, Fivetran, Pentaho etc).',
 '8.c.7_Plataformas de Machine Learning (TensorFlow, Azure Machine Learning, Kubeflow etc).',
 '8.c.8_Feature Store (Feast, Hopsworks, AWS Feature Store, Databricks Feature Store etc).',
 '8.c.9_Sistemas de controle de versão (Github, DVC, Neptune, Gitlab etc).',
 '8.c.10_Plataformas de Data Apps (Streamlit, Shiny, Plotly Dash etc).',
 '8.c.11_Ferramentas de estatística avançada como SPSS, SAS, etc.',
 '8.d_maior_tempo_gasto_como_ds',
 '8.d.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.',
 '8.d.2_Coletando e limpando dos dados que uso para análise e modelagem.',
 '8.d.3_Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.',
 '8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).',
 '8.d.5_Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.',
 '8.d.6_Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.',
 '8.d.7_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.',

In [40]:
type(colunas_secoes)

dict

In [41]:
set(df.columns).difference(todas_colunas_secoes)

{'0.a_token', '0.d_data/hora_envio'}

> São colunas que não serão usadas para análise.

##### Analisando cada seção

In [42]:
colunas_secoes[1]

['1.a_idade',
 '1.a.1_faixa_idade',
 '1.b_genero',
 '1.c_cor/raca/etnia',
 '1.d_pcd',
 '1.e_experiencia_profissional_prejudicada',
 '1.e.1_Não acredito que minha experiência profissional seja afetada',
 '1.e.2_Sim, devido a minha Cor/Raça/Etnia',
 '1.e.3_Sim, devido a minha identidade de gênero',
 '1.e.4_Sim, devido ao fato de ser PCD',
 '1.i.1_uf_onde_mora',
 '1.f.1_Quantidade de oportunidades de emprego/vagas recebidas',
 '1.f.2_Senioridade das vagas recebidas em relação à sua experiência',
 '1.f.3_Aprovação em processos seletivos/entrevistas',
 '1.f.4_Oportunidades de progressão de carreira',
 '1.f.5_Velocidade de progressão de carreira',
 '1.f.6_Nível de cobrança no trabalho/Stress no trabalho',
 '1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias',
 '1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho',
 '1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho',
 '1.i.2_regiao_onde_mora',
 '1.f_aspectos_prejudicados',
 '1.k.1_uf_de_origem',
 '1.k.2_regiao_de_origem',
 '1.g_vive_no_brasil',
 '1.h_pais_onde_mora',
 '1.i_estado_onde_mora',
 '1.j_vive_no_estado_de_formacao',
 '1.k_estado_de_origem',
 '1.l_nivel_de_ensino',
 '1.m_área_de_formação']

In [43]:
df[colunas_secoes[1]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5217 entries, 0 to 5216
Data columns (total 31 columns):
 #   Column                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                     --------------  -----
 0   1.a_idade                                                                                                  5217 non-null   int64
 1   1.a.1_faixa_idade                                                                                          5217 non-null   object
 2   1.b_genero                                                                                                 5217 non-null   object
 3   1.c_cor/raca/etnia                                                                                         5217 non-null   object
 4   1.d_pcd                                                                                                    5217 non-null   object
 5   1.e_experiencia_profissional_prejudicada                                                                   2641 non-null   object
 6   1.e.1_Não acredito que minha experiência profissional seja afetada                                         2641 non-null   float64
 7   1.e.2_Sim, devido a minha Cor/Raça/Etnia                                                                   2641 non-null   float64
 8   1.e.3_Sim, devido a minha identidade de gênero                                                             2641 non-null   float64
 9   1.e.4_Sim, devido ao fato de ser PCD                                                                       2641 non-null   float64
 10  1.i.1_uf_onde_mora                                                                                         5075 non-null   object
 11  1.f.1_Quantidade de oportunidades de emprego/vagas recebidas                                               1289 non-null   float64
 12  1.f.2_Senioridade das vagas recebidas em relação à sua experiência                                         1289 non-null   float64
 13  1.f.3_Aprovação em processos seletivos/entrevistas                                                         1289 non-null   float64
 14  1.f.4_Oportunidades de progressão de carreira                                                              1289 non-null   float64
 15  1.f.5_Velocidade de progressão de carreira                                                                 1289 non-null   float64
 16  1.f.6_Nível de cobrança no trabalho/Stress no trabalho                                                     1289 non-null   float64
 17  1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias                                       1289 non-null   float64
 18  1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho                                       1289 non-null   float64
 19  1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho  1289 non-null   float64
 20  1.i.2_regiao_onde_mora                                                                                     5075 non-null   object
 21  1.f_aspectos_prejudicados                                                                                  1289 non-null   object
 22  1.k.1_uf_de_origem                                                                                         953 non-null    object
 23  1.k.2_regiao_de_origem                                                                                     953 non-null    object
 24  1.g_vive_no_brasil                                                                                         5217 non-null   bool
 25  1.h_pais_onde_mora                                                                                         139 non-null    object
 26  1.i_estado_onde_mora                                                                                       5078 non-null   object
 27  1.j_vive_no_estado_de_formacao                                                                             5078 non-null   object
 28  1.k_estado_de_origem                                                                                       977 non-null    object
 29  1.l_nivel_de_ensino                                                                                        5217 non-null   object
 30  1.m_área_de_formação                                                                                       5123 non-null   object
dtypes: bool(1), float64(13), int64(1), object(16)
memory usage: 1.2+ MB

In [44]:
df[colunas_secoes[1]].head()

,1.a_idade,1.a.1_faixa_idade,1.b_genero,1.c_cor/raca/etnia,1.d_pcd,1.e_experiencia_profissional_prejudicada,1.e.1_Não acredito que minha experiência profissional seja afetada,"1.e.2_Sim, devido a minha Cor/Raça/Etnia","1.e.3_Sim, devido a minha identidade de gênero","1.e.4_Sim, devido ao fato de ser PCD",...,1.f_aspectos_prejudicados,1.k.1_uf_de_origem,1.k.2_regiao_de_origem,1.g_vive_no_brasil,1.h_pais_onde_mora,1.i_estado_onde_mora,1.j_vive_no_estado_de_formacao,1.k_estado_de_origem,1.l_nivel_de_ensino,1.m_área_de_formação
0,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,True,NaN,Rio Grande do Sul (RS),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
1,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,...,NaN,PR,Sul,True,NaN,Santa Catarina (SC),False,Paraná (PR),Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
2,18,17-21,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,True,NaN,São Paulo (SP),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
3,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,True,NaN,São Paulo (SP),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
4,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,True,NaN,São Paulo (SP),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...

In [46]:
pd.set_option("display.max_columns", None)
df[colunas_secoes[1]].head()

,1.a_idade,1.a.1_faixa_idade,1.b_genero,1.c_cor/raca/etnia,1.d_pcd,1.e_experiencia_profissional_prejudicada,1.e.1_Não acredito que minha experiência profissional seja afetada,"1.e.2_Sim, devido a minha Cor/Raça/Etnia","1.e.3_Sim, devido a minha identidade de gênero","1.e.4_Sim, devido ao fato de ser PCD",1.i.1_uf_onde_mora,1.f.1_Quantidade de oportunidades de emprego/vagas recebidas,1.f.2_Senioridade das vagas recebidas em relação à sua experiência,1.f.3_Aprovação em processos seletivos/entrevistas,1.f.4_Oportunidades de progressão de carreira,1.f.5_Velocidade de progressão de carreira,1.f.6_Nível de cobrança no trabalho/Stress no trabalho,1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias,"1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho","1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho",1.i.2_regiao_onde_mora,1.f_aspectos_prejudicados,1.k.1_uf_de_origem,1.k.2_regiao_de_origem,1.g_vive_no_brasil,1.h_pais_onde_mora,1.i_estado_onde_mora,1.j_vive_no_estado_de_formacao,1.k_estado_de_origem,1.l_nivel_de_ensino,1.m_área_de_formação
0,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,RS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sul,NaN,NaN,NaN,True,NaN,Rio Grande do Sul (RS),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
1,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,SC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sul,NaN,PR,Sul,True,NaN,Santa Catarina (SC),False,Paraná (PR),Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
2,18,17-21,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,1.0,0.0,0.0,0.0,SP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sudeste,NaN,NaN,NaN,True,NaN,São Paulo (SP),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
3,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,SP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sudeste,NaN,NaN,NaN,True,NaN,São Paulo (SP),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
4,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,SP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sudeste,NaN,NaN,NaN,True,NaN,São Paulo (SP),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...

In [10]:
# Gerando estatísticas descritivas para colunas numéricas.
df.describe()

,1.a_idade,1.e.1_Não acredito que minha experiência profissional seja afetada,"1.e.2_Sim, devido a minha Cor/Raça/Etnia","1.e.3_Sim, devido a minha identidade de gênero","1.e.4_Sim, devido ao fato de ser PCD",1.f.1_Quantidade de oportunidades de emprego/vagas recebidas,1.f.2_Senioridade das vagas recebidas em relação à sua experiência,1.f.3_Aprovação em processos seletivos/entrevistas,1.f.4_Oportunidades de progressão de carreira,1.f.5_Velocidade de progressão de carreira,...,"8.d.3_Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.",8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).,"8.d.5_Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.","8.d.6_Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.","8.d.7_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.","8.d.8_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.","8.d.9_Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.",8.d.10_Criando e gerenciando soluções de Feature Store e cultura de MLOps.,"8.d.11_Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)",8.d.12_Treinando e aplicando LLM's para solucionar problemas de negócio.
count,5217.000000,2641.000000,2641.000000,2641.000000,2641.000000,1289.000000,1289.000000,1289.000000,1289.000000,1289.000000,...,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000
mean,32.358827,0.511927,0.221128,0.319576,0.033321,0.392552,0.359969,0.373157,0.521334,0.556245,...,0.222510,0.298836,0.086675,0.091850,0.041397,0.003881,0.043984,0.009056,0.011643,0.133247
std,7.419433,0.499952,0.415085,0.466401,0.179507,0.488508,0.480177,0.483831,0.499739,0.497019,...,0.416201,0.458044,0.281541,0.289001,0.199336,0.062217,0.205193,0.094791,0.107342,0.340062
min,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,31.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,36.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,68.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

#### 4. Verificação de Valores Faltantes

In [63]:
missing = df.isnull().mean().sort_values(ascending=False)
missing[missing > 0]   # Focando apenas nas variáveis com ausência
print(missing.head(20))

1.h_pais_onde_mora                                                                                                                                                                                     0.973356
5.b_oportunidade_buscada                                                                                                                                                                               0.945179
5.d_experiencia_em_processos_seletivos                                                                                                                                                                 0.944604
5.c_tempo_em_busca_de_oportunidade                                                                                                                                                                     0.944412
5.a_objetivo_na_area_de_dados                                                                                                                                                                          0.896301
6.g_ferramentas_de_qualidade_de_dados_(dia_a_dia)                                                                                                                                                      0.892659
6.f_tecnologia_data_warehouse                                                                                                                                                                          0.860840
6.d_tecnologia_data_lake                                                                                                                                                                               0.859114
8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).                                                                                 0.851831
8.d.5_Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.                                                                                                   0.851831
8.d.6_Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.                                                         0.851831
8.d.10_Criando e gerenciando soluções de Feature Store e cultura de MLOps.                                                                                                                             0.851831
8.d.12_Treinando e aplicando LLM's para solucionar problemas de negócio.                                                                                                                               0.851831
8.d.11_Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)                                                                                      0.851831
8.a.8_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.                                                                                                  0.851831
8.a.9_Crio e dou manutenção em ETLs, DAGs e automações de pipelines de dados.                                                                                                                          0.851831
8.a.10_Crio e gerencio soluções de Feature Store e cultura de MLOps.                                                                                                                                   0.851831
8.a.11_Sou responsável por criar e manter a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)                                                                      0.851831
8.a_rotina_como_ds                                                                                                                                                                                     0.851831
8.a.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.    0.851831
dtype: float64

#### 5. Gráficos Exploratórios Iniciais

In [103]:
# Distribuição da Faixa Etária
g1 = px.histogram(
    df,
    x="1.a.1_faixa_idade",
    title="Distribuição por Faixa Etária",
    text_auto=True,
)
g1.update_layout(xaxis_title="Faixa Etária", yaxis_title="Nº de Pessoas")
g1.show()

In [100]:
# Distribuição por Nível de Senioridade
g2 = px.histogram(
    df,
    x="2.g_nivel",
    title="Distribuição por Nível de Senioridade",
    text_auto=True,
)
g2.update_layout(xaxis_title="Nível do Senioridade", yaxis_title="Nº de Pessoas")
g2.show()

In [98]:
# Mapeamento para rótulos simplificados
mapa_faixas = {
    "Menos de R$ 1.000/mês": "< R$1K",
    "de R$ 1.001/mês a R$ 2.000/mês": "R$1K-2K",
    "de R$ 2.001/mês a R$ 3.000/mês": "R$2K-3K",
    "de R$ 3.001/mês a R$ 4.000/mês": "R$3K-4K",
    "de R$ 4.001/mês a R$ 6.000/mês": "R$4K-6K",
    "de R$ 6.001/mês a R$ 8.000/mês": "R$6K-8K",
    "de R$ 8.001/mês a R$ 12.000/mês": "R$8K-12K",
    "de R$ 12.001/mês a R$ 16.000/mês": "R$12K-16K",
    "de R$ 16.001/mês a R$ 20.000/mês": "R$16K-20K",
    "de R$ 20.001/mês a R$ 25.000/mês": "R$20K-25K",
    "de R$ 25.001/mês a R$ 30.000/mês": "R$25K-30K",
    "de R$ 30.001/mês a R$ 40.000/mês": "R$30K-40K",
    "Acima de R$ 40.001/mês": "> R$40K",
}

# Aplicando a coluna formatada
df["faixa_salarial_simplificada"] = df["2.h_faixa_salarial"].map(mapa_faixas)

# Definindo a nova ordem simplificada
ordem_simplificada = list(mapa_faixas.values())

# Distribuição da Faixa Salarial
g3 = px.histogram(
    df,
    x="faixa_salarial_simplificada",
    category_orders={"faixa_salarial_simplificada": ordem_simplificada},
    title="Distribuição da Faixa Salarial",
    text_auto=True,
)
g3.update_layout(xaxis_title="Faixa Salarial", yaxis_title="Nº de Pessoas")
g3.show()

In [122]:
# Mapeamento para rótulos simplificados
mapa_exp = {
    "Não tenho experiência na área de dados": "Sem experiência",
    "Menos de 1 ano": "<1 ano",
    "de 1 a 2 anos": "1-2 anos",
    "de 3 a 4 anos": "3-4 anos",
    "de 5 a 6 anos": "5-6 anos",
    "de 7 a 10 anos": "7-10 anos",
    "Mais de 10 anos": ">10 anos",
}

# Aplicando a coluna formatada
df["exp_dados_simplificado"] = df["2.i_tempo_de_experiencia_em_dados"].map(mapa_exp)

# Ordem das colunas
ordem_exp = [
    "Sem experiência",
    "<1 ano",
    "1-2 anos",
    "3-4 anos",
    "5-6 anos",
    "7-10 anos",
    ">10 anos",
]

# Distribuição por Tempo de Experiência em Dados
g4 = px.histogram(
    df,
    x="exp_dados_simplificado",
    category_orders={"exp_dados_simplificado": ordem_exp},
    title="Distribuição por Tempo de Experiência em Dados",
    labels={"exp_dados_simplificado": "Tempo de Experiência"},
    text_auto=True
)
g4.update_layout(
    xaxis_title="Tempo de experiência na área de dados", yaxis_title="Nº de Pessoas"
)
g4.show()

In [121]:
# Mapeamento para rótulos
df["atua_como_gestor_bin"] = df["2.d_atua_como_gestor"].map({True: "Sim", False: "Não"})

# Proporção de Pessoas que Atuam como Gestor(a)
g5 = px.histogram(
    df,
    x="atua_como_gestor_bin",
    title="Distribuição de Pessoas em Cargos de Gestão",
    labels={"atua_como_gestor_bin": "Atua como Gestor(a)?"},
    text_auto=True,
)
g5.update_layout(xaxis_title=None, yaxis_title="Nº de Pessoas")
g5.show()

#### Principais Insights da Análise Exploratória
- Perfil Etário: maioria entre 25-39 anos; baixa representatividade de 40+ anos, que é o público-alvo. Isso sugere barreiras de entrada ou menor retenção para profissionais maduros.

- Cargos: predominância de níveis pleno e júnior, com poucos seniores ou de liderança. O mercado foca em funções operacionais, limitando profissionais mais experientes.

- Salário: Concentração entre R$ 4K e R$ 12K; poucos acima de R$ 20K. Pode indicar um "teto salarial" prematuro ou dificuldades na valorização de perfis seniores.

- Experiência: maioria com 3-10 anos na área. O mercado está em consolidação, criando desafios para iniciantes (incluindo maduros em transição) devido à competição.

- Gestão: baixa proporção de gestores, mesmo entre os mais experientes. Isso aponta para um subaproveitamento de perfis experientes que poderiam liderar.

- Dados Ausentes: alta ausência de dados em variáveis sobre objetivos, busca de emprego e processos seletivos. A base reflete principalmente quem já está no mercado de dados, limitando análises sobre a entrada no setor.

### Hipóteses de Pesquisa

#### Hipóteses a serem exploradas

- **H1**: Profissionais 40+ enfrentam mais dificuldade para alcançar oportunidades.
- **H2**: Entre profissionais de dados que já atuam na área, pessoas 40+ tendem a ocupar faixas salariais inferiores às de profissionais mais jovens com o mesmo nível de atuação.
- **H3**: Entre os respondentes da pesquisa, profissionais 40+ tendem a ser menos aproveitados tanto em funções técnicas quanto de liderança, ocupando posições que nem sempre refletem seu perfil ou objetivo de carreira.

##### Hipótese 1 - Profissionais 40+ enfrentam mais dificuldade para alcançar oportunidades

**Pergunta**: entre os entrevistados que atuam ou buscam ativamente atuação em dados, profissionais 40+ demonstram maior dificuldade em alcançar oportunidades de trabalho do que os mais jovens.

**Objetivo da análise**: investigar se há indícios de desigualdade de acesso a oportunidades com base na faixa etária, usando como indicadores:

- Tipo de oportunidade desejada (`5.b_oportunidade_buscada`)
- Tempo de busca por vaga (`5.c_tempo_em_busca_de_oportunidade`)
- Experiência em processos seletivos (`5.d_experiencia_em_processos_seletivos`)

In [132]:
# Filtrando apenas entrevistados que informaram tempo de busca por vaga
df_h1 = df[df["5.c_tempo_em_busca_de_oportunidade"].notna()].copy()

# Criando uma coluna simplificada para grupos etários: 40+ vs <40
df_h1["grupo_idade"] = df_h1["1.a.1_faixa_idade"].apply(
    lambda x: (
        "40+"
        if x
        in [
            "de 40 a 44 anos",
            "de 45 a 49 anos",
            "de 50 a 54 anos",
            "de 55 a 59 anos",
            "60 anos ou mais",
        ]
        else "<40"
    )
)

In [183]:
# 1. Tempo em busca de oportunidade, grupo 40+
# Ordenando as categorias
ordem_tempo = [
    "0 - 6 meses",
    "7 meses - 1 ano",
    "1 ano - 2 anos",
    "acima de 2 anos"
]

g6 = px.histogram(
    df_h1,
    x="5.c_tempo_em_busca_de_oportunidade",
    category_orders={"5.c_tempo_em_busca_de_oportunidade": ordem_tempo},
    text_auto=True,
    title="Tempo em busca de oportunidade em Dados (Grupo 40+)",
    labels={"5.c_tempo_em_busca_de_oportunidade": "Tempo de Busca"},
)
g6.update_layout(xaxis_title="Tempo em busca de oportunidade", yaxis_title="Nº de Pessoas")
g6.show()

In [182]:
# 2. Participação em Processos Seletivos
# Contando e ordenando as categorias da mais frequente para a menos
ordem_experiencia = (
    df_h1["5.d_experiencia_em_processos_seletivos"]
    .value_counts()
    .sort_values(ascending=False)
    .index.tolist()
)


g7 = px.histogram(
    df_h1,
    y="5.d_experiencia_em_processos_seletivos",
    orientation="h",
    text_auto=True,
    title="Participação em Processos Seletivos (Grupo 40+)",
    category_orders={"5.d_experiencia_em_processos_seletivos": ordem_experiencia},
    labels={
        "5.d_experiencia_em_processos_seletivos": "Experiência em Processos Seletivos"
    },
)
g7.update_layout(
    xaxis_title="Nº de Pessoas", yaxis_title="Experiência em Processos Seletivos",
)
g7.show()

In [181]:
# 3. Tipo de oportunidade buscada
# Contandp e ordenando as categorias da mais para a menos buscada
ordem_oportunidade = (
    df_h1["5.b_oportunidade_buscada"]
    .value_counts()
    .sort_values(ascending=False)
    .index.tolist()
)

g8 = px.histogram(
    df_h1,
    y="5.b_oportunidade_buscada",
    orientation="h",
    text_auto=True,
    title="Tipo de Oportunidade Buscada (Grupo 40+)",
    category_orders={"5.b_oportunidade_buscada": ordem_oportunidade},
    labels={"5.b_oportunidade_buscada": "Oportunidade Buscada"},
)

g8.update_layout(xaxis_title="Nº de Pessoas", yaxis_title="Oportunidade Buscada")

g8.show()

##### Conclusão — Hipótese 1

A hipótese investigava se, entre profissionais de dados, pessoas com 40 anos ou mais enfrentam mais dificuldades para conquistar oportunidades do que profissionais mais jovens.

**Principais achados:**

- **Tempo de busca por vagas:** O grupo 40+ apresenta uma distribuição semelhante ao grupo <40, com destaque para busca entre 3 a 6 meses em ambos os grupos.
  
- **Participação em processos seletivos:** A maioria dos respondentes (de todas as idades) participou de poucos ou nenhum processo seletivo, mas o grupo 40+ mostra ligeira tendência a participar menos.

- **Tipo de oportunidade buscada:** Pessoas 40+ buscam majoritariamente oportunidades como analistas e especialistas, e poucas estão focadas em posições de gestão, o que indica desejo de inserção técnica no setor.

**Interpretação:**

Embora os dados não apresentem diferenças gritantes entre os grupos etários, há sinais de que:
- O grupo 40+ **participa menos de processos seletivos**;
- Está em busca ativa de recolocação, porém **não necessariamente direcionado a cargos de liderança**;
- Pode estar enfrentando **barreiras mais sutis**, como **filtro etário invisível em processos seletivos**, o que não aparece diretamente nos dados, mas pode ser complementado em análises qualitativas futuras.

#### 7. Análise das Hipóteses

In [32]:
# H3: Política salarial desfavorece faixas etárias mais velhas?
fig3 = px.box(
    df_h3,
    x="1.a.1_faixa_idade",
    y="2.h_faixa_salarial",
    title="Distribuição Salarial por Faixa Etária",
)
fig3.show()