### Análise Exploratória de Dados - State of Data 2024-2025

#### Contextualização e Objetivos

O mercado de dados está em constante crescimento, mas será que ele é acessível para profissionais em todas as fases da vida? Em áreas que mudam rápido, como TI e marketing digital, pessoas com mais de 40 anos podem enfrentar obstáculos como preconceito por idade e defasagem técnica.

Com base na pesquisa State of Data Brazil 2024-2025, este estudo investiga os principais desafios vividos por profissionais 40+ no setor de dados.

**Objetivos:**
1. Investigar se há desigualdade de oportunidades e crescimento para profissionais 40+.
2. Avaliar a percepção de discriminação por idade no mercado.
3. Entender se há defasagem técnica percebida ou real entre profissionais mais velhos.

#### 1. Importações e Configurações

In [1]:
import pandas as pd
import plotly.express as px

#### 2. Carregamento e Leitura Inicial dos Dados

In [2]:
# Dataset original da pesquisa State of Data, foi renomeado para simplificar.
df = pd.read_csv("../data/raw/Dataset_Original.csv")

#### 3. Informações Gerais do DataFrame

In [3]:
# Visializando as primeiras linhas do Dataframe
df.head()

,0.a_token,0.d_data/hora_envio,1.a_idade,1.a.1_faixa_idade,1.b_genero,1.c_cor/raca/etnia,1.d_pcd,1.e_experiencia_profissional_prejudicada,1.e.1_Não acredito que minha experiência profissional seja afetada,"1.e.2_Sim, devido a minha Cor/Raça/Etnia",...,"8.d.3_Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.",8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).,"8.d.5_Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.","8.d.6_Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.","8.d.7_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.","8.d.8_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.","8.d.9_Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.",8.d.10_Criando e gerenciando soluções de Feature Store e cultura de MLOps.,"8.d.11_Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)",8.d.12_Treinando e aplicando LLM's para solucionar problemas de negócio.
0,reb94rv0msth7q4nreb94riaq80iz3yi,16/10/2024 11:19:17,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1zc66g69jjt49y32l1zc66g8wqj79m4e,16/10/2024 20:45:31,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,uu99wmam4n5kc2uu99wmydf0rk7l58f7,17/10/2024 18:10:59,18,17-21,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3ynsw7z0hl5hhpbfvaeqk73ynsw7z04l,22/10/2024 18:03:00,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,v6bji2ct5xckpl1uouv6bjiotkrf3b4f,23/10/2024 01:33:23,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Verificando o número de linhas e colunas.
print(f"Número de linhas: {df.shape[0]}")
print(f"Número de colunas: {df.shape[1]}")

Número de linhas: 5217
Número de colunas: 403

In [5]:
# Exibindo informações sobre o DataFrame, incluindo tipos de dados e valores não nulos.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5217 entries, 0 to 5216
Columns: 403 entries, 0.a_token to 8.d.12_Treinando e aplicando LLM's para solucionar problemas de negócio.
dtypes: bool(1), float64(323), int64(1), object(78)
memory usage: 16.0+ MB

In [6]:
# Substituí df.columns por este comando para melhor visualizar o DataFrame, que tem muitas colunas.
df.columns.to_list()

['0.a_token',
 '0.d_data/hora_envio',
 '1.a_idade',
 '1.a.1_faixa_idade',
 '1.b_genero',
 '1.c_cor/raca/etnia',
 '1.d_pcd',
 '1.e_experiencia_profissional_prejudicada',
 '1.e.1_Não acredito que minha experiência profissional seja afetada',
 '1.e.2_Sim, devido a minha Cor/Raça/Etnia',
 '1.e.3_Sim, devido a minha identidade de gênero',
 '1.e.4_Sim, devido ao fato de ser PCD',
 '1.i.1_uf_onde_mora',
 '1.f.1_Quantidade de oportunidades de emprego/vagas recebidas',
 '1.f.2_Senioridade das vagas recebidas em relação à sua experiência',
 '1.f.3_Aprovação em processos seletivos/entrevistas',
 '1.f.4_Oportunidades de progressão de carreira',
 '1.f.5_Velocidade de progressão de carreira',
 '1.f.6_Nível de cobrança no trabalho/Stress no trabalho',
 '1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias',
 '1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho',
 '1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho',
 '1.i.2_regiao_onde_mora',
 '1.f_aspectos_prejudicados',
 '1.k.1_uf_de_origem',
 '1.k.2_regiao_de_origem',
 '1.g_vive_no_brasil',
 '1.h_pais_onde_mora',
 '1.i_estado_onde_mora',
 '1.j_vive_no_estado_de_formacao',
 '1.k_estado_de_origem',
 '1.l_nivel_de_ensino',
 '1.m_área_de_formação',
 '2.a_situação_de_trabalho',
 '2.b_setor',
 '2.c_numero_de_funcionarios',
 '2.d_atua_como_gestor',
 '2.e_cargo_como_gestor',
 '2.f_cargo_atual',
 '2.g_nivel',
 '2.h_faixa_salarial',
 '2.i_tempo_de_experiencia_em_dados',
 '2.j_tempo_de_experiencia_em_ti',
 '2.k_satisfeito_atualmente',
 '2.l.1_Remuneração/Salário',
 '2.l.2_Benefícios',
 '2.l.3_Propósito do trabalho e da empresa',
 '2.l.4_Flexibilidade de trabalho remoto',
 '2.l.5_Ambiente e clima de trabalho',
 '2.l.6_Oportunidade de aprendizado e trabalhar com referências',
 '2.l.7_Oportunidades de crescimento',
 '2.l.8_Maturidade da empresa em termos de tecnologia e dados',
 '2.l.9_Relação com os gestores e líderes',
 '2.l.10_Reputação que a empresa tem no mercado',
 '2.l.11_Gostaria de trabalhar em outra área',
 '2.l_motivo_insatisfacao',
 '2.m_participou_de_entrevistas_ultimos_6m',
 '2.n_planos_de_mudar_de_emprego_6m',
 '2.o_criterios_para_escolha_de_emprego',
 '2.o.1_Remuneração/Salário',
 '2.o.2_Benefícios',
 '2.o.3_Propósito do trabalho e da empresa',
 '2.o.4_Flexibilidade de trabalho remoto',
 '2.o.5_Ambiente e clima de trabalho',
 '2.o.6_Oportunidade de aprendizado e trabalhar com referências',
 '2.o.7_Plano de carreira e oportunidades de crescimento',
 '2.o.8_Maturidade da empresa em termos de tecnologia e dados',
 '2.o.9_Qualidade dos gestores e líderes',
 '2.o.10_Reputação que a empresa tem no mercado',
 '2.q_empresa_passou_por_layoff_em_2024',
 '2.r_modelo_de_trabalho_atual',
 '2.s_modelo_de_trabalho_ideal',
 '2.t_atitude_em_caso_de_retorno_presencial',
 '3.a_numero_de_pessoas_em_dados',
 '3.b_cargos_no_time_de_dados_da_empresa',
 '3.b.1_Analytics Engineer',
 '3.b.2_Engenharia de Dados/Data Engineer',
 '3.b.3_Analista de Dados/Data Analyst',
 '3.b.4_Cientista de Dados/Data Scientist',
 '3.b.5_Database Administrator/DBA',
 '3.b.6_Analista de Business Intelligence/BI',
 '3.b.7_Arquiteto de Dados/Data Architect',
 '3.b.8_Data Product Manager/DPM',
 '3.b.9_Business Analyst',
 '3.b.10_ML Engineer/AI Engineer',
 '3.c_responsabilidades_como_gestor',
 '3.c.1_Pensar na visão de longo prazo de dados',
 '3.c.2_Organização de treinamentos e iniciativas',
 '3.c.3_Atração, seleção e contratação',
 '3.c.4_Decisão sobre contratação de ferramentas',
 '3.c.5_gestor da equipe de engenharia de dados',
 '3.c.6_gestor da equipe de estudos, relatórios',
 '3.c.7_gestor da equipe de Inteligência Artificial e Machine Learning',
 '3.c.8_Apesar de ser gestor ainda atuo na parte técnica',
 '3.c.9_Gestão de projetos de dados',
 '3.c.10_Gestão de produtos de dados',
 '3.c.11_Gestão de pessoas',
 '3.d_desafios_como_gestor',
 '3.d.1_Contratar talentos',
 '3.d.2_Reter talentos',
 '3.d.3_Convencer a empresa a aumentar investimentos',
 '3.d.4_Gestão de equipes no ambiente remoto',
 '3.d.5_Gestão de projetos envolvendo áreas multidisciplinares',
 '3.d.6_Organizar as informações com qualidade e confiabilidade',
 '3.d.7_Processar e armazenar um alto volume de dados',
 '3.d.8_Gerar valor para as áreas de negócios',
 '3.d.9_Desenvolver e manter modelos Machine Learning em produção',
 '3.d.10_Gerenciar a expectativa das áreas',
 '3.d.11_Garantir a manutenção dos projetos e modelos em produção',
 '3.d.12_Conseguir levar inovação para a empresa',
 '3.d.13_Garantir (ROI) em projetos de dados',
 '3.d.14_Dividir o tempo entre entregas técnicas e gestão',
 '3.e_ai_generativa_e_llm_é_uma_prioridade?',
 '3.f_tipo_de_uso_de_ai_generativa_e_llm_na_empresa',
 '3.f.1 Colaboradores usando AI generativa de forma independente e descentralizada',
 '3.f.2 Direcionamento centralizado do uso de AI generativa',
 '3.f.3 Desenvolvedores utilizando Copilots',
 '3.f.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais',
 '3.f.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores',
 '3.f.6 IA Generativa e LLMs como principal frente do negócio',
 '3.f.7 IA Generativa e LLMs não é prioridade',
 '3.f.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa',
 '3.g_motivos_para_não_usar_ai_generativa_e_llm',
 '3.g.1 Falta de compreensão dos casos de uso',
 '3.g.2 Falta de confiabilidade das saídas (alucinação dos modelos)',
 '3.g.3 Incerteza em relação a regulamentação',
 '3.g.4 Preocupações com segurança e privacidade de dados',
 '3.g.5 Retorno sobre investimento (ROI) não comprovado de IA Generativa',
 '3.g.6 Dados da empresa não estão prontos para uso de IA Generativa',
 '3.g.7 Falta de expertise ou falta de recursos',
 '3.g.8 Alta direção da empresa não vê valor ou não vê como prioridade',
 '3.g.9 Preocupações com propriedade intelectual',
 '4.a_funcao_de_atuacao',
 '4.a.1_atuacao_em_dados',
 '4.b_fontes_de_dados_(dia_a_dia)',
 '4.b.1_Dados relacionais (estruturados em bancos SQL)',
 '4.b.2_Dados armazenados em bancos NoSQL',
 '4.b.3_Imagens',
 '4.b.4_Textos/Documentos',
 '4.b.5_Vídeos',
 '4.b.6_Áudios',
 '4.b.7_Planilhas',
 '4.b.8_Dados georeferenciados',
 '4.c_fonte_de_dado_mais_usada',
 '4.c.1_Dados relacionais (estruturados em bancos SQL)',
 '4.c.2_Dados armazenados em bancos NoSQL',
 '4.c.3_Imagens',
 '4.c.4_Textos/Documentos',
 '4.c.5_Vídeos',
 '4.c.6_Áudios',
 '4.c.7_Planilhas',
 '4.c.8_Dados georeferenciados',
 '4.d_linguagem_de_programacao_(dia_a_dia)',
 '4.d.1_SQL',
 '4.d.2_R',
 '4.d.3_Python',
 '4.d.4_C/C++/C#',
 '4.d.5_.NET',
 '4.d.6_Java',
 '4.d.7_Julia',
 '4.d.8_SAS/Stata',
 '4.d.9_Visual Basic/VBA',
 '4.d.10_Scala',
 '4.d.11_Matlab',
 '4.d.12_Rust',
 '4.d.13_PHP',
 '4.d.14_JavaScript',
 '4.d.15_Não utilizo nenhuma das linguagens listadas',
 '4.e_linguagem_mais_usada',
 '4.f_linguagem_preferida',
 '4.g_banco_de_dados_(dia_a_dia)',
 '4.g.1_MySQL',
 '4.g.2_Oracle',
 '4.g.3_SQL SERVER',
 '4.g.4_Amazon Aurora ou RDS',
 '4.g.5_DynamoDB',
 '4.g.6_CoachDB',
 '4.g.7_Cassandra',
 '4.g.8_MongoDB',
 '4.g.9_MariaDB',
 '4.g.10_Datomic',
 '4.g.11_S3',
 '4.g.12_PostgreSQL',
 '4.g.13_ElasticSearch',
 '4.g.14_DB2',
 '4.g.15_Microsoft Access',
 '4.g.16_SQLite',
 '4.g.17_Sybase',
 '4.g.18_Firebase',
 '4.g.19_Vertica',
 '4.g.20_Redis',
 '4.g.21_Neo4J',
 '4.g.22_Google BigQuery',
 '4.g.23_Google Firestore',
 '4.g.24_Amazon Redshift',
 '4.g.25_Amazon Athena',
 '4.g.26_Snowflake',
 '4.g.27_Databricks',
 '4.g.28_HBase',
 '4.g.29_Presto',
 '4.g.30_Splunk',
 '4.g.31_SAP HANA',
 '4.g.32_Hive',
 '4.g.33_Firebird',
 '4.h_cloud_(dia_a_dia)',
 '4.h.1_Amazon Web Services (AWS)',
 '4.h.2_Google Cloud (GCP)',
 '4.h.3_Azure (Microsoft)',
 '4.h.4_Oracle Cloud',
 '4.h.5_IBM',
 '4.h.6_Servidores On Premise/Não utilizamos Cloud',
 '4.h.7_Cloud Própria',
 '4.i_cloud_preferida',
 '4.j_ferramenta_de_bi_(dia_a_dia)',
 '4.j.1_Microsoft PowerBI',
 '4.j.2_Qlik View/Qlik Sense',
 '4.j.3_Tableau',
 '4.j.4_Metabase',
 '4.j.5_Superset',
 '4.j.6_Redash',
 '4.j.7_Looker',
 '4.j.8_Looker Studio(Google Data Studio)',
 '4.j.9_Amazon Quicksight',
 '4.j.10_Alteryx',
 '4.j.11_SAP Business Objects/SAP Analytics',
 '4.j.12_Oracle Business Intelligence',
 '4.j.13_Salesforce/Einstein Analytics',
 '4.j.14_SAS Visual Analytics',
 '4.j.15_Grafana',
 '4.j.16_Pentaho',
 '4.j.17_Fazemos todas as análises utilizando apenas Excel ou planilhas do google',
 '4.j.18_Não utilizo nenhuma ferramenta de BI no trabalho',
 '4.k_ferramenta_de_bi_preferida',
 '4.l_tipo_de_uso_de_ai_generativa_e_llm_na_empresa',
 '4.l.1 Colaboradores usando AI generativa de forma independente e descentralizada',
 '4.l.2 Direcionamento centralizado do uso de AI generativa',
 '4.l.3 Desenvolvedores utilizando Copilots',
 '4.l.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais',
 '4.l.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores',
 '4.l.6 IA Generativa e LLMs como principal frente do negócio',
 '4.l.7 IA Generativa e LLMs não é prioridade',
 '4.l.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa',
 '4.m_usa_chatgpt_ou_copilot_no_trabalho?',
 '4.m.1 Não uso soluções de AI Generativa com foco em produtividade',
 '4.m.2 Uso soluções gratuitas de AI Generativa com foco em produtividade',
 '4.m.3 Uso e pago pelas soluções de AI Generativa com foco em produtividade',
 '4.m.4 A empresa que trabalho paga pelas soluções de AI Generativa com foco em produtividade',
 '4.m.5 Uso soluções do tipo Copilot',
 '5.a_objetivo_na_area_de_dados',
 '5.b_oportunidade_buscada',
 '5.c_tempo_em_busca_de_oportunidade',
 '5.d_experiencia_em_processos_seletivos',
 '6.a_rotina_como_de',
 '6.a.1_Desenvolvo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.',
 "6.a.2_Realizo construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.",
 '6.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 '6.a.4_Atuo na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.',
 '6.a.5_Modelo soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.',
 '6.a.6_Desenvolvo/cuido da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.',
 '6.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
 '6.a.8_Cuido da qualidade dos dados, metadados e dicionário de dados.',
 '6.a.9_Nenhuma das opções listadas refletem meu dia a dia.',
 '6.b_ferramentas_etl_de',
 '6.b.1_Scripts Python',
 '6.b.2_SQL & Stored Procedures',
 '6.b.3_Apache Airflow',
 '6.b.4_Apache NiFi',
 '6.b.5_Luigi',
 '6.b.6_AWS Glue',
 '6.b.7_Talend',
 '6.b.8_Pentaho',
 '6.b.9_Alteryx',
 '6.b.10_Stitch',
 '6.b.11_Fivetran',
 '6.b.12_Google Dataflow',
 '6.b.13_Oracle Data Integrator',
 '6.b.14_IBM DataStage',
 '6.b.15_SAP BW ETL',
 '6.b.16_SQL Server Integration Services (SSIS)',
 '6.b.17_SAS Data Integration',
 '6.b.18_Qlik Sense',
 '6.b.19_Knime',
 '6.b.20_Databricks',
 '6.b.21_Não utilizo ferramentas de ETL',
 '6.c_possui_data_lake',
 '6.d_tecnologia_data_lake',
 '6.e_possui_data_warehouse',
 '6.f_tecnologia_data_warehouse',
 '6.g_ferramentas_de_qualidade_de_dados_(dia_a_dia)',
 '6.h_maior_tempo_gasto_como_de',
 '6.h.1_Desenvolvendo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.',
 '6.h.2_Realizando construções de ETL\\s em ferramentas como Pentaho, Talend, Dataflow etc.',
 '6.h.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 '6.h.4_Atuando na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.',
 '6.h.5_Modelando soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.',
 '6.h.6_Desenvolvendo/cuidando da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.',
 '6.h.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
 '6.h.8_Cuidando da qualidade dos dados, metadados e dicionário de dados.',
 '6.h.9_Nenhuma das opções listadas refletem meu dia a dia.',
 '7.a_rotina_como_da',
 '7.a.1_Processo e analiso dados utilizando linguagens de programação como Python, R etc.',
 '7.a.2_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.',
 '7.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 '7.a.4_Utilizo API\\s para extrair dados e complementar minhas análises.',
 '7.a.5_Realizo experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.',
 '7.a.6_Desenvolvo/cuido da manutenção de ETL\\s utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.',
 '7.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.',
 '7.a.8_Desenvolvo/cuido da manutenção de planilhas para atender as áreas de negócio.',
 '7.a.9_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.',
 '7.a.10_Nenhuma das opções listadas refletem meu dia a dia.',
 '7.b_ferramentas_etl_da',
 '7.b.1_Scripts Python',
 '7.b.2_SQL & Stored Procedures',
 '7.b.3_Apache Airflow',
 '7.b.4_Apache NiFi',
 '7.b.5_Luigi',
 '7.b.6_AWS Glue',
 '7.b.7_Talend',
 '7.b.8_Pentaho',
 '7.b.9_Alteryx',
 '7.b.10_Stitch',
 '7.b.11_Fivetran',
 '7.b.12_Google Dataflow',
 '7.b.13_Oracle Data Integrator',
 '7.b.14_IBM DataStage',
 '7.b.15_SAP BW ETL',
 '7.b.16_SQL Server Integration Services (SSIS)',
 '7.b.17_SAS Data Integration',
 '7.b.18_Qlik Sense',
 '7.b.19_Knime',
 '7.b.20_Databricks',
 '7.b.21_Não utilizo ferramentas de ETL',
 '7.c_ferramentas_autonomia_area_de_negocios',
 '7.c.1_Ferramentas de AutoML como H2O.ai, Data Robot, BigML etc.',
 '7.c.2_"Point and Click" Analytics como Alteryx, Knime, Rapidminer etc.',
 '7.c.3_Product metricts & Insights como Mixpanel, Amplitude, Adobe Analytics.',
 '7.c.4_Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.',
 '7.c.5_Minha empresa não utiliza essas ferramentas.',
 '7.c.6_Não sei informar.',
 '7.d_maior_tempo_gasto_como_da',
 '7.d.1_Processando e analisando dados utilizando linguagens de programação como Python, R etc.',
 '7.d.2_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.',
 '7.d.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 "7.d.4_Utilizando API's para extrair dados e complementar minhas análises.",
 '7.d.5_Realizando experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.',
 "7.d.6_Desenvolvendo/cuidando da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.",
 '7.d.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
 '7.d.8_Desenvolvendo/cuidando da manutenção de planilhas para atender as áreas de negócio.',
 '7.d.9_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.',
 '7.d.10_Nenhuma das opções listadas refletem meu dia a dia.',
 '8.a_rotina_como_ds',
 '8.a.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.',
 '8.a.2_Sou responsável pela coleta e limpeza dos dados que uso para análise e modelagem.',
 '8.a.3_Sou responsável por entrar em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.',
 '8.a.4_Desenvolvo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).',
 '8.a.5_Sou responsável por colocar modelos em produção, criar os pipelines de dados, APIs de consumo e monitoramento.',
 '8.a.6_Cuido da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.',
 '8.a.7_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc',
 '8.a.8_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.',
 '8.a.9_Crio e dou manutenção em ETLs, DAGs e automações de pipelines de dados.',
 '8.a.10_Crio e gerencio soluções de Feature Store e cultura de MLOps.',
 '8.a.11_Sou responsável por criar e manter a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)',
 "8.a.12_Treino e aplico LLM's para solucionar problemas de negócio.",
 '8.b_tecnicas_e_metodos_ds',
 '8.b.1_Utilizo modelos de regressão (linear, logística, GLM).',
 '8.b.2_Utilizo redes neurais ou modelos baseados em árvore para criar modelos de classificação.',
 '8.b.3_Desenvolvo sistemas de recomendação (RecSys).',
 '8.b.4_Utilizo métodos estatísticos Bayesianos para analisar dados.',
 '8.b.5_Utilizo técnicas de NLP (Natural Language Processing) para análisar dados não-estruturados.',
 '8.b.6_Utilizo métodos estatísticos clássicos (Testes de hipótese, análise multivariada, sobrevivência, dados longitudinais, inferência estatistica) para analisar dados.',
 '8.b.7_Utilizo cadeias de Markov ou HMM\\s para realizar análises de dados.',
 '8.b.8_Desenvolvo técnicas de Clusterização (K-means, Spectral, DBScan etc).',
 '8.b.9_Realizo previsões através de modelos de Séries Temporais (Time Series).',
 '8.b.10_Utilizo modelos de Reinforcement Learning (aprendizado por reforço).',
 '8.b.11_Utilizo modelos de Machine Learning para detecção de fraude.',
 '8.b.12_Utilizo métodos de Visão Computacional.',
 '8.b.13_Utilizo modelos de Detecção de Churn.',
 "8.b.14_Utilizo LLM's para solucionar problemas de negócio.",
 '8.c_tecnologias_ds',
 '8.c.1_Ferramentas de BI (PowerBI, Looker, Tableau, Qlik etc).',
 '8.c.2_Planilhas (Excel, Google Sheets etc).',
 '8.c.3_Ambientes de desenvolvimento local (R-studio, JupyterLab, Anaconda).',
 '8.c.4_Ambientes de desenvolvimento na nuvem (Google Colab, AWS Sagemaker, Kaggle Notebooks etc).',
 '8.c.5_Ferramentas de AutoML (Datarobot, H2O, Auto-Keras etc).',
 '8.c.6_Ferramentas de ETL (Apache Airflow, NiFi, Stitch, Fivetran, Pentaho etc).',
 '8.c.7_Plataformas de Machine Learning (TensorFlow, Azure Machine Learning, Kubeflow etc).',
 '8.c.8_Feature Store (Feast, Hopsworks, AWS Feature Store, Databricks Feature Store etc).',
 '8.c.9_Sistemas de controle de versão (Github, DVC, Neptune, Gitlab etc).',
 '8.c.10_Plataformas de Data Apps (Streamlit, Shiny, Plotly Dash etc).',
 '8.c.11_Ferramentas de estatística avançada como SPSS, SAS, etc.',
 '8.d_maior_tempo_gasto_como_ds',
 '8.d.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.',
 '8.d.2_Coletando e limpando dos dados que uso para análise e modelagem.',
 '8.d.3_Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.',
 '8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).',
 '8.d.5_Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.',
 '8.d.6_Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.',
 '8.d.7_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.',

In [7]:
colunas_secoes = {k: [] for k in range(1, 9)}
colunas_secoes

{1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: []}

In [8]:
# Para cada seção, separar as colunas
for secao in range(1, 9):
    colunas_secoes[secao] = [col for col in df.columns if col.startswith(f"{secao}")]

colunas_secoes

{1: ['1.a_idade',
  '1.a.1_faixa_idade',
  '1.b_genero',
  '1.c_cor/raca/etnia',
  '1.d_pcd',
  '1.e_experiencia_profissional_prejudicada',
  '1.e.1_Não acredito que minha experiência profissional seja afetada',
  '1.e.2_Sim, devido a minha Cor/Raça/Etnia',
  '1.e.3_Sim, devido a minha identidade de gênero',
  '1.e.4_Sim, devido ao fato de ser PCD',
  '1.i.1_uf_onde_mora',
  '1.f.1_Quantidade de oportunidades de emprego/vagas recebidas',
  '1.f.2_Senioridade das vagas recebidas em relação à sua experiência',
  '1.f.3_Aprovação em processos seletivos/entrevistas',
  '1.f.4_Oportunidades de progressão de carreira',
  '1.f.5_Velocidade de progressão de carreira',
  '1.f.6_Nível de cobrança no trabalho/Stress no trabalho',
  '1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias',
  '1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho',
  '1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho',
  '1.i.2_regiao_onde_mora',
  '1.f_aspectos_prejudicados',
  '1.k.1_uf_de_origem',
  '1.k.2_regiao_de_origem',
  '1.g_vive_no_brasil',
  '1.h_pais_onde_mora',
  '1.i_estado_onde_mora',
  '1.j_vive_no_estado_de_formacao',
  '1.k_estado_de_origem',
  '1.l_nivel_de_ensino',
  '1.m_área_de_formação'],
 2: ['2.a_situação_de_trabalho',
  '2.b_setor',
  '2.c_numero_de_funcionarios',
  '2.d_atua_como_gestor',
  '2.e_cargo_como_gestor',
  '2.f_cargo_atual',
  '2.g_nivel',
  '2.h_faixa_salarial',
  '2.i_tempo_de_experiencia_em_dados',
  '2.j_tempo_de_experiencia_em_ti',
  '2.k_satisfeito_atualmente',
  '2.l.1_Remuneração/Salário',
  '2.l.2_Benefícios',
  '2.l.3_Propósito do trabalho e da empresa',
  '2.l.4_Flexibilidade de trabalho remoto',
  '2.l.5_Ambiente e clima de trabalho',
  '2.l.6_Oportunidade de aprendizado e trabalhar com referências',
  '2.l.7_Oportunidades de crescimento',
  '2.l.8_Maturidade da empresa em termos de tecnologia e dados',
  '2.l.9_Relação com os gestores e líderes',
  '2.l.10_Reputação que a empresa tem no mercado',
  '2.l.11_Gostaria de trabalhar em outra área',
  '2.l_motivo_insatisfacao',
  '2.m_participou_de_entrevistas_ultimos_6m',
  '2.n_planos_de_mudar_de_emprego_6m',
  '2.o_criterios_para_escolha_de_emprego',
  '2.o.1_Remuneração/Salário',
  '2.o.2_Benefícios',
  '2.o.3_Propósito do trabalho e da empresa',
  '2.o.4_Flexibilidade de trabalho remoto',
  '2.o.5_Ambiente e clima de trabalho',
  '2.o.6_Oportunidade de aprendizado e trabalhar com referências',
  '2.o.7_Plano de carreira e oportunidades de crescimento',
  '2.o.8_Maturidade da empresa em termos de tecnologia e dados',
  '2.o.9_Qualidade dos gestores e líderes',
  '2.o.10_Reputação que a empresa tem no mercado',
  '2.q_empresa_passou_por_layoff_em_2024',
  '2.r_modelo_de_trabalho_atual',
  '2.s_modelo_de_trabalho_ideal',
  '2.t_atitude_em_caso_de_retorno_presencial'],
 3: ['3.a_numero_de_pessoas_em_dados',
  '3.b_cargos_no_time_de_dados_da_empresa',
  '3.b.1_Analytics Engineer',
  '3.b.2_Engenharia de Dados/Data Engineer',
  '3.b.3_Analista de Dados/Data Analyst',
  '3.b.4_Cientista de Dados/Data Scientist',
  '3.b.5_Database Administrator/DBA',
  '3.b.6_Analista de Business Intelligence/BI',
  '3.b.7_Arquiteto de Dados/Data Architect',
  '3.b.8_Data Product Manager/DPM',
  '3.b.9_Business Analyst',
  '3.b.10_ML Engineer/AI Engineer',
  '3.c_responsabilidades_como_gestor',
  '3.c.1_Pensar na visão de longo prazo de dados',
  '3.c.2_Organização de treinamentos e iniciativas',
  '3.c.3_Atração, seleção e contratação',
  '3.c.4_Decisão sobre contratação de ferramentas',
  '3.c.5_gestor da equipe de engenharia de dados',
  '3.c.6_gestor da equipe de estudos, relatórios',
  '3.c.7_gestor da equipe de Inteligência Artificial e Machine Learning',
  '3.c.8_Apesar de ser gestor ainda atuo na parte técnica',
  '3.c.9_Gestão de projetos de dados',
  '3.c.10_Gestão de produtos de dados',
  '3.c.11_Gestão de pessoas',
  '3.d_desafios_como_gestor',
  '3.d.1_Contratar talentos',
  '3.d.2_Reter talentos',
  '3.d.3_Convencer a empresa a aumentar investimentos',
  '3.d.4_Gestão de equipes no ambiente remoto',
  '3.d.5_Gestão de projetos envolvendo áreas multidisciplinares',
  '3.d.6_Organizar as informações com qualidade e confiabilidade',
  '3.d.7_Processar e armazenar um alto volume de dados',
  '3.d.8_Gerar valor para as áreas de negócios',
  '3.d.9_Desenvolver e manter modelos Machine Learning em produção',
  '3.d.10_Gerenciar a expectativa das áreas',
  '3.d.11_Garantir a manutenção dos projetos e modelos em produção',
  '3.d.12_Conseguir levar inovação para a empresa',
  '3.d.13_Garantir (ROI) em projetos de dados',
  '3.d.14_Dividir o tempo entre entregas técnicas e gestão',
  '3.e_ai_generativa_e_llm_é_uma_prioridade?',
  '3.f_tipo_de_uso_de_ai_generativa_e_llm_na_empresa',
  '3.f.1 Colaboradores usando AI generativa de forma independente e descentralizada',
  '3.f.2 Direcionamento centralizado do uso de AI generativa',
  '3.f.3 Desenvolvedores utilizando Copilots',
  '3.f.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais',
  '3.f.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores',
  '3.f.6 IA Generativa e LLMs como principal frente do negócio',
  '3.f.7 IA Generativa e LLMs não é prioridade',
  '3.f.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa',
  '3.g_motivos_para_não_usar_ai_generativa_e_llm',
  '3.g.1 Falta de compreensão dos casos de uso',
  '3.g.2 Falta de confiabilidade das saídas (alucinação dos modelos)',
  '3.g.3 Incerteza em relação a regulamentação',
  '3.g.4 Preocupações com segurança e privacidade de dados',
  '3.g.5 Retorno sobre investimento (ROI) não comprovado de IA Generativa',
  '3.g.6 Dados da empresa não estão prontos para uso de IA Generativa',
  '3.g.7 Falta de expertise ou falta de recursos',
  '3.g.8 Alta direção da empresa não vê valor ou não vê como prioridade',
  '3.g.9 Preocupações com propriedade intelectual'],
 4: ['4.a_funcao_de_atuacao',
  '4.a.1_atuacao_em_dados',
  '4.b_fontes_de_dados_(dia_a_dia)',
  '4.b.1_Dados relacionais (estruturados em bancos SQL)',
  '4.b.2_Dados armazenados em bancos NoSQL',
  '4.b.3_Imagens',
  '4.b.4_Textos/Documentos',
  '4.b.5_Vídeos',
  '4.b.6_Áudios',
  '4.b.7_Planilhas',
  '4.b.8_Dados georeferenciados',
  '4.c_fonte_de_dado_mais_usada',
  '4.c.1_Dados relacionais (estruturados em bancos SQL)',
  '4.c.2_Dados armazenados em bancos NoSQL',
  '4.c.3_Imagens',
  '4.c.4_Textos/Documentos',
  '4.c.5_Vídeos',
  '4.c.6_Áudios',
  '4.c.7_Planilhas',
  '4.c.8_Dados georeferenciados',
  '4.d_linguagem_de_programacao_(dia_a_dia)',
  '4.d.1_SQL',
  '4.d.2_R',
  '4.d.3_Python',
  '4.d.4_C/C++/C#',
  '4.d.5_.NET',
  '4.d.6_Java',
  '4.d.7_Julia',
  '4.d.8_SAS/Stata',
  '4.d.9_Visual Basic/VBA',
  '4.d.10_Scala',
  '4.d.11_Matlab',
  '4.d.12_Rust',
  '4.d.13_PHP',
  '4.d.14_JavaScript',
  '4.d.15_Não utilizo nenhuma das linguagens listadas',
  '4.e_linguagem_mais_usada',
  '4.f_linguagem_preferida',
  '4.g_banco_de_dados_(dia_a_dia)',
  '4.g.1_MySQL',
  '4.g.2_Oracle',
  '4.g.3_SQL SERVER',
  '4.g.4_Amazon Aurora ou RDS',
  '4.g.5_DynamoDB',
  '4.g.6_CoachDB',
  '4.g.7_Cassandra',
  '4.g.8_MongoDB',
  '4.g.9_MariaDB',
  '4.g.10_Datomic',
  '4.g.11_S3',
  '4.g.12_PostgreSQL',
  '4.g.13_ElasticSearch',
  '4.g.14_DB2',
  '4.g.15_Microsoft Access',
  '4.g.16_SQLite',
  '4.g.17_Sybase',
  '4.g.18_Firebase',
  '4.g.19_Vertica',
  '4.g.20_Redis',
  '4.g.21_Neo4J',
  '4.g.22_Google BigQuery',
  '4.g.23_Google Firestore',
  '4.g.24_Amazon Redshift',
  '4.g.25_Amazon Athena',
  '4.g.26_Snowflake',
  '4.g.27_Databricks',
  '4.g.28_HBase',
  '4.g.29_Presto',
  '4.g.30_Splunk',
  '4.g.31_SAP HANA',
  '4.g.32_Hive',
  '4.g.33_Firebird',
  '4.h_cloud_(dia_a_dia)',
  '4.h.1_Amazon Web Services (AWS)',
  '4.h.2_Google Cloud (GCP)',
  '4.h.3_Azure (Microsoft)',
  '4.h.4_Oracle Cloud',
  '4.h.5_IBM',
  '4.h.6_Servidores On Premise/Não utilizamos Cloud',
  '4.h.7_Cloud Própria',
  '4.i_cloud_preferida',
  '4.j_ferramenta_de_bi_(dia_a_dia)',
  '4.j.1_Microsoft PowerBI',
  '4.j.2_Qlik View/Qlik Sense',
  '4.j.3_Tableau',
  '4.j.4_Metabase',
  '4.j.5_Superset',
  '4.j.6_Redash',
  '4.j.7_Looker',
  '4.j.8_Looker Studio(Google Data Studio)',
  '4.j.9_Amazon Quicksight',
  '4.j.10_Alteryx',
  '4.j.11_SAP Business Objects/SAP Analytics',
  '4.j.12_Oracle Business Intelligence',
  '4.j.13_Salesforce/Einstein Analytics',
  '4.j.14_SAS Visual Analytics',
  '4.j.15_Grafana',
  '4.j.16_Pentaho',
  '4.j.17_Fazemos todas as análises utilizando apenas Excel ou planilhas do google',
  '4.j.18_Não utilizo nenhuma ferramenta de BI no trabalho',
  '4.k_ferramenta_de_bi_preferida',
  '4.l_tipo_de_uso_de_ai_generativa_e_llm_na_empresa',
  '4.l.1 Colaboradores usando AI generativa de forma independente e descentralizada',
  '4.l.2 Direcionamento centralizado do uso de AI generativa',
  '4.l.3 Desenvolvedores utilizando Copilots',
  '4.l.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais',
  '4.l.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores',
  '4.l.6 IA Generativa e LLMs como principal frente do negócio',
  '4.l.7 IA Generativa e LLMs não é prioridade',
  '4.l.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa',
  '4.m_usa_chatgpt_ou_copilot_no_trabalho?',
  '4.m.1 Não uso soluções de AI Generativa com foco em produtividade',
  '4.m.2 Uso soluções gratuitas de AI Generativa com foco em produtividade',
  '4.m.3 Uso e pago pelas soluções de AI Generativa com foco em produtividade',
  '4.m.4 A empresa que trabalho paga pelas soluções de AI Generativa com foco em produtividade',
  '4.m.5 Uso soluções do tipo Copilot'],
 5: ['5.a_objetivo_na_area_de_dados',
  '5.b_oportunidade_buscada',
  '5.c_tempo_em_busca_de_oportunidade',
  '5.d_experiencia_em_processos_seletivos'],
 6: ['6.a_rotina_como_de',
  '6.a.1_Desenvolvo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.',
  "6.a.2_Realizo construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.",
  '6.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
  '6.a.4_Atuo na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.',
  '6.a.5_Modelo soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.',
  '6.a.6_Desenvolvo/cuido da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.',
  '6.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
  '6.a.8_Cuido da qualidade dos dados, metadados e dicionário de dados.',
  '6.a.9_Nenhuma das opções listadas refletem meu dia a dia.',
  '6.b_ferramentas_etl_de',
  '6.b.1_Scripts Python',
  '6.b.2_SQL & Stored Procedures',
  '6.b.3_Apache Airflow',
  '6.b.4_Apache NiFi',
  '6.b.5_Luigi',
  '6.b.6_AWS Glue',
  '6.b.7_Talend',
  '6.b.8_Pentaho',
  '6.b.9_Alteryx',
  '6.b.10_Stitch',
  '6.b.11_Fivetran',
  '6.b.12_Google Dataflow',
  '6.b.13_Oracle Data Integrator',
  '6.b.14_IBM DataStage',
  '6.b.15_SAP BW ETL',
  '6.b.16_SQL Server Integration Services (SSIS)',
  '6.b.17_SAS Data Integration',
  '6.b.18_Qlik Sense',
  '6.b.19_Knime',
  '6.b.20_Databricks',
  '6.b.21_Não utilizo ferramentas de ETL',
  '6.c_possui_data_lake',
  '6.d_tecnologia_data_lake',
  '6.e_possui_data_warehouse',
  '6.f_tecnologia_data_warehouse',
  '6.g_ferramentas_de_qualidade_de_dados_(dia_a_dia)',
  '6.h_maior_tempo_gasto_como_de',
  '6.h.1_Desenvolvendo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.',
  '6.h.2_Realizando construções de ETL\\s em ferramentas como Pentaho, Talend, Dataflow etc.',
  '6.h.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
  '6.h.4_Atuando na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.',
  '6.h.5_Modelando soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.',
  '6.h.6_Desenvolvendo/cuidando da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.',
  '6.h.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
  '6.h.8_Cuidando da qualidade dos dados, metadados e dicionário de dados.',
  '6.h.9_Nenhuma das opções listadas refletem meu dia a dia.'],
 7: ['7.a_rotina_como_da',
  '7.a.1_Processo e analiso dados utilizando linguagens de programação como Python, R etc.',
  '7.a.2_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.',
  '7.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
  '7.a.4_Utilizo API\\s para extrair dados e complementar minhas análises.',
  '7.a.5_Realizo experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.',
  '7.a.6_Desenvolvo/cuido da manutenção de ETL\\s utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.',
  '7.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.',
  '7.a.8_Desenvolvo/cuido da manutenção de planilhas para atender as áreas de negócio.',
  '7.a.9_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.',
  '7.a.10_Nenhuma das opções listadas refletem meu dia a dia.',
  '7.b_ferramentas_etl_da',
  '7.b.1_Scripts Python',
  '7.b.2_SQL & Stored Procedures',
  '7.b.3_Apache Airflow',
  '7.b.4_Apache NiFi',
  '7.b.5_Luigi',
  '7.b.6_AWS Glue',
  '7.b.7_Talend',
  '7.b.8_Pentaho',
  '7.b.9_Alteryx',
  '7.b.10_Stitch',
  '7.b.11_Fivetran',
  '7.b.12_Google Dataflow',
  '7.b.13_Oracle Data Integrator',
  '7.b.14_IBM DataStage',
  '7.b.15_SAP BW ETL',
  '7.b.16_SQL Server Integration Services (SSIS)',
  '7.b.17_SAS Data Integration',
  '7.b.18_Qlik Sense',
  '7.b.19_Knime',
  '7.b.20_Databricks',
  '7.b.21_Não utilizo ferramentas de ETL',
  '7.c_ferramentas_autonomia_area_de_negocios',
  '7.c.1_Ferramentas de AutoML como H2O.ai, Data Robot, BigML etc.',
  '7.c.2_"Point and Click" Analytics como Alteryx, Knime, Rapidminer etc.',
  '7.c.3_Product metricts & Insights como Mixpanel, Amplitude, Adobe Analytics.',
  '7.c.4_Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.',
  '7.c.5_Minha empresa não utiliza essas ferramentas.',
  '7.c.6_Não sei informar.',
  '7.d_maior_tempo_gasto_como_da',
  '7.d.1_Processando e analisando dados utilizando linguagens de programação como Python, R etc.',
  '7.d.2_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.',
  '7.d.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
  "7.d.4_Utilizando API's para extrair dados e complementar minhas análises.",
  '7.d.5_Realizando experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.',
  "7.d.6_Desenvolvendo/cuidando da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.",
  '7.d.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
  '7.d.8_Desenvolvendo/cuidando da manutenção de planilhas para atender as áreas de negócio.',
  '7.d.9_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.',
  '7.d.10_Nenhuma das opções listadas refletem meu dia a dia.'],
 8: ['8.a_rotina_como_ds',
  '8.a.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.',
  '8.a.2_Sou responsável pela coleta e limpeza dos dados que uso para análise e modelagem.',
  '8.a.3_Sou responsável por entrar em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.',
  '8.a.4_Desenvolvo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).',
  '8.a.5_Sou responsável por colocar modelos em produção, criar os pipelines de dados, APIs de consumo e monitoramento.',
  '8.a.6_Cuido da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.',
  '8.a.7_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc',
  '8.a.8_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.',
  '8.a.9_Crio e dou manutenção em ETLs, DAGs e automações de pipelines de dados.',
  '8.a.10_Crio e gerencio soluções de Feature Store e cultura de MLOps.',
  '8.a.11_Sou responsável por criar e manter a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)',
  "8.a.12_Treino e aplico LLM's para solucionar problemas de negócio.",
  '8.b_tecnicas_e_metodos_ds',
  '8.b.1_Utilizo modelos de regressão (linear, logística, GLM).',
  '8.b.2_Utilizo redes neurais ou modelos baseados em árvore para criar modelos de classificação.',
  '8.b.3_Desenvolvo sistemas de recomendação (RecSys).',
  '8.b.4_Utilizo métodos estatísticos Bayesianos para analisar dados.',
  '8.b.5_Utilizo técnicas de NLP (Natural Language Processing) para análisar dados não-estruturados.',
  '8.b.6_Utilizo métodos estatísticos clássicos (Testes de hipótese, análise multivariada, sobrevivência, dados longitudinais, inferência estatistica) para analisar dados.',
  '8.b.7_Utilizo cadeias de Markov ou HMM\\s para realizar análises de dados.',
  '8.b.8_Desenvolvo técnicas de Clusterização (K-means, Spectral, DBScan etc).',
  '8.b.9_Realizo previsões através de modelos de Séries Temporais (Time Series).',
  '8.b.10_Utilizo modelos de Reinforcement Learning (aprendizado por reforço).',
  '8.b.11_Utilizo modelos de Machine Learning para detecção de fraude.',
  '8.b.12_Utilizo métodos de Visão Computacional.',
  '8.b.13_Utilizo modelos de Detecção de Churn.',
  "8.b.14_Utilizo LLM's para solucionar problemas de negócio.",
  '8.c_tecnologias_ds',
  '8.c.1_Ferramentas de BI (PowerBI, Looker, Tableau, Qlik etc).',
  '8.c.2_Planilhas (Excel, Google Sheets etc).',
  '8.c.3_Ambientes de desenvolvimento local (R-studio, JupyterLab, Anaconda).',
  '8.c.4_Ambientes de desenvolvimento na nuvem (Google Colab, AWS Sagemaker, Kaggle Notebooks etc).',
  '8.c.5_Ferramentas de AutoML (Datarobot, H2O, Auto-Keras etc).',
  '8.c.6_Ferramentas de ETL (Apache Airflow, NiFi, Stitch, Fivetran, Pentaho etc).',
  '8.c.7_Plataformas de Machine Learning (TensorFlow, Azure Machine Learning, Kubeflow etc).',
  '8.c.8_Feature Store (Feast, Hopsworks, AWS Feature Store, Databricks Feature Store etc).',
  '8.c.9_Sistemas de controle de versão (Github, DVC, Neptune, Gitlab etc).',
  '8.c.10_Plataformas de Data Apps (Streamlit, Shiny, Plotly Dash etc).',
  '8.c.11_Ferramentas de estatística avançada como SPSS, SAS, etc.',
  '8.d_maior_tempo_gasto_como_ds',
  '8.d.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.',
  '8.d.2_Coletando e limpando dos dados que uso para análise e modelagem.',
  '8.d.3_Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.',
  '8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).',

In [9]:
# Verificando se ficou alguma coluna de fora
todas_colunas_secoes = [item for sublist in colunas_secoes.values() for item in sublist]
todas_colunas_secoes

['1.a_idade',
 '1.a.1_faixa_idade',
 '1.b_genero',
 '1.c_cor/raca/etnia',
 '1.d_pcd',
 '1.e_experiencia_profissional_prejudicada',
 '1.e.1_Não acredito que minha experiência profissional seja afetada',
 '1.e.2_Sim, devido a minha Cor/Raça/Etnia',
 '1.e.3_Sim, devido a minha identidade de gênero',
 '1.e.4_Sim, devido ao fato de ser PCD',
 '1.i.1_uf_onde_mora',
 '1.f.1_Quantidade de oportunidades de emprego/vagas recebidas',
 '1.f.2_Senioridade das vagas recebidas em relação à sua experiência',
 '1.f.3_Aprovação em processos seletivos/entrevistas',
 '1.f.4_Oportunidades de progressão de carreira',
 '1.f.5_Velocidade de progressão de carreira',
 '1.f.6_Nível de cobrança no trabalho/Stress no trabalho',
 '1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias',
 '1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho',
 '1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho',
 '1.i.2_regiao_onde_mora',
 '1.f_aspectos_prejudicados',
 '1.k.1_uf_de_origem',
 '1.k.2_regiao_de_origem',
 '1.g_vive_no_brasil',
 '1.h_pais_onde_mora',
 '1.i_estado_onde_mora',
 '1.j_vive_no_estado_de_formacao',
 '1.k_estado_de_origem',
 '1.l_nivel_de_ensino',
 '1.m_área_de_formação',
 '2.a_situação_de_trabalho',
 '2.b_setor',
 '2.c_numero_de_funcionarios',
 '2.d_atua_como_gestor',
 '2.e_cargo_como_gestor',
 '2.f_cargo_atual',
 '2.g_nivel',
 '2.h_faixa_salarial',
 '2.i_tempo_de_experiencia_em_dados',
 '2.j_tempo_de_experiencia_em_ti',
 '2.k_satisfeito_atualmente',
 '2.l.1_Remuneração/Salário',
 '2.l.2_Benefícios',
 '2.l.3_Propósito do trabalho e da empresa',
 '2.l.4_Flexibilidade de trabalho remoto',
 '2.l.5_Ambiente e clima de trabalho',
 '2.l.6_Oportunidade de aprendizado e trabalhar com referências',
 '2.l.7_Oportunidades de crescimento',
 '2.l.8_Maturidade da empresa em termos de tecnologia e dados',
 '2.l.9_Relação com os gestores e líderes',
 '2.l.10_Reputação que a empresa tem no mercado',
 '2.l.11_Gostaria de trabalhar em outra área',
 '2.l_motivo_insatisfacao',
 '2.m_participou_de_entrevistas_ultimos_6m',
 '2.n_planos_de_mudar_de_emprego_6m',
 '2.o_criterios_para_escolha_de_emprego',
 '2.o.1_Remuneração/Salário',
 '2.o.2_Benefícios',
 '2.o.3_Propósito do trabalho e da empresa',
 '2.o.4_Flexibilidade de trabalho remoto',
 '2.o.5_Ambiente e clima de trabalho',
 '2.o.6_Oportunidade de aprendizado e trabalhar com referências',
 '2.o.7_Plano de carreira e oportunidades de crescimento',
 '2.o.8_Maturidade da empresa em termos de tecnologia e dados',
 '2.o.9_Qualidade dos gestores e líderes',
 '2.o.10_Reputação que a empresa tem no mercado',
 '2.q_empresa_passou_por_layoff_em_2024',
 '2.r_modelo_de_trabalho_atual',
 '2.s_modelo_de_trabalho_ideal',
 '2.t_atitude_em_caso_de_retorno_presencial',
 '3.a_numero_de_pessoas_em_dados',
 '3.b_cargos_no_time_de_dados_da_empresa',
 '3.b.1_Analytics Engineer',
 '3.b.2_Engenharia de Dados/Data Engineer',
 '3.b.3_Analista de Dados/Data Analyst',
 '3.b.4_Cientista de Dados/Data Scientist',
 '3.b.5_Database Administrator/DBA',
 '3.b.6_Analista de Business Intelligence/BI',
 '3.b.7_Arquiteto de Dados/Data Architect',
 '3.b.8_Data Product Manager/DPM',
 '3.b.9_Business Analyst',
 '3.b.10_ML Engineer/AI Engineer',
 '3.c_responsabilidades_como_gestor',
 '3.c.1_Pensar na visão de longo prazo de dados',
 '3.c.2_Organização de treinamentos e iniciativas',
 '3.c.3_Atração, seleção e contratação',
 '3.c.4_Decisão sobre contratação de ferramentas',
 '3.c.5_gestor da equipe de engenharia de dados',
 '3.c.6_gestor da equipe de estudos, relatórios',
 '3.c.7_gestor da equipe de Inteligência Artificial e Machine Learning',
 '3.c.8_Apesar de ser gestor ainda atuo na parte técnica',
 '3.c.9_Gestão de projetos de dados',
 '3.c.10_Gestão de produtos de dados',
 '3.c.11_Gestão de pessoas',
 '3.d_desafios_como_gestor',
 '3.d.1_Contratar talentos',
 '3.d.2_Reter talentos',
 '3.d.3_Convencer a empresa a aumentar investimentos',
 '3.d.4_Gestão de equipes no ambiente remoto',
 '3.d.5_Gestão de projetos envolvendo áreas multidisciplinares',
 '3.d.6_Organizar as informações com qualidade e confiabilidade',
 '3.d.7_Processar e armazenar um alto volume de dados',
 '3.d.8_Gerar valor para as áreas de negócios',
 '3.d.9_Desenvolver e manter modelos Machine Learning em produção',
 '3.d.10_Gerenciar a expectativa das áreas',
 '3.d.11_Garantir a manutenção dos projetos e modelos em produção',
 '3.d.12_Conseguir levar inovação para a empresa',
 '3.d.13_Garantir (ROI) em projetos de dados',
 '3.d.14_Dividir o tempo entre entregas técnicas e gestão',
 '3.e_ai_generativa_e_llm_é_uma_prioridade?',
 '3.f_tipo_de_uso_de_ai_generativa_e_llm_na_empresa',
 '3.f.1 Colaboradores usando AI generativa de forma independente e descentralizada',
 '3.f.2 Direcionamento centralizado do uso de AI generativa',
 '3.f.3 Desenvolvedores utilizando Copilots',
 '3.f.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais',
 '3.f.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores',
 '3.f.6 IA Generativa e LLMs como principal frente do negócio',
 '3.f.7 IA Generativa e LLMs não é prioridade',
 '3.f.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa',
 '3.g_motivos_para_não_usar_ai_generativa_e_llm',
 '3.g.1 Falta de compreensão dos casos de uso',
 '3.g.2 Falta de confiabilidade das saídas (alucinação dos modelos)',
 '3.g.3 Incerteza em relação a regulamentação',
 '3.g.4 Preocupações com segurança e privacidade de dados',
 '3.g.5 Retorno sobre investimento (ROI) não comprovado de IA Generativa',
 '3.g.6 Dados da empresa não estão prontos para uso de IA Generativa',
 '3.g.7 Falta de expertise ou falta de recursos',
 '3.g.8 Alta direção da empresa não vê valor ou não vê como prioridade',
 '3.g.9 Preocupações com propriedade intelectual',
 '4.a_funcao_de_atuacao',
 '4.a.1_atuacao_em_dados',
 '4.b_fontes_de_dados_(dia_a_dia)',
 '4.b.1_Dados relacionais (estruturados em bancos SQL)',
 '4.b.2_Dados armazenados em bancos NoSQL',
 '4.b.3_Imagens',
 '4.b.4_Textos/Documentos',
 '4.b.5_Vídeos',
 '4.b.6_Áudios',
 '4.b.7_Planilhas',
 '4.b.8_Dados georeferenciados',
 '4.c_fonte_de_dado_mais_usada',
 '4.c.1_Dados relacionais (estruturados em bancos SQL)',
 '4.c.2_Dados armazenados em bancos NoSQL',
 '4.c.3_Imagens',
 '4.c.4_Textos/Documentos',
 '4.c.5_Vídeos',
 '4.c.6_Áudios',
 '4.c.7_Planilhas',
 '4.c.8_Dados georeferenciados',
 '4.d_linguagem_de_programacao_(dia_a_dia)',
 '4.d.1_SQL',
 '4.d.2_R',
 '4.d.3_Python',
 '4.d.4_C/C++/C#',
 '4.d.5_.NET',
 '4.d.6_Java',
 '4.d.7_Julia',
 '4.d.8_SAS/Stata',
 '4.d.9_Visual Basic/VBA',
 '4.d.10_Scala',
 '4.d.11_Matlab',
 '4.d.12_Rust',
 '4.d.13_PHP',
 '4.d.14_JavaScript',
 '4.d.15_Não utilizo nenhuma das linguagens listadas',
 '4.e_linguagem_mais_usada',
 '4.f_linguagem_preferida',
 '4.g_banco_de_dados_(dia_a_dia)',
 '4.g.1_MySQL',
 '4.g.2_Oracle',
 '4.g.3_SQL SERVER',
 '4.g.4_Amazon Aurora ou RDS',
 '4.g.5_DynamoDB',
 '4.g.6_CoachDB',
 '4.g.7_Cassandra',
 '4.g.8_MongoDB',
 '4.g.9_MariaDB',
 '4.g.10_Datomic',
 '4.g.11_S3',
 '4.g.12_PostgreSQL',
 '4.g.13_ElasticSearch',
 '4.g.14_DB2',
 '4.g.15_Microsoft Access',
 '4.g.16_SQLite',
 '4.g.17_Sybase',
 '4.g.18_Firebase',
 '4.g.19_Vertica',
 '4.g.20_Redis',
 '4.g.21_Neo4J',
 '4.g.22_Google BigQuery',
 '4.g.23_Google Firestore',
 '4.g.24_Amazon Redshift',
 '4.g.25_Amazon Athena',
 '4.g.26_Snowflake',
 '4.g.27_Databricks',
 '4.g.28_HBase',
 '4.g.29_Presto',
 '4.g.30_Splunk',
 '4.g.31_SAP HANA',
 '4.g.32_Hive',
 '4.g.33_Firebird',
 '4.h_cloud_(dia_a_dia)',
 '4.h.1_Amazon Web Services (AWS)',
 '4.h.2_Google Cloud (GCP)',
 '4.h.3_Azure (Microsoft)',
 '4.h.4_Oracle Cloud',
 '4.h.5_IBM',
 '4.h.6_Servidores On Premise/Não utilizamos Cloud',
 '4.h.7_Cloud Própria',
 '4.i_cloud_preferida',
 '4.j_ferramenta_de_bi_(dia_a_dia)',
 '4.j.1_Microsoft PowerBI',
 '4.j.2_Qlik View/Qlik Sense',
 '4.j.3_Tableau',
 '4.j.4_Metabase',
 '4.j.5_Superset',
 '4.j.6_Redash',
 '4.j.7_Looker',
 '4.j.8_Looker Studio(Google Data Studio)',
 '4.j.9_Amazon Quicksight',
 '4.j.10_Alteryx',
 '4.j.11_SAP Business Objects/SAP Analytics',
 '4.j.12_Oracle Business Intelligence',
 '4.j.13_Salesforce/Einstein Analytics',
 '4.j.14_SAS Visual Analytics',
 '4.j.15_Grafana',
 '4.j.16_Pentaho',
 '4.j.17_Fazemos todas as análises utilizando apenas Excel ou planilhas do google',
 '4.j.18_Não utilizo nenhuma ferramenta de BI no trabalho',
 '4.k_ferramenta_de_bi_preferida',
 '4.l_tipo_de_uso_de_ai_generativa_e_llm_na_empresa',
 '4.l.1 Colaboradores usando AI generativa de forma independente e descentralizada',
 '4.l.2 Direcionamento centralizado do uso de AI generativa',
 '4.l.3 Desenvolvedores utilizando Copilots',
 '4.l.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais',
 '4.l.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores',
 '4.l.6 IA Generativa e LLMs como principal frente do negócio',
 '4.l.7 IA Generativa e LLMs não é prioridade',
 '4.l.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa',
 '4.m_usa_chatgpt_ou_copilot_no_trabalho?',
 '4.m.1 Não uso soluções de AI Generativa com foco em produtividade',
 '4.m.2 Uso soluções gratuitas de AI Generativa com foco em produtividade',
 '4.m.3 Uso e pago pelas soluções de AI Generativa com foco em produtividade',
 '4.m.4 A empresa que trabalho paga pelas soluções de AI Generativa com foco em produtividade',
 '4.m.5 Uso soluções do tipo Copilot',
 '5.a_objetivo_na_area_de_dados',
 '5.b_oportunidade_buscada',
 '5.c_tempo_em_busca_de_oportunidade',
 '5.d_experiencia_em_processos_seletivos',
 '6.a_rotina_como_de',
 '6.a.1_Desenvolvo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.',
 "6.a.2_Realizo construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.",
 '6.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 '6.a.4_Atuo na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.',
 '6.a.5_Modelo soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.',
 '6.a.6_Desenvolvo/cuido da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.',
 '6.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
 '6.a.8_Cuido da qualidade dos dados, metadados e dicionário de dados.',
 '6.a.9_Nenhuma das opções listadas refletem meu dia a dia.',
 '6.b_ferramentas_etl_de',
 '6.b.1_Scripts Python',
 '6.b.2_SQL & Stored Procedures',
 '6.b.3_Apache Airflow',
 '6.b.4_Apache NiFi',
 '6.b.5_Luigi',
 '6.b.6_AWS Glue',
 '6.b.7_Talend',
 '6.b.8_Pentaho',
 '6.b.9_Alteryx',
 '6.b.10_Stitch',
 '6.b.11_Fivetran',
 '6.b.12_Google Dataflow',
 '6.b.13_Oracle Data Integrator',
 '6.b.14_IBM DataStage',
 '6.b.15_SAP BW ETL',
 '6.b.16_SQL Server Integration Services (SSIS)',
 '6.b.17_SAS Data Integration',
 '6.b.18_Qlik Sense',
 '6.b.19_Knime',
 '6.b.20_Databricks',
 '6.b.21_Não utilizo ferramentas de ETL',
 '6.c_possui_data_lake',
 '6.d_tecnologia_data_lake',
 '6.e_possui_data_warehouse',
 '6.f_tecnologia_data_warehouse',
 '6.g_ferramentas_de_qualidade_de_dados_(dia_a_dia)',
 '6.h_maior_tempo_gasto_como_de',
 '6.h.1_Desenvolvendo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.',
 '6.h.2_Realizando construções de ETL\\s em ferramentas como Pentaho, Talend, Dataflow etc.',
 '6.h.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 '6.h.4_Atuando na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.',
 '6.h.5_Modelando soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.',
 '6.h.6_Desenvolvendo/cuidando da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.',
 '6.h.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
 '6.h.8_Cuidando da qualidade dos dados, metadados e dicionário de dados.',
 '6.h.9_Nenhuma das opções listadas refletem meu dia a dia.',
 '7.a_rotina_como_da',
 '7.a.1_Processo e analiso dados utilizando linguagens de programação como Python, R etc.',
 '7.a.2_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.',
 '7.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 '7.a.4_Utilizo API\\s para extrair dados e complementar minhas análises.',
 '7.a.5_Realizo experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.',
 '7.a.6_Desenvolvo/cuido da manutenção de ETL\\s utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.',
 '7.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.',
 '7.a.8_Desenvolvo/cuido da manutenção de planilhas para atender as áreas de negócio.',
 '7.a.9_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.',
 '7.a.10_Nenhuma das opções listadas refletem meu dia a dia.',
 '7.b_ferramentas_etl_da',
 '7.b.1_Scripts Python',
 '7.b.2_SQL & Stored Procedures',
 '7.b.3_Apache Airflow',
 '7.b.4_Apache NiFi',
 '7.b.5_Luigi',
 '7.b.6_AWS Glue',
 '7.b.7_Talend',
 '7.b.8_Pentaho',
 '7.b.9_Alteryx',
 '7.b.10_Stitch',
 '7.b.11_Fivetran',
 '7.b.12_Google Dataflow',
 '7.b.13_Oracle Data Integrator',
 '7.b.14_IBM DataStage',
 '7.b.15_SAP BW ETL',
 '7.b.16_SQL Server Integration Services (SSIS)',
 '7.b.17_SAS Data Integration',
 '7.b.18_Qlik Sense',
 '7.b.19_Knime',
 '7.b.20_Databricks',
 '7.b.21_Não utilizo ferramentas de ETL',
 '7.c_ferramentas_autonomia_area_de_negocios',
 '7.c.1_Ferramentas de AutoML como H2O.ai, Data Robot, BigML etc.',
 '7.c.2_"Point and Click" Analytics como Alteryx, Knime, Rapidminer etc.',
 '7.c.3_Product metricts & Insights como Mixpanel, Amplitude, Adobe Analytics.',
 '7.c.4_Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.',
 '7.c.5_Minha empresa não utiliza essas ferramentas.',
 '7.c.6_Não sei informar.',
 '7.d_maior_tempo_gasto_como_da',
 '7.d.1_Processando e analisando dados utilizando linguagens de programação como Python, R etc.',
 '7.d.2_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.',
 '7.d.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.',
 "7.d.4_Utilizando API's para extrair dados e complementar minhas análises.",
 '7.d.5_Realizando experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.',
 "7.d.6_Desenvolvendo/cuidando da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.",
 '7.d.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.',
 '7.d.8_Desenvolvendo/cuidando da manutenção de planilhas para atender as áreas de negócio.',
 '7.d.9_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.',
 '7.d.10_Nenhuma das opções listadas refletem meu dia a dia.',
 '8.a_rotina_como_ds',
 '8.a.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.',
 '8.a.2_Sou responsável pela coleta e limpeza dos dados que uso para análise e modelagem.',
 '8.a.3_Sou responsável por entrar em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.',
 '8.a.4_Desenvolvo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).',
 '8.a.5_Sou responsável por colocar modelos em produção, criar os pipelines de dados, APIs de consumo e monitoramento.',
 '8.a.6_Cuido da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.',
 '8.a.7_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc',
 '8.a.8_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.',
 '8.a.9_Crio e dou manutenção em ETLs, DAGs e automações de pipelines de dados.',
 '8.a.10_Crio e gerencio soluções de Feature Store e cultura de MLOps.',
 '8.a.11_Sou responsável por criar e manter a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)',
 "8.a.12_Treino e aplico LLM's para solucionar problemas de negócio.",
 '8.b_tecnicas_e_metodos_ds',
 '8.b.1_Utilizo modelos de regressão (linear, logística, GLM).',
 '8.b.2_Utilizo redes neurais ou modelos baseados em árvore para criar modelos de classificação.',
 '8.b.3_Desenvolvo sistemas de recomendação (RecSys).',
 '8.b.4_Utilizo métodos estatísticos Bayesianos para analisar dados.',
 '8.b.5_Utilizo técnicas de NLP (Natural Language Processing) para análisar dados não-estruturados.',
 '8.b.6_Utilizo métodos estatísticos clássicos (Testes de hipótese, análise multivariada, sobrevivência, dados longitudinais, inferência estatistica) para analisar dados.',
 '8.b.7_Utilizo cadeias de Markov ou HMM\\s para realizar análises de dados.',
 '8.b.8_Desenvolvo técnicas de Clusterização (K-means, Spectral, DBScan etc).',
 '8.b.9_Realizo previsões através de modelos de Séries Temporais (Time Series).',
 '8.b.10_Utilizo modelos de Reinforcement Learning (aprendizado por reforço).',
 '8.b.11_Utilizo modelos de Machine Learning para detecção de fraude.',
 '8.b.12_Utilizo métodos de Visão Computacional.',
 '8.b.13_Utilizo modelos de Detecção de Churn.',
 "8.b.14_Utilizo LLM's para solucionar problemas de negócio.",
 '8.c_tecnologias_ds',
 '8.c.1_Ferramentas de BI (PowerBI, Looker, Tableau, Qlik etc).',
 '8.c.2_Planilhas (Excel, Google Sheets etc).',
 '8.c.3_Ambientes de desenvolvimento local (R-studio, JupyterLab, Anaconda).',
 '8.c.4_Ambientes de desenvolvimento na nuvem (Google Colab, AWS Sagemaker, Kaggle Notebooks etc).',
 '8.c.5_Ferramentas de AutoML (Datarobot, H2O, Auto-Keras etc).',
 '8.c.6_Ferramentas de ETL (Apache Airflow, NiFi, Stitch, Fivetran, Pentaho etc).',
 '8.c.7_Plataformas de Machine Learning (TensorFlow, Azure Machine Learning, Kubeflow etc).',
 '8.c.8_Feature Store (Feast, Hopsworks, AWS Feature Store, Databricks Feature Store etc).',
 '8.c.9_Sistemas de controle de versão (Github, DVC, Neptune, Gitlab etc).',
 '8.c.10_Plataformas de Data Apps (Streamlit, Shiny, Plotly Dash etc).',
 '8.c.11_Ferramentas de estatística avançada como SPSS, SAS, etc.',
 '8.d_maior_tempo_gasto_como_ds',
 '8.d.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.',
 '8.d.2_Coletando e limpando dos dados que uso para análise e modelagem.',
 '8.d.3_Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.',
 '8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).',
 '8.d.5_Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.',
 '8.d.6_Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.',
 '8.d.7_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.',

In [10]:
type(colunas_secoes)

dict

In [11]:
set(df.columns).difference(todas_colunas_secoes)

{'0.a_token', '0.d_data/hora_envio'}

> São colunas que não serão usadas para análise.

##### 3.1 Analisando cada seção

In [12]:
colunas_secoes[1]

['1.a_idade',
 '1.a.1_faixa_idade',
 '1.b_genero',
 '1.c_cor/raca/etnia',
 '1.d_pcd',
 '1.e_experiencia_profissional_prejudicada',
 '1.e.1_Não acredito que minha experiência profissional seja afetada',
 '1.e.2_Sim, devido a minha Cor/Raça/Etnia',
 '1.e.3_Sim, devido a minha identidade de gênero',
 '1.e.4_Sim, devido ao fato de ser PCD',
 '1.i.1_uf_onde_mora',
 '1.f.1_Quantidade de oportunidades de emprego/vagas recebidas',
 '1.f.2_Senioridade das vagas recebidas em relação à sua experiência',
 '1.f.3_Aprovação em processos seletivos/entrevistas',
 '1.f.4_Oportunidades de progressão de carreira',
 '1.f.5_Velocidade de progressão de carreira',
 '1.f.6_Nível de cobrança no trabalho/Stress no trabalho',
 '1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias',
 '1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho',
 '1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho',
 '1.i.2_regiao_onde_mora',
 '1.f_aspectos_prejudicados',
 '1.k.1_uf_de_origem',
 '1.k.2_regiao_de_origem',
 '1.g_vive_no_brasil',
 '1.h_pais_onde_mora',
 '1.i_estado_onde_mora',
 '1.j_vive_no_estado_de_formacao',
 '1.k_estado_de_origem',
 '1.l_nivel_de_ensino',
 '1.m_área_de_formação']

In [13]:
df[colunas_secoes[1]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5217 entries, 0 to 5216
Data columns (total 31 columns):
 #   Column                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                     --------------  -----
 0   1.a_idade                                                                                                  5217 non-null   int64
 1   1.a.1_faixa_idade                                                                                          5217 non-null   object
 2   1.b_genero                                                                                                 5217 non-null   object
 3   1.c_cor/raca/etnia                                                                                         5217 non-null   object
 4   1.d_pcd                                                                                                    5217 non-null   object
 5   1.e_experiencia_profissional_prejudicada                                                                   2641 non-null   object
 6   1.e.1_Não acredito que minha experiência profissional seja afetada                                         2641 non-null   float64
 7   1.e.2_Sim, devido a minha Cor/Raça/Etnia                                                                   2641 non-null   float64
 8   1.e.3_Sim, devido a minha identidade de gênero                                                             2641 non-null   float64
 9   1.e.4_Sim, devido ao fato de ser PCD                                                                       2641 non-null   float64
 10  1.i.1_uf_onde_mora                                                                                         5075 non-null   object
 11  1.f.1_Quantidade de oportunidades de emprego/vagas recebidas                                               1289 non-null   float64
 12  1.f.2_Senioridade das vagas recebidas em relação à sua experiência                                         1289 non-null   float64
 13  1.f.3_Aprovação em processos seletivos/entrevistas                                                         1289 non-null   float64
 14  1.f.4_Oportunidades de progressão de carreira                                                              1289 non-null   float64
 15  1.f.5_Velocidade de progressão de carreira                                                                 1289 non-null   float64
 16  1.f.6_Nível de cobrança no trabalho/Stress no trabalho                                                     1289 non-null   float64
 17  1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias                                       1289 non-null   float64
 18  1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho                                       1289 non-null   float64
 19  1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho  1289 non-null   float64
 20  1.i.2_regiao_onde_mora                                                                                     5075 non-null   object
 21  1.f_aspectos_prejudicados                                                                                  1289 non-null   object
 22  1.k.1_uf_de_origem                                                                                         953 non-null    object
 23  1.k.2_regiao_de_origem                                                                                     953 non-null    object
 24  1.g_vive_no_brasil                                                                                         5217 non-null   bool
 25  1.h_pais_onde_mora                                                                                         139 non-null    object
 26  1.i_estado_onde_mora                                                                                       5078 non-null   object
 27  1.j_vive_no_estado_de_formacao                                                                             5078 non-null   object
 28  1.k_estado_de_origem                                                                                       977 non-null    object
 29  1.l_nivel_de_ensino                                                                                        5217 non-null   object
 30  1.m_área_de_formação                                                                                       5123 non-null   object
dtypes: bool(1), float64(13), int64(1), object(16)
memory usage: 1.2+ MB

In [14]:
df[colunas_secoes[1]].head()

,1.a_idade,1.a.1_faixa_idade,1.b_genero,1.c_cor/raca/etnia,1.d_pcd,1.e_experiencia_profissional_prejudicada,1.e.1_Não acredito que minha experiência profissional seja afetada,"1.e.2_Sim, devido a minha Cor/Raça/Etnia","1.e.3_Sim, devido a minha identidade de gênero","1.e.4_Sim, devido ao fato de ser PCD",...,1.f_aspectos_prejudicados,1.k.1_uf_de_origem,1.k.2_regiao_de_origem,1.g_vive_no_brasil,1.h_pais_onde_mora,1.i_estado_onde_mora,1.j_vive_no_estado_de_formacao,1.k_estado_de_origem,1.l_nivel_de_ensino,1.m_área_de_formação
0,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,True,NaN,Rio Grande do Sul (RS),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
1,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,...,NaN,PR,Sul,True,NaN,Santa Catarina (SC),False,Paraná (PR),Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
2,18,17-21,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,True,NaN,São Paulo (SP),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
3,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,True,NaN,São Paulo (SP),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
4,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,True,NaN,São Paulo (SP),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...

In [15]:
pd.set_option("display.max_columns", None)
df[colunas_secoes[1]].head()

,1.a_idade,1.a.1_faixa_idade,1.b_genero,1.c_cor/raca/etnia,1.d_pcd,1.e_experiencia_profissional_prejudicada,1.e.1_Não acredito que minha experiência profissional seja afetada,"1.e.2_Sim, devido a minha Cor/Raça/Etnia","1.e.3_Sim, devido a minha identidade de gênero","1.e.4_Sim, devido ao fato de ser PCD",1.i.1_uf_onde_mora,1.f.1_Quantidade de oportunidades de emprego/vagas recebidas,1.f.2_Senioridade das vagas recebidas em relação à sua experiência,1.f.3_Aprovação em processos seletivos/entrevistas,1.f.4_Oportunidades de progressão de carreira,1.f.5_Velocidade de progressão de carreira,1.f.6_Nível de cobrança no trabalho/Stress no trabalho,1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias,"1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho","1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho",1.i.2_regiao_onde_mora,1.f_aspectos_prejudicados,1.k.1_uf_de_origem,1.k.2_regiao_de_origem,1.g_vive_no_brasil,1.h_pais_onde_mora,1.i_estado_onde_mora,1.j_vive_no_estado_de_formacao,1.k_estado_de_origem,1.l_nivel_de_ensino,1.m_área_de_formação
0,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,RS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sul,NaN,NaN,NaN,True,NaN,Rio Grande do Sul (RS),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
1,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,SC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sul,NaN,PR,Sul,True,NaN,Santa Catarina (SC),False,Paraná (PR),Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
2,18,17-21,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,1.0,0.0,0.0,0.0,SP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sudeste,NaN,NaN,NaN,True,NaN,São Paulo (SP),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
3,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,SP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sudeste,NaN,NaN,NaN,True,NaN,São Paulo (SP),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...
4,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,NaN,SP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sudeste,NaN,NaN,NaN,True,NaN,São Paulo (SP),True,NaN,Estudante de Graduação,Computação / Engenharia de Software / Sistemas...

In [16]:
colunas_secoes[2]

['2.a_situação_de_trabalho',
 '2.b_setor',
 '2.c_numero_de_funcionarios',
 '2.d_atua_como_gestor',
 '2.e_cargo_como_gestor',
 '2.f_cargo_atual',
 '2.g_nivel',
 '2.h_faixa_salarial',
 '2.i_tempo_de_experiencia_em_dados',
 '2.j_tempo_de_experiencia_em_ti',
 '2.k_satisfeito_atualmente',
 '2.l.1_Remuneração/Salário',
 '2.l.2_Benefícios',
 '2.l.3_Propósito do trabalho e da empresa',
 '2.l.4_Flexibilidade de trabalho remoto',
 '2.l.5_Ambiente e clima de trabalho',
 '2.l.6_Oportunidade de aprendizado e trabalhar com referências',
 '2.l.7_Oportunidades de crescimento',
 '2.l.8_Maturidade da empresa em termos de tecnologia e dados',
 '2.l.9_Relação com os gestores e líderes',
 '2.l.10_Reputação que a empresa tem no mercado',
 '2.l.11_Gostaria de trabalhar em outra área',
 '2.l_motivo_insatisfacao',
 '2.m_participou_de_entrevistas_ultimos_6m',
 '2.n_planos_de_mudar_de_emprego_6m',
 '2.o_criterios_para_escolha_de_emprego',
 '2.o.1_Remuneração/Salário',
 '2.o.2_Benefícios',
 '2.o.3_Propósito do trabalho e da empresa',
 '2.o.4_Flexibilidade de trabalho remoto',
 '2.o.5_Ambiente e clima de trabalho',
 '2.o.6_Oportunidade de aprendizado e trabalhar com referências',
 '2.o.7_Plano de carreira e oportunidades de crescimento',
 '2.o.8_Maturidade da empresa em termos de tecnologia e dados',
 '2.o.9_Qualidade dos gestores e líderes',
 '2.o.10_Reputação que a empresa tem no mercado',
 '2.q_empresa_passou_por_layoff_em_2024',
 '2.r_modelo_de_trabalho_atual',
 '2.s_modelo_de_trabalho_ideal',
 '2.t_atitude_em_caso_de_retorno_presencial']

In [17]:
df[colunas_secoes[2]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5217 entries, 0 to 5216
Data columns (total 40 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   2.a_situação_de_trabalho                                       5217 non-null   object
 1   2.b_setor                                                      4863 non-null   object
 2   2.c_numero_de_funcionarios                                     4863 non-null   object
 3   2.d_atua_como_gestor                                           4863 non-null   object
 4   2.e_cargo_como_gestor                                          1045 non-null   object
 5   2.f_cargo_atual                                                3818 non-null   object
 6   2.g_nivel                                                      3818 non-null   object
 7   2.h_faixa_salarial                                             4863 non-null   object
 8   2.i_tempo_de_experiencia_em_dados                              4863 non-null   object
 9   2.j_tempo_de_experiencia_em_ti                                 4863 non-null   object
 10  2.k_satisfeito_atualmente                                      4863 non-null   object
 11  2.l.1_Remuneração/Salário                                      1527 non-null   float64
 12  2.l.2_Benefícios                                               1527 non-null   float64
 13  2.l.3_Propósito do trabalho e da empresa                       1527 non-null   float64
 14  2.l.4_Flexibilidade de trabalho remoto                         1527 non-null   float64
 15  2.l.5_Ambiente e clima de trabalho                             1527 non-null   float64
 16  2.l.6_Oportunidade de aprendizado e trabalhar com referências  1527 non-null   float64
 17  2.l.7_Oportunidades de crescimento                             1527 non-null   float64
 18  2.l.8_Maturidade da empresa em termos de tecnologia e dados    1527 non-null   float64
 19  2.l.9_Relação com os gestores e líderes                        1527 non-null   float64
 20  2.l.10_Reputação que a empresa tem no mercado                  1527 non-null   float64
 21  2.l.11_Gostaria de trabalhar em outra área                     1527 non-null   float64
 22  2.l_motivo_insatisfacao                                        1527 non-null   object
 23  2.m_participou_de_entrevistas_ultimos_6m                       4863 non-null   object
 24  2.n_planos_de_mudar_de_emprego_6m                              4863 non-null   object
 25  2.o_criterios_para_escolha_de_emprego                          4862 non-null   object
 26  2.o.1_Remuneração/Salário                                      4863 non-null   float64
 27  2.o.2_Benefícios                                               4863 non-null   float64
 28  2.o.3_Propósito do trabalho e da empresa                       4863 non-null   float64
 29  2.o.4_Flexibilidade de trabalho remoto                         4863 non-null   float64
 30  2.o.5_Ambiente e clima de trabalho                             4863 non-null   float64
 31  2.o.6_Oportunidade de aprendizado e trabalhar com referências  4863 non-null   float64
 32  2.o.7_Plano de carreira e oportunidades de crescimento         4863 non-null   float64
 33  2.o.8_Maturidade da empresa em termos de tecnologia e dados    4863 non-null   float64
 34  2.o.9_Qualidade dos gestores e líderes                         4863 non-null   float64
 35  2.o.10_Reputação que a empresa tem no mercado                  4863 non-null   float64
 36  2.q_empresa_passou_por_layoff_em_2024                          4863 non-null   object
 37  2.r_modelo_de_trabalho_atual                                   4863 non-null   object
 38  2.s_modelo_de_trabalho_ideal                                   4863 non-null   object
 39  2.t_atitude_em_caso_de_retorno_presencial                      4863 non-null   object
dtypes: float64(21), object(19)
memory usage: 1.6+ MB

In [18]:
pd.set_option("display.max_columns", None)
df[colunas_secoes[2]].head()

,2.a_situação_de_trabalho,2.b_setor,2.c_numero_de_funcionarios,2.d_atua_como_gestor,2.e_cargo_como_gestor,2.f_cargo_atual,2.g_nivel,2.h_faixa_salarial,2.i_tempo_de_experiencia_em_dados,2.j_tempo_de_experiencia_em_ti,2.k_satisfeito_atualmente,2.l.1_Remuneração/Salário,2.l.2_Benefícios,2.l.3_Propósito do trabalho e da empresa,2.l.4_Flexibilidade de trabalho remoto,2.l.5_Ambiente e clima de trabalho,2.l.6_Oportunidade de aprendizado e trabalhar com referências,2.l.7_Oportunidades de crescimento,2.l.8_Maturidade da empresa em termos de tecnologia e dados,2.l.9_Relação com os gestores e líderes,2.l.10_Reputação que a empresa tem no mercado,2.l.11_Gostaria de trabalhar em outra área,2.l_motivo_insatisfacao,2.m_participou_de_entrevistas_ultimos_6m,2.n_planos_de_mudar_de_emprego_6m,2.o_criterios_para_escolha_de_emprego,2.o.1_Remuneração/Salário,2.o.2_Benefícios,2.o.3_Propósito do trabalho e da empresa,2.o.4_Flexibilidade de trabalho remoto,2.o.5_Ambiente e clima de trabalho,2.o.6_Oportunidade de aprendizado e trabalhar com referências,2.o.7_Plano de carreira e oportunidades de crescimento,2.o.8_Maturidade da empresa em termos de tecnologia e dados,2.o.9_Qualidade dos gestores e líderes,2.o.10_Reputação que a empresa tem no mercado,2.q_empresa_passou_por_layoff_em_2024,2.r_modelo_de_trabalho_atual,2.s_modelo_de_trabalho_ideal,2.t_atitude_em_caso_de_retorno_presencial
0,Estagiário,Marketing,de 101 a 500,False,NaN,Analista de Dados/Data Analyst,Júnior,de R$ 1.001/mês a R$ 2.000/mês,de 1 a 2 anos,de 1 a 2 anos,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sim, fui aprovado e mudei de emprego","Não estou buscando, mas me considero aberto a ...","Remuneração/Salário, Reputação que a empresa t...",1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,"Sim, ocorreram layoffs/demissões em massa na e...",Modelo 100% remoto,Modelo híbrido flexível (o funcionário tem lib...,Vou procurar outra oportunidade no modelo híbr...
1,Estagiário,Finanças ou Bancos,Acima de 3.000,False,NaN,Analista de BI/BI Analyst,Júnior,Menos de R$ 1.000/mês,Menos de 1 ano,Menos de 1 ano,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não participei de entrevistas de emprego/proce...,Não estou buscando e não pretendo mudar de emp...,Oportunidade de aprendizado e trabalhar com re...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,Não ocorreram layoffs/demissões em massa na em...,Modelo 100% presencial,Modelo 100% presencial,Vou aceitar e retornar ao modelo 100% presencial
2,Empregado (CLT),Indústria,de 501 a 1.000,False,NaN,Outra Opção,Júnior,de R$ 1.001/mês a R$ 2.000/mês,Não tenho experiência na área de dados,Não tive experiência na área de TI/Engenharia ...,False,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Remuneração/Salário não corresponde a realidad...,Não participei de entrevistas de emprego/proce...,Estou em busca de oportunidades dentro ou fora...,"Remuneração/Salário, Propósito do trabalho e d...",1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Não ocorreram layoffs/demissões em massa na em...,Modelo 100% presencial,Modelo híbrido com dias fixos de trabalho pres...,Vou aceitar e retornar ao modelo 100% presencial
3,Estagiário,Tecnologia/Fábrica de Software,de 501 a 1.000,False,NaN,Analista de Dados/Data Analyst,Júnior,de R$ 1.001/mês a R$ 2.000/mês,Menos de 1 ano,Não tive experiência na área de TI/Engenharia ...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não participei de entrevistas de emprego/proce...,Não estou buscando e não pretendo mudar de emp...,Oportunidade de aprendizado e trabalhar com re...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,Não ocorreram layoffs/demissões em massa na em...,Modelo híbrido flexível (o funcionário tem lib...,Modelo híbrido flexível (o funcionário tem lib...,Vou aceitar e retornar ao modelo 100% presencial
4,Estagiário,Tecnologia/Fábrica de Software,de 1.001 a 3.000,False,NaN,Desenvolvedor/ Engenheiro de Software/ Analist...,Júnior,de R$ 1.001/mês a R$ 2.000/mês,Menos de 1 ano,Menos de 1 ano,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sim, fui aprovado mas decidi não mudar de emprego",Não estou buscando e não pretendo mudar de emp...,Oportunidade de aprendizado e trabalhar com re...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,Não ocorreram layoffs/demissões em massa na em...,Modelo 100% remoto,Modelo híbrido flexível (o funcionário tem lib...,Vou aceitar e retornar ao modelo 100% presencial

In [19]:
# Gerando estatísticas descritivas para colunas numéricas.
df.describe()

,1.a_idade,1.e.1_Não acredito que minha experiência profissional seja afetada,"1.e.2_Sim, devido a minha Cor/Raça/Etnia","1.e.3_Sim, devido a minha identidade de gênero","1.e.4_Sim, devido ao fato de ser PCD",1.f.1_Quantidade de oportunidades de emprego/vagas recebidas,1.f.2_Senioridade das vagas recebidas em relação à sua experiência,1.f.3_Aprovação em processos seletivos/entrevistas,1.f.4_Oportunidades de progressão de carreira,1.f.5_Velocidade de progressão de carreira,1.f.6_Nível de cobrança no trabalho/Stress no trabalho,1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias,"1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho","1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho",2.l.1_Remuneração/Salário,2.l.2_Benefícios,2.l.3_Propósito do trabalho e da empresa,2.l.4_Flexibilidade de trabalho remoto,2.l.5_Ambiente e clima de trabalho,2.l.6_Oportunidade de aprendizado e trabalhar com referências,2.l.7_Oportunidades de crescimento,2.l.8_Maturidade da empresa em termos de tecnologia e dados,2.l.9_Relação com os gestores e líderes,2.l.10_Reputação que a empresa tem no mercado,2.l.11_Gostaria de trabalhar em outra área,2.o.1_Remuneração/Salário,2.o.2_Benefícios,2.o.3_Propósito do trabalho e da empresa,2.o.4_Flexibilidade de trabalho remoto,2.o.5_Ambiente e clima de trabalho,2.o.6_Oportunidade de aprendizado e trabalhar com referências,2.o.7_Plano de carreira e oportunidades de crescimento,2.o.8_Maturidade da empresa em termos de tecnologia e dados,2.o.9_Qualidade dos gestores e líderes,2.o.10_Reputação que a empresa tem no mercado,3.b.1_Analytics Engineer,3.b.2_Engenharia de Dados/Data Engineer,3.b.3_Analista de Dados/Data Analyst,3.b.4_Cientista de Dados/Data Scientist,3.b.5_Database Administrator/DBA,3.b.6_Analista de Business Intelligence/BI,3.b.7_Arquiteto de Dados/Data Architect,3.b.8_Data Product Manager/DPM,3.b.9_Business Analyst,3.b.10_ML Engineer/AI Engineer,3.c.1_Pensar na visão de longo prazo de dados,3.c.2_Organização de treinamentos e iniciativas,"3.c.3_Atração, seleção e contratação",3.c.4_Decisão sobre contratação de ferramentas,3.c.5_gestor da equipe de engenharia de dados,"3.c.6_gestor da equipe de estudos, relatórios",3.c.7_gestor da equipe de Inteligência Artificial e Machine Learning,3.c.8_Apesar de ser gestor ainda atuo na parte técnica,3.c.9_Gestão de projetos de dados,3.c.10_Gestão de produtos de dados,3.c.11_Gestão de pessoas,3.d.1_Contratar talentos,3.d.2_Reter talentos,3.d.3_Convencer a empresa a aumentar investimentos,3.d.4_Gestão de equipes no ambiente remoto,3.d.5_Gestão de projetos envolvendo áreas multidisciplinares,3.d.6_Organizar as informações com qualidade e confiabilidade,3.d.7_Processar e armazenar um alto volume de dados,3.d.8_Gerar valor para as áreas de negócios,3.d.9_Desenvolver e manter modelos Machine Learning em produção,3.d.10_Gerenciar a expectativa das áreas,3.d.11_Garantir a manutenção dos projetos e modelos em produção,3.d.12_Conseguir levar inovação para a empresa,3.d.13_Garantir (ROI) em projetos de dados,3.d.14_Dividir o tempo entre entregas técnicas e gestão,3.f.1 Colaboradores usando AI generativa de forma independente e descentralizada,3.f.2 Direcionamento centralizado do uso de AI generativa,3.f.3 Desenvolvedores utilizando Copilots,3.f.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais,3.f.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores,3.f.6 IA Generativa e LLMs como principal frente do negócio,3.f.7 IA Generativa e LLMs não é prioridade,3.f.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa,3.g.1 Falta de compreensão dos casos de uso,3.g.2 Falta de confiabilidade das saídas (alucinação dos modelos),3.g.3 Incerteza em relação a regulamentação,3.g.4 Preocupações com segurança e privacidade de dados,3.g.5 Retorno sobre investimento (ROI) não comprovado de IA Generativa,3.g.6 Dados da empresa não estão prontos para uso de IA Generativa,3.g.7 Falta de expertise ou falta de recursos,3.g.8 Alta direção da empresa não vê valor ou não vê como prioridade,3.g.9 Preocupações com propriedade intelectual,4.b.1_Dados relacionais (estruturados em bancos SQL),4.b.2_Dados armazenados em bancos NoSQL,4.b.3_Imagens,4.b.4_Textos/Documentos,4.b.5_Vídeos,4.b.6_Áudios,4.b.7_Planilhas,4.b.8_Dados georeferenciados,4.c.1_Dados relacionais (estruturados em bancos SQL),4.c.2_Dados armazenados em bancos NoSQL,4.c.3_Imagens,4.c.4_Textos/Documentos,4.c.5_Vídeos,4.c.6_Áudios,4.c.7_Planilhas,4.c.8_Dados georeferenciados,4.d.1_SQL,4.d.2_R,4.d.3_Python,4.d.4_C/C++/C#,4.d.5_.NET,4.d.6_Java,4.d.7_Julia,4.d.8_SAS/Stata,4.d.9_Visual Basic/VBA,4.d.10_Scala,4.d.11_Matlab,4.d.12_Rust,4.d.13_PHP,4.d.14_JavaScript,4.d.15_Não utilizo nenhuma das linguagens listadas,4.g.1_MySQL,4.g.2_Oracle,4.g.3_SQL SERVER,4.g.4_Amazon Aurora ou RDS,4.g.5_DynamoDB,4.g.6_CoachDB,4.g.7_Cassandra,4.g.8_MongoDB,4.g.9_MariaDB,4.g.10_Datomic,4.g.11_S3,4.g.12_PostgreSQL,4.g.13_ElasticSearch,4.g.14_DB2,4.g.15_Microsoft Access,4.g.16_SQLite,4.g.17_Sybase,4.g.18_Firebase,4.g.19_Vertica,4.g.20_Redis,4.g.21_Neo4J,4.g.22_Google BigQuery,4.g.23_Google Firestore,4.g.24_Amazon Redshift,4.g.25_Amazon Athena,4.g.26_Snowflake,4.g.27_Databricks,4.g.28_HBase,4.g.29_Presto,4.g.30_Splunk,4.g.31_SAP HANA,4.g.32_Hive,4.g.33_Firebird,4.h.1_Amazon Web Services (AWS),4.h.2_Google Cloud (GCP),4.h.3_Azure (Microsoft),4.h.4_Oracle Cloud,4.h.5_IBM,4.h.6_Servidores On Premise/Não utilizamos Cloud,4.h.7_Cloud Própria,4.j.1_Microsoft PowerBI,4.j.2_Qlik View/Qlik Sense,4.j.3_Tableau,4.j.4_Metabase,4.j.5_Superset,4.j.6_Redash,4.j.7_Looker,4.j.8_Looker Studio(Google Data Studio),4.j.9_Amazon Quicksight,4.j.10_Alteryx,4.j.11_SAP Business Objects/SAP Analytics,4.j.12_Oracle Business Intelligence,4.j.13_Salesforce/Einstein Analytics,4.j.14_SAS Visual Analytics,4.j.15_Grafana,4.j.16_Pentaho,4.j.17_Fazemos todas as análises utilizando apenas Excel ou planilhas do google,4.j.18_Não utilizo nenhuma ferramenta de BI no trabalho,4.l.1 Colaboradores usando AI generativa de forma independente e descentralizada,4.l.2 Direcionamento centralizado do uso de AI generativa,4.l.3 Desenvolvedores utilizando Copilots,4.l.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais,4.l.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores,4.l.6 IA Generativa e LLMs como principal frente do negócio,4.l.7 IA Generativa e LLMs não é prioridade,4.l.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa,4.m.1 Não uso soluções de AI Generativa com foco em produtividade,4.m.2 Uso soluções gratuitas de AI Generativa com foco em produtividade,4.m.3 Uso e pago pelas soluções de AI Generativa com foco em produtividade,4.m.4 A empresa que trabalho paga pelas soluções de AI Generativa com foco em produtividade,4.m.5 Uso soluções do tipo Copilot,"6.a.1_Desenvolvo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.","6.a.2_Realizo construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.",6.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.,"6.a.4_Atuo na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.","6.a.5_Modelo soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.",6.a.6_Desenvolvo/cuido da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.,"6.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.","6.a.8_Cuido da qualidade dos dados, metadados e dicionário de dados.",6.a.9_Nenhuma das opções listadas refletem meu dia a dia.,6.b.1_Scripts Python,6.b.2_SQL & Stored Procedures,6.b.3_Apache Airflow,6.b.4_Apache NiFi,6.b.5_Luigi,6.b.6_AWS Glue,6.b.7_Talend,6.b.8_Pentaho,6.b.9_Alteryx,6.b.10_Stitch,6.b.11_Fivetran,6.b.12_Google Dataflow,6.b.13_Oracle Data Integrator,6.b.14_IBM DataStage,6.b.15_SAP BW ETL,6.b.16_SQL Server Integration Services (SSIS),6.b.17_SAS Data Integration,6.b.18_Qlik Sense,6.b.19_Knime,6.b.20_Databricks,6.b.21_Não utilizo ferramentas de ETL,"6.h.1_Desenvolvendo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.","6.h.2_Realizando construções de ETL\s em ferramentas como Pentaho, Talend, Dataflow etc.",6.h.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.,"6.h.4_Atuando na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.","6.h.5_Modelando soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.",6.h.6_Desenvolvendo/cuidando da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.,"6.h.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.","6.h.8_Cuidando da qualidade dos dados, metadados e dicionário de dados.",6.h.9_Nenhuma das opções listadas refletem meu dia a dia.,"7.a.1_Processo e analiso dados utilizando linguagens de programação como Python, R etc.","7.a.2_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.",7.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.,7.a.4_Utilizo API\s para extrair dados e complementar minhas análises.,"7.a.5_Realizo experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.","7.a.6_Desenvolvo/cuido da manutenção de ETL\s utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.","7.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.",7.a.8_Desenvolvo/cuido da manutenção de planilhas para atender as áreas de negócio.,"7.a.9_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.",7.a.10_Nenhuma das opções listadas refletem meu dia a dia.,7.b.1_Scripts Python,7.b.2_SQL & Stored Procedures,7.b.3_Apache Airflow,7.b.4_Apache NiFi,7.b.5_Luigi,7.b.6_AWS Glue,7.b.7_Talend,7.b.8_Pentaho,7.b.9_Alteryx,7.b.10_Stitch,7.b.11_Fivetran,7.b.12_Google Dataflow,7.b.13_Oracle Data Integrator,7.b.14_IBM DataStage,7.b.15_SAP BW ETL,7.b.16_SQL Server Integration Services (SSIS),7.b.17_SAS Data Integration,7.b.18_Qlik Sense,7.b.19_Knime,7.b.20_Databricks,7.b.21_Não utilizo ferramentas de ETL,"7.c.1_Ferramentas de AutoML como H2O.ai, Data Robot, BigML etc.","7.c.2_""Point and Click"" Analytics como Alteryx, Knime, Rapidminer etc.","7.c.3_Product metricts & Insights como Mixpanel, Amplitude, Adobe Analytics.",7.c.4_Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.,7.c.5_Minha empresa não utiliza essas ferramentas.,7.c.6_Não sei informar.,"7.d.1_Processando e analisando dados utilizando linguagens de programação como Python, R etc.","7.d.2_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.",7.d.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.,7.d.4_Utilizando API's para extrair dados e complementar minhas análises.,"7.d.5_Realizando experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.","7.d.6_Desenvolvendo/cuidando da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.","7.d.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.",7.d.8_Desenvolvendo/cuidando da manutenção de planilhas para atender as áreas de negócio.,"7.d.9_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.",7.d.10_Nenhuma das opções listadas refletem meu dia a dia.,"8.a.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.",8.a.2_Sou responsável pela coleta e limpeza dos dados que uso para análise e modelagem.,"8.a.3_Sou responsável por entrar em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.",8.a.4_Desenvolvo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).,"8.a.5_Sou responsável por colocar modelos em produção, criar os pipelines de dados, APIs de consumo e monitoramento.","8.a.6_Cuido da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.","8.a.7_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc","8.a.8_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.","8.a.9_Crio e dou manutenção em ETLs, DAGs e automações de pipelines de dados.",8.a.10_Crio e gerencio soluções de Feature Store e cultura de MLOps.,"8.a.11_Sou responsável por criar e manter a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)",8.a.12_Treino e aplico LLM's para solucionar problemas de negócio.,"8.b.1_Utilizo modelos de regressão (linear, logística, GLM).",8.b.2_Utilizo redes neurais ou modelos baseados em árvore para criar modelos de classificação.,8.b.3_Desenvolvo sistemas de recomendação (RecSys).,8.b.4_Utilizo métodos estatísticos Bayesianos para analisar dados.,8.b.5_Utilizo técnicas de NLP (Natural Language Processing) para análisar dados não-estruturados.,"8.b.6_Utilizo métodos estatísticos clássicos (Testes de hipótese, análise multivariada, sobrevivência, dados longitudinais, inferência estatistica) para analisar dados.",8.b.7_Utilizo cadeias de Markov ou HMM\s para realizar análises de dados.,"8.b.8_Desenvolvo técnicas de Clusterização (K-means, Spectral, DBScan etc).",8.b.9_Realizo previsões através de modelos de Séries Temporais (Time Series).,8.b.10_Utilizo modelos de Reinforcement Learning (aprendizado por reforço).,8.b.11_Utilizo modelos de Machine Learning para detecção de fraude.,8.b.12_Utilizo métodos de Visão Computacional.,8.b.13_Utilizo modelos de Detecção de Churn.,8.b.14_Utilizo LLM's para solucionar problemas de negócio.,"8.c.1_Ferramentas de BI (PowerBI, Looker, Tableau, Qlik etc).","8.c.2_Planilhas (Excel, Google Sheets etc).","8.c.3_Ambientes de desenvolvimento local (R-studio, JupyterLab, Anaconda).","8.c.4_Ambientes de desenvolvimento na nuvem (Google Colab, AWS Sagemaker, Kaggle Notebooks etc).","8.c.5_Ferramentas de AutoML (Datarobot, H2O, Auto-Keras etc).","8.c.6_Ferramentas de ETL (Apache Airflow, NiFi, Stitch, Fivetran, Pentaho etc).","8.c.7_Plataformas de Machine Learning (TensorFlow, Azure Machine Learning, Kubeflow etc).","8.c.8_Feature Store (Feast, Hopsworks, AWS Feature Store, Databricks Feature Store etc).","8.c.9_Sistemas de controle de versão (Github, DVC, Neptune, Gitlab etc).","8.c.10_Plataformas de Data Apps (Streamlit, Shiny, Plotly Dash etc).","8.c.11_Ferramentas de estatística avançada como SPSS, SAS, etc.","8.d.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.",8.d.2_Coletando e limpando dos dados que uso para análise e modelagem.,"8.d.3_Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.",8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).,"8.d.5_Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.","8.d.6_Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.","8.d.7_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.","8.d.8_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.","8.d.9_Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.",8.d.10_Criando e gerenciando soluções de Feature Store e cultura de MLOps.,"8.d.11_Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)",8.d.12_Treinando e aplicando LLM's para solucionar problemas de negócio.

#### 4. Verificação de Valores Faltantes

In [20]:
missing = df.isnull().mean().sort_values(ascending=False)
missing[missing > 0]   # Focando apenas nas variáveis com ausência
print(missing.head(20))

1.h_pais_onde_mora                                                                                                                                                                                     0.973356
5.b_oportunidade_buscada                                                                                                                                                                               0.945179
5.d_experiencia_em_processos_seletivos                                                                                                                                                                 0.944604
5.c_tempo_em_busca_de_oportunidade                                                                                                                                                                     0.944412
5.a_objetivo_na_area_de_dados                                                                                                                                                                          0.896301
6.g_ferramentas_de_qualidade_de_dados_(dia_a_dia)                                                                                                                                                      0.892659
6.f_tecnologia_data_warehouse                                                                                                                                                                          0.860840
6.d_tecnologia_data_lake                                                                                                                                                                               0.859114
8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).                                                                                 0.851831
8.d.5_Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.                                                                                                   0.851831
8.d.6_Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.                                                         0.851831
8.d.10_Criando e gerenciando soluções de Feature Store e cultura de MLOps.                                                                                                                             0.851831
8.d.12_Treinando e aplicando LLM's para solucionar problemas de negócio.                                                                                                                               0.851831
8.d.11_Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)                                                                                      0.851831
8.a.8_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.                                                                                                  0.851831
8.a.9_Crio e dou manutenção em ETLs, DAGs e automações de pipelines de dados.                                                                                                                          0.851831
8.a.10_Crio e gerencio soluções de Feature Store e cultura de MLOps.                                                                                                                                   0.851831
8.a.11_Sou responsável por criar e manter a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)                                                                      0.851831
8.a_rotina_como_ds                                                                                                                                                                                     0.851831
8.a.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.    0.851831
dtype: float64

#### 5. Gráficos Exploratórios Iniciais

##### 5.1 Distribuição por Faixa Etária

In [21]:
g1 = px.histogram(
    df,
    x="1.a.1_faixa_idade",
    title="Distribuição por Faixa Etária",
    text_auto=True,
)
g1.update_layout(xaxis_title="Faixa Etária", yaxis_title="Nº de Pessoas")
g1.show()

##### 5.2 Distribuição por Nível de Senioridade

In [22]:
g2 = px.histogram(
    df,
    x="2.g_nivel",
    title="Distribuição por Nível de Senioridade",
    text_auto=True,
)
g2.update_layout(xaxis_title="Nível do Senioridade", yaxis_title="Nº de Pessoas")
g2.show()

##### 5.3 Distribuição da Faixa Salarial

In [23]:
# Mapeamento para rótulos simplificados
mapa_faixas = {
    "Menos de R$ 1.000/mês": "< R$1K",
    "de R$ 1.001/mês a R$ 2.000/mês": "R$1K-2K",
    "de R$ 2.001/mês a R$ 3.000/mês": "R$2K-3K",
    "de R$ 3.001/mês a R$ 4.000/mês": "R$3K-4K",
    "de R$ 4.001/mês a R$ 6.000/mês": "R$4K-6K",
    "de R$ 6.001/mês a R$ 8.000/mês": "R$6K-8K",
    "de R$ 8.001/mês a R$ 12.000/mês": "R$8K-12K",
    "de R$ 12.001/mês a R$ 16.000/mês": "R$12K-16K",
    "de R$ 16.001/mês a R$ 20.000/mês": "R$16K-20K",
    "de R$ 20.001/mês a R$ 25.000/mês": "R$20K-25K",
    "de R$ 25.001/mês a R$ 30.000/mês": "R$25K-30K",
    "de R$ 30.001/mês a R$ 40.000/mês": "R$30K-40K",
    "Acima de R$ 40.001/mês": "> R$40K",
}

# Aplicando a coluna formatada
df["faixa_salarial_simplificada"] = df["2.h_faixa_salarial"].map(mapa_faixas)

# Definindo a nova ordem simplificada
ordem_simplificada = list(mapa_faixas.values())

g3 = px.histogram(
    df,
    x="faixa_salarial_simplificada",
    category_orders={"faixa_salarial_simplificada": ordem_simplificada},
    title="Distribuição da Faixa Salarial",
    text_auto=True,
)
g3.update_layout(xaxis_title="Faixa Salarial", yaxis_title="Nº de Pessoas")
g3.show()

##### 5.4 Tempo de Experiência em Dados

In [24]:
# Mapeamento para rótulos simplificados
mapa_exp = {
    "Não tenho experiência na área de dados": "Sem experiência",
    "Menos de 1 ano": "<1 ano",
    "de 1 a 2 anos": "1-2 anos",
    "de 3 a 4 anos": "3-4 anos",
    "de 5 a 6 anos": "5-6 anos",
    "de 7 a 10 anos": "7-10 anos",
    "Mais de 10 anos": ">10 anos",
}

# Aplicando a coluna formatada
df["exp_dados_simplificado"] = df["2.i_tempo_de_experiencia_em_dados"].map(mapa_exp)

# Ordem das colunas
ordem_exp = [
    "Sem experiência",
    "<1 ano",
    "1-2 anos",
    "3-4 anos",
    "5-6 anos",
    "7-10 anos",
    ">10 anos",
]

g4 = px.histogram(
    df,
    x="exp_dados_simplificado",
    category_orders={"exp_dados_simplificado": ordem_exp},
    title="Distribuição por Tempo de Experiência em Dados",
    labels={"exp_dados_simplificado": "Tempo de Experiência"},
    text_auto=True
)
g4.update_layout(
    xaxis_title="Tempo de experiência na área de dados", yaxis_title="Nº de Pessoas"
)
g4.show()

##### 5.5 Distribuição de Cargos de Gestão

In [25]:
# Mapeamento para rótulos
df["atua_como_gestor_bin"] = df["2.d_atua_como_gestor"].map({True: "Sim", False: "Não"})

# Proporção de Pessoas que Atuam como Gestor(a)
g5 = px.histogram(
    df,
    x="atua_como_gestor_bin",
    title="Distribuição de Pessoas em Cargos de Gestão",
    labels={"atua_como_gestor_bin": "Atua como Gestor(a)?"},
    text_auto=True,
)
g5.update_layout(xaxis_title=None, yaxis_title="Nº de Pessoas")
g5.show()

##### 5.6 Atuação como Gestor(a) por Grupo Etário

In [26]:
# Para entender se há diferença na ocupação de cargos de liderança entre faixas etárias, o gráfico abaixo mostra a proporção de profissionais que atuam como gestores, segmentada por grupo etário (<40 e 40+).
# Criando variável de grupo etário
faixas_40mais = ["40-44", "45-49", "50-54", "55+"]
df["grupo_idade"] = df["1.a.1_faixa_idade"].apply(
    lambda x: "40+" if x in faixas_40mais else "<40"
)

# Criaando coluna para rótulo de gestor
df["atua_como_gestor_bin"] = df["2.d_atua_como_gestor"].map({True: "Sim", False: "Não"})

g6 = px.histogram(
    df,
    x="grupo_idade",
    color="atua_como_gestor_bin",
    barmode="group",
    title="Atuação como Gestor(a) por Grupo Etário",
    labels={
        "grupo_idade": "Grupo Etário",
        "atua_como_gestor_bin": "Atua como Gestor(a)?",
    },
)
g6.update_layout(yaxis_title="Nº de Pessoas")
g6.show()

#### Observações Gerais

- O mercado de dados é majoritariamente ocupado por profissionais entre 25 e 34 anos. A faixa 40+ representa uma pequena parcela da amostra, reforçando a necessidade de analisar se há barreiras à entrada ou permanência desse grupo.
- A maioria dos respondentes atua nos níveis Júnior ou Pleno, e poucos alcançam cargos mais altos, mesmo entre os mais experientes.
- Os salários concentram-se nas faixas entre R$ 4.000 e R$ 12.000. Faixas superiores são menos acessíveis.
- Apesar da senioridade etária, muitos profissionais 40+ têm até 4 anos de experiência em dados, o que pode indicar transição de carreira tardia.
- A maioria dos participantes não atua em cargos de gestão, embora o grupo 40+ tenha proporção ligeiramente maior de gestores. Ainda assim, o número absoluto de líderes permanece baixo, mesmo entre os mais experientes.

### Análise das Hipóteses

#### A partir da exploração inicial dos dados, três hipóteses principais foram formuladas sobre os desafios enfrentados por profissionais com 40 anos ou mais no mercado de dados. A seguir, analisamos cada uma com base nas variáveis da pesquisa.

#### H1. Profissionais 40+ enfrentam mais dificuldade para progredir na carreira?

Objetivo: Verificar se os profissionais com 40 anos ou mais estão concentrados em níveis mais baixos de senioridade.

- Variáveis:
  - `grupo_idade` (derivada de `1.a.1_faixa_idade`)
  - `2.g_nivel` (nível de senioridade)

In [27]:
g_h1 = px.histogram(
    df,
    x="2.g_nivel",
    color="grupo_idade",
    barmode="group",
    title="Distribuição de Nível de Senioridade por Grupo Etário",
    labels={"2.g_nivel": "Nível de Senioridade", "grupo_idade": "Grupo Etário"},
)

g_h1.update_layout(xaxis_title="Senioridade", yaxis_title="Nº de Pessoas")

g_h1.show()

**Interpretação:**

O gráfico mostra que o grupo 40+ está mais representado em cargos Sênior e de Gestão do que o grupo mais jovem — o que pode ser esperado. No entanto, ainda há presença significativa de profissionais 40+ em níveis Júnior e Pleno.

Isso pode indicar dois cenários:

- Parte desses profissionais pode estar em transição de carreira, começando na área de dados com mais idade.
- Ou ainda há barreiras para progressão, mesmo com experiência acumulada.

Esse padrão reforça a necessidade de explorar outras dimensões, como tempo de experiência, percepção de discriminação e defasagem técnica.

#### H2. Profissionais 40+ estão mais concentrados em áreas menos técnicas ou mais voltadas à gestão?
Objetivo: Investigar se profissionais com 40 anos ou mais ocupam mais cargos de gestão ou funções menos técnicas, enquanto profissionais mais jovens estão majoritariamente em cargos técnicos.

Variáveis sugeridas:

- grupo_idade (derivada de 1.a.1_faixa_idade)

- 2.d_atua_como_gestor (indica se exerce cargo de gestão)

- 2.f_cargo_atual ou 4.a_funcao_de_atuacao (para classificar áreas técnicas vs. não técnicas)

In [36]:
# Verificar os valores únicos da coluna de cargo
df["2.f_cargo_atual"].value_counts()

2.f_cargo_atual
Analista de Dados/Data Analyst                                 957
Cientista de Dados/Data Scientist                              687
Engenheiro de Dados/Data Engineer/Data Architect               613
Analista de BI/BI Analyst                                      396
Outra Opção                                                    254
Analytics Engineer                                             228
Analista de Negócios/Business Analyst                          184
Desenvolvedor/ Engenheiro de Software/ Analista de Sistemas    122
Engenheiro de Machine Learning/ML Engineer/AI Engineer         103
Data Product Manager/ Product Manager (PM/APM/DPM/GPM/PO)       80
Analista de Suporte/Analista Técnico                            79
Arquiteto de Dados/Data Architect                               48
Outras Engenharias (não inclui dev)                             29
Professor/Pesquisador                                           21
Estatístico                                                     17
Name: count, dtype: int64

In [37]:
# Função refinada para classificar os cargos
def classificar_cargo(cargo):
    if pd.isnull(cargo):
        return "Não informado"

    cargo = cargo.lower()

    # Gestão
    if (
        "product manager" in cargo
        or "pm" in cargo
        or "dpm" in cargo
        or "gpm" in cargo
        or "po" in cargo
    ):
        return "Gestão"

    # Técnico
    elif any(
        palavra in cargo
        for palavra in [
            "analista de dados",
            "data analyst",
            "cientista de dados",
            "data scientist",
            "engenheiro de dados",
            "data engineer",
            "analytics engineer",
            "bi analyst",
            "analista de bi",
            "analista de negócios",
            "business analyst",
            "engenheiro de software",
            "desenvolvedor",
            "ml engineer",
            "engenheiro de machine learning",
            "ai engineer",
            "arquiteto de dados",
            "estatístico",
            "analista técnico",
            "analista de suporte",
        ]
    ):
        return "Técnico"

    # Outros
    else:
        return "Outros"

In [38]:
# Aplicando a função no dataframe
df["categoria_cargo"] = df["2.f_cargo_atual"].apply(classificar_cargo)

In [39]:
# Criar tabela com proporções
tabela_cargo = (
    df.groupby(["grupo_idade", "categoria_cargo"]).size().reset_index(name="quantidade")
)

tabela_cargo["proporcao"] = tabela_cargo.groupby("grupo_idade")["quantidade"].transform(
    lambda x: x / x.sum()
)

In [41]:
g_h2 = px.bar(
    tabela_cargo,
    x="grupo_idade",
    y="proporcao",
    color="categoria_cargo",
    barmode="group",
    text="quantidade",
    title="Distribuição de Tipos de Cargo por Grupo Etário",
    labels={
        "grupo_idade": "Grupo Etário",
        "proporcao": "Proporção",
        "categoria_cargo": "Tipo de Cargo",
    },
)
g_h2.update_layout(yaxis_tickformat=".0%", xaxis_title=None)
g_h2.show()

A hipótese 2 é parcialmente confirmada:

Profissionais mais jovens (<40) estão mais concentrados em cargos técnicos.

Profissionais 40+ têm menos presença técnica proporcionalmente, mas não necessariamente mais presença em cargos de gestão.

A alta taxa de respostas “Não informado” no grupo 40+ sugere que a análise pode estar subestimando ou distorcendo a realidade desse grupo.

#### H3. Profissionais 40+ apresentam menor domínio ou uso de ferramentas modernas?

Objetivo: Verificar se profissionais 40+ usam menos ferramentas populares ou modernas de dados.

- Variáveis:
  - `grupo_idade`
  - Perguntas multivaloradas de ferramentas (ex: `4.b_ferramentas_de_visualizacao_` ou `7.c_ferramentas_de_analise_`)

Sugestão de gráfico:
- Heatmap ou barras empilhadas: **Uso de ferramentas por grupo etário**
- Pode-se agrupar ferramentas por categorias (ex: modernas vs tradicionais)

In [42]:
# Seleção de colunas relevantes
colunas_ferramentas = [
    # Linguagens
    "4.d.1_SQL",
    "4.d.3_Python",
    # BI
    "4.j.1_Microsoft PowerBI",
    "4.j.3_Tableau",
    "4.j.7_Looker",
    # Cloud
    "4.h.1_Amazon Web Services (AWS)",
    "4.h.2_Google Cloud (GCP)",
    "4.h.3_Azure (Microsoft)",
    # Plataformas modernas
    "4.g.22_Google BigQuery",
    "4.g.26_Snowflake",
    "4.g.27_Databricks",
]

In [43]:
# Copiar dados apenas das colunas necessárias
df_tools = df[["grupo_idade"] + colunas_ferramentas].copy()

# Converter para formato longo
df_melt = df_tools.melt(id_vars="grupo_idade", var_name="Ferramenta", value_name="Usa")

# Filtrar respostas positivas (uso declarado)
df_melt = df_melt[df_melt["Usa"] == True]

# Agrupar por grupo etário e ferramenta
uso_por_idade = (
    df_melt.groupby(["grupo_idade", "Ferramenta"]).size().reset_index(name="Quantidade")
)

# Total por grupo para calcular proporção
total_por_grupo = df.groupby("grupo_idade").size().to_dict()
uso_por_idade["Proporcao"] = uso_por_idade.apply(
    lambda row: row["Quantidade"] / total_por_grupo.get(row["grupo_idade"], 1), axis=1
)

In [44]:
# Gráfico
fig = px.bar(
    uso_por_idade,
    x="Ferramenta",
    y="Proporcao",
    color="grupo_idade",
    barmode="group",
    title="Adoção de Ferramentas por Grupo Etário",
    labels={"Proporcao": "Proporção de Uso", "grupo_idade": "Faixa Etária"},
    text="Quantidade",
)
fig.update_layout(xaxis_tickangle=-45)
fig.show()

In [46]:
# Outra versão
# Filtrar colunas relevantes (exemplo com visualização + análise + BI)
cols_visual = [col for col in df.columns if col.startswith("4.b.")]
cols_analise = [col for col in df.columns if col.startswith("7.c.")]
cols_bi = [col for col in df.columns if col.startswith("4.j.")]
cols_total = cols_visual + cols_analise + cols_bi

# Copiar e transformar para formato longo
df_melt = df[["grupo_idade"] + cols_total].melt(
    id_vars="grupo_idade", var_name="ferramenta", value_name="usa"
)
df_melt = df_melt[df_melt["usa"] == True]

# Agrupar por grupo etário e ferramenta
uso = (
    df_melt.groupby(["grupo_idade", "ferramenta"]).size().reset_index(name="quantidade")
)

# Total por grupo
total_grupo = df["grupo_idade"].value_counts().to_dict()
uso["proporcao"] = uso.apply(
    lambda row: row["quantidade"] / total_grupo[row["grupo_idade"]], axis=1
)

# Dicionário de categorização das ferramentas
mapa_modernas = {
    "powerbi": "Tradicional",
    "excel": "Tradicional",
    "tableau": "Tradicional",
    "spss": "Tradicional",
    "sas": "Tradicional",
    "looker": "Moderna",
    "snowflake": "Moderna",
    "databricks": "Moderna",
    "bigquery": "Moderna",
    "dbt": "Moderna",
    "chatgpt": "Moderna",
}


# Criar nova coluna com categoria (moderna vs tradicional)
def classificar_categoria(ferramenta):
    f = ferramenta.lower()
    for chave in mapa_modernas:
        if chave in f:
            return mapa_modernas[chave]
    return "Outros/Não categorizado"


uso["categoria"] = uso["ferramenta"].apply(classificar_categoria)

# Agrupar por grupo etário e categoria
uso_categoria = (
    uso.groupby(["grupo_idade", "categoria"])["quantidade"].sum().reset_index()
)

uso_categoria["proporcao"] = uso_categoria.apply(
    lambda row: row["quantidade"] / total_grupo[row["grupo_idade"]], axis=1
)

In [47]:
fig = px.bar(
    uso_categoria,
    x="grupo_idade",
    y="proporcao",
    color="categoria",
    text="quantidade",
    barmode="stack",
    title="Proporção de Uso de Ferramentas por Categoria e Faixa Etária",
    labels={
        "grupo_idade": "Grupo Etário",
        "proporcao": "Proporção",
        "categoria": "Categoria de Ferramenta",
    },
)
fig.update_layout(yaxis_tickformat=".0%")
fig.show()